### ISSUE TITLE
Can't compile source code

### ISSUE THREAD

**Issue by fluancefg** [2ndQuadrant/pglogical#1]
Hi,

I would like to try the pglogical and pglogical-output extensions, but I can't compile the source code with the tarballs provided and PostgreSQL 9.4.7 and I can't find any documentation on how to do it.

`Makefile:41: ../../src/Makefile.global: No such file or directory`
`Makefile:42: /contrib/contrib-global.mk: No such file or directory`
`make: *** No rule to make target '/contrib/contrib-global.mk'.  Stop.`

**Comment by ringerc** [comment]
Right, we used to distribute it as a patch against the PostgreSQL source tree so that wasn't required. 

It's compiled like most PostgreSQL extensions, using PGXS:

Make sure your PostgreSQL's `pg_config` is on your `PATH` then pass `USE_PGXS=1` to `make`, e.g.

    PATH=/usr/pgsql-9.4/bin:$PATH make USE_PGXS=1 clean all

I'll add a note to the docs.

**Comment by ringerc** [comment]
Added to README

**Comment by fluancefg** [comment]
Thanks, I didn't know PGXS.
