### ISSUE TITLE
Upgraded to RHEL2.0 unable to update existing installation, unable to drop extension

### ISSUE THREAD

**Issue by asr1901** [2ndQuadrant/pglogical#103]
I installed the new pglogical 2.0 on our RHEL databases.  Previously we were using 1.2.  However, 'alter extension update' shows this error:  ERROR:  cache lookup failed for relation pglogical.depend

I could live with re-creating my replication sets, etc. so I did:

DROP EXTENSION pglogical CASCADE;

This also fails with the error: ERROR:  cache lookup failed for relation pglogical.depend

Any ideas how I can get logical replication working again?  I am completely stuck, unable to drop the extension to recreate replication sets and similarly unable to upgrade my extension.

In the meantime, even trying to recreate my old subscriptions with the upgraded binaries (but non-updated pglogical extension) fails.

Additionally, my error logs on both the subscriber and primary are filled with this: 

LOG:  manager worker [12770] at slot 0 generation 60 crashed
LOG:  worker process: pglogical manager 21705 (PID 12770) exited with exit code 1
LOG:  unregistering background worker "pglogical manager 21705"

**Comment by PJMODOS** [comment]
Yes, sorry for that, 2.0.1 will fix it soon (the code is already in the REL2_0_STABLE branch).
