### ISSUE TITLE
Can't restore view when using pglogical

### ISSUE THREAD

**Issue by fluancefg** [2ndQuadrant/pglogical#104]
Hi,
I have dumped a database in which is installed pglogical.
However, because pglogical automatically adds a trigger when a new table is created, pg_restore is not able to restore a view when it's splitted in two commands: 
`CREATE TABLE myview (...)`
`CREATE RULE "_RETURN" AS
ON SELECT TO myview DO INSTEAD  SELECT ...`

When it tries to create the rule, the following error occurs:
`ERROR:  could not convert table "myview" to a view because it has triggers`

And a simple check confirms that there's a trigger on the table:
`SELECT tgname, tgfoid FROM pg_trigger WHERE tgrelid = 'myschema.myview'::regclass;`

```
tgname              |  tgfoid 
---------------------------------+----------
queue_truncate_trigger_11078295 | 11077522
```

`SELECT pg_get_functiondef(11077522);`
```
pg_get_functiondef                         
----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pglogical.queue_truncate()
RETURNS trigger
LANGUAGE c
AS '$libdir/pglogical', $function$pglogical_queue_truncate$function$
```

**Comment by PJMODOS** [comment]
This should be solved in pglogical 2.x so I'd recommend upgrading.

**Comment by fluancefg** [comment]
Ok, thanks. But at the moment I'm stucked with #90

**Comment by PJMODOS** [comment]
Yeah that one needed new release unfortunately, so 2.0.1 it is.
