### ISSUE TITLE
Error unknown column

### ISSUE THREAD

**Issue by patdenis** [2ndQuadrant/pglogical#107]
i test this situation:
1- add table01 to repset in provider
2- test replication and is OK
3- add column (col10) in provider
4- execute query on  table01, include col10 (on provider) 
5- in log file i get: ERROR:  unknown column name col10
6- replication go "down"

if i execute alter_subscription_resynchronize_table with table01 (in subscriber), replication go to "replicating", but alter_subscription_resynchronize_table truncate table and resync all data.

But i if execute alter_subscription_disable and alter_subscription_enable instead of resynchronize, replication remains down and alter_subscription_resynchronize_table don't work anymore. i must restart server.
there is a "safe way" to manage replication "down" when i get ERROR:  unknown column name col10?

thanks

**Comment by PJMODOS** [comment]
You can't have missing column on subscriber unless you use column filtering explicitly when publishing the table (see documentation of `pglogical.create_subscription` function). The replication will always go down and stay down in that situation otherwise.
