### ISSUE TITLE
when make has error:*** No rule to make target `/usr/local/src/postgresql-9.4.9/contrib/pglogical/pglogical_dump/Makefile'.  Stop.

### ISSUE THREAD

**Issue by weiboyiyou** [2ndQuadrant/pglogical#108]
make[1]: Entering directory `/usr/local/src/postgresql-9.4.9/contrib/pglogical/pglogical_dump'
make[1]: /usr/local/src/postgresql-9.4.9/contrib/pglogical/pglogical_dump/Makefile: No such file or directory
make[1]: *** No rule to make target `/usr/local/src/postgresql-9.4.9/contrib/pglogical/pglogical_dump/Makefile'.  Stop.
make[1]: Leaving directory `/usr/local/src/postgresql-9.4.9/contrib/pglogical/pglogical_dump'
make: *** [all-pglogical_dump-recurse] Error 2

**Comment by PJMODOS** [comment]
If you are building from git you need to initialize and update the submodules.
