### ISSUE TITLE
Synchronous multiple databases replica

### ISSUE THREAD

**Issue by ubupirata** [2ndQuadrant/pglogical#110]
I need different databases on provider node to be replicated on different subscriber node in synchronous way.
From documentation it seems be possible in asynchronous way, setting up individual provider/subscriber relationships for each database. In synchronous mode i have to use pglogical subscription name in _synchronous_standby_names_, but subscription name must be unique in a node.
Is there a way to make so?
Thanks

**Comment by ubupirata** [comment]
The solution is to give subscriptions on different node the same name, because every node is related to a single database, not to all postmaster (this was the point that i didn't understood)
Perhaps could be useful some explanations in documentation?

**Comment by ubupirata** [comment]
If i give same name to different subscriptions, only one is selected by postgresql as synchronous replica.
So i renew my problem: i need different subscriptions connected to different database to work in synchronous mode. Is there a way to do so? The only solution i found is to install multiple instances of postgresl server ...

**Comment by PJMODOS** [comment]
There is no way to do this that I know of.

**Comment by ubupirata** [comment]
Thank you very much for the response, i supposed it was so. It is written explicitely in documentation:
https://www.postgresql.org/docs/9.6/static/logicaldecoding-synchronous.html

**Comment by PJMODOS** [comment]
Yeah, eventually it would be nice to do this somehow per database, but currently the mechanism in PostgreSQL is global for whole instance and based on WAL position and we simply reuse that mechanism. So we'll need to think of how to add support for this in PostgreSQL itself.

**Comment by ubupirata** [comment]
Ok, thanks again for your support
