### ISSUE TITLE
undefined symbol: EncodeSpecialTimestamp

### ISSUE THREAD

**Issue by afefelov** [2ndQuadrant/pglogical#111]
Hello,

First of all, thanks for your product.
While installing pglogical into docker running postgres // psql (9.4.4, server 9.4.5)
found following error on server start:

FATAL:  could not load library "/usr/lib/postgresql/9.4/lib/pglogical.so": /usr/lib/postgresql/9.4/lib/pglogical.so: undefined symbol: EncodeSpecialTimestamp

**Comment by afefelov** [comment]
root@6eb8284c1ffd:/# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

**Comment by afefelov** [comment]
Found problem. Postgres itself should be updated till latest in 9.4 branch, it works with 9.4.12

**Comment by shumingking** [comment]
we install pglogical2.0.1 into postgres9.4.1 found the same error:
FATAL: could not load library "/usr/lib/postgresql/9.4/lib/pglogical.so": /usr/lib/postgresql/9.4/lib/pglogical.so: undefined symbol: EncodeSpecialTimestamp
in addition to upgrade to the 9.4.12,other solutions?

**Comment by afefelov** [comment]
@shumingking you have to update to latest postgres94 which is 9412 atm, so it will work

**Comment by thunderbird86** [comment]
postgresql-server-dev-9.4/trusty-pgdg,now 9.4.14-1.pgdg14.04+1 amd64 
postgresql-9.4-pglogical/jessie-2ndquadrant

Have the same problem

**Comment by maxpinto** [comment]
could you share a guide to upgrade from postgresql 9.4.4 to 9.4.12?,
