### ISSUE TITLE
pglogical_output consumer

### ISSUE THREAD

**Issue by patdenis** [2ndQuadrant/pglogical#117]
Hi, 
there is the possibility to implement an external consumer for pglogical_output?
there is a short guide?
i want to find a solution for connection drop from master to replica (when connection in over WAN).
it that case if i don't resolve connection error my pg_xlog folder go full and my cluster will dead.
thanks
Denis

**Comment by eulerto** [comment]
It is possible to create external consumers for any output plugin including `pglogical_output`. See this [documentation](https://github.com/2ndQuadrant/pglogical/blob/REL2_x_STABLE/internals-doc/OUTPUT.md) and check the [available parameters](https://github.com/2ndQuadrant/pglogical/blob/REL2_x_STABLE/pglogical_output_config.c#L82).

If you are using Postgres 13, there is a parameter [max_slot_wal_keep_size](https://www.postgresql.org/docs/13/runtime-config-replication.html#RUNTIME-CONFIG-REPLICATION-SENDER) that specifies the maximum amount of WAL that can be reserved by replication slots.
