### ISSUE TITLE
unusual slow replication

### ISSUE THREAD

**Issue by noizo** [2ndQuadrant/pglogical#118]
Hi.

Have to replicate one table 180GB in size from PG 9.5.4 to 9.6.3.
It starts normally, and at around 20GB of data replicated, it starts to be very slowly.
It took 96h to replicate 119Gb, and it behave strange when i'm looking at `df -H`
It show 119Gb, then it drops to 118, and it can do so several times.
I have `max_wal_size = 10Gb`, not sure if i can do anything else.

I've been replicating DB's with more then 300Gb, and it all was fine (still, there were more tables, then just one)

Is there anything i can do to speed up process?

**Comment by mchhatani** [comment]
I am also facing the same problem where for large tables initial copy takes very long time.

**Comment by Andersson007** [comment]
I have the same problem. The database has 90Gb size. It's been running 45 minutes and just 20Gb are replicated. Perhaps it will never to be replicated for a 2TB base.

**Comment by Andersson007** [comment]
It was very thrillingly for our production) 1.37 Tb base has been copied for 26 hours. The biggest table 260 Gb for 8 hours. Average writing speed was about 20-40 mb/sec, sometimes 1-2 mb/sec for hours. I observed the same behavior for big tables (larger than 10-20gb) and it was not related with number of queries to the database. Network bandwidth is more than 10 gbit/sec. ln that time the database was handling queries much slowly

**Comment by GEverding** [comment]
I think I'm seeing the same behaviour. Is there any configuration that can speed this up?

**Comment by eulerto** [comment]
There isn't sufficient information that exposes a possible pglogical limitation. It is hard to investigate without additional information besides "it took x hours to the initial sync" or "it is copying at a rate of y MB/s". If it is still an issue, I recommend that you provide CPU, IO, network information using any monitoring tool (`top`, `iostat`, `ps`, `sar`, ...). Depending on the situation, a `strace` output from wal sender (on provider) or pglogical sync / pglogical apply (on subscriber) can help identify the problem. A perf report output could also be useful.
