### ISSUE TITLE
Postgres-XL problem

### ISSUE THREAD

**Issue by ElmirSecerbegovic** [2ndQuadrant/pglogical#122]
We have a Postgres-XL 9.5r1.6 cluster running our AWS EC2 instances. We are trying to make this cluster subscriber to our regular Postgres instance but once we add "shared_preload_libraries = 'pglogical'" to our postgresql.conf we receive next error on startup:

LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  cluster monitor started
LOG:  autovacuum launcher started
LOG:  starting pglogical supervisor
LOG:  worker process: pglogical supervisor (PID 13836) was terminated by signal 11: Segmentation fault
LOG:  terminating any other active server processes

If we comment pglogical line than everything is running fine. We have followed PgLogical installation steps and use postgresql95-pglogical option.

Are we doing something wrong here?

**Comment by pavanvd** [comment]
@ElmirSecerbegovic would it be possible for you to get a backtrace of the failing process? You will need to enable core dumps if it's not already. Then attach the core to a debugger and get a full backtrace.

**Comment by ElmirSecerbegovic** [comment]
Sorry for delay. We have manage to dump couple of core.pid files and after using it with gdb we get similar message as already stated in LOG file

[New LWP 29225]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `postgres: bgworker: pglogical supervisor                                      '.
Program terminated with signal 11, Segmentation fault.
#0  start_manager_workers () at pglogical.c:606
606                     Form_pg_database        pgdatabase = (Form_pg_database) GETSTRUCT(tup);

**Comment by ElmirSecerbegovic** [comment]
After updating pg_logical to release 2.1 Postgres-XL server is starting normaly. So, could it be issue with pg_logical release 2.0 ?

**Comment by eulerto** [comment]
Since it worked in version 2.1, I'm closing this issue.
