### ISSUE TITLE
Fails to build against latest v10

### ISSUE THREAD

**Issue by mbanck** [2ndQuadrant/pglogical#124]
If I try to build 2.0.1 (but master seems to be unchanged in this regard) against v10 RC1 I get:

```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fdebug-prefix-map=/build/postgresql-10-ccxnXW/postgresql-10-10~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/<<PKGBUILDDIR>>/compat10 -I. -I/<<PKGBUILDDIR>> -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_functions.o /<<PKGBUILDDIR>>/pglogical_functions.c
/<<PKGBUILDDIR>>/pglogical_functions.c: In function 'pglogical_drop_subscription':
/<<PKGBUILDDIR>>/pglogical_functions.c:604:4: error: too few arguments to function 'replorigin_drop'
    replorigin_drop(originid);
    ^~~~~~~~~~~~~~~
In file included from /<<PKGBUILDDIR>>/pglogical_functions.c:49:0:
/usr/include/postgresql/10/server/replication/origin.h:44:13: note: declared here
 extern void replorigin_drop(RepOriginId roident, bool nowait);
             ^~~~~~~~~~~~~~~
<builtin>: recipe for target 'pglogical_functions.o' failed
make[2]: *** [pglogical_functions.o] Error 1
```

Indeed, in `b2c95a37`, this got changed:

```
-extern void replorigin_drop(RepOriginId roident);
+extern void replorigin_drop(RepOriginId roident, bool nowait);
```

**Comment by mbanck** [comment]
There's a second instance of this in `pglogical_sync.c` and all the `ExecAR*Trigger`  calls need an additional `NULL` argument at the end due to `501ed02c`

**Comment by pallavisontakke** [comment]
Hi @mbanck , could you please move this Issue to repo : https://github.com/2ndQuadrant/pglogical_internal/  
This repo is an old one. pglogical-internal repo is the one which is active/ Issues are tracked fine there.

**Comment by mbanck** [comment]
@pallavisontakke https://github.com/2ndQuadrant/pglogical_internal/ is a non-public repository.

**Comment by pallavisontakke** [comment]
Alright raised as issue over there - linking this Issue:
https://github.com/2ndQuadrant/pglogical_internal/issues/153

**Comment by tbartelmess** [comment]
Any update here?

**Comment by mbanck** [comment]
@tbartelmess not from upstream, but you can grab my working patch from here if you like:

https://anonscm.debian.org/cgit/pkg-postgresql/pglogical.git/tree/debian/patches/v10_compatibility.patch

**Comment by pallavisontakke** [comment]
pglogical 2.1 packages are ready, with some final sanity testing they'll be released soon.

**Comment by PJMODOS** [comment]
REL2_0_STABLE and  REL2_1_0 work with PG10 now.
