### ISSUE TITLE
Expand support for forward_origins

### ISSUE THREAD

**Issue by EliSnow** [2ndQuadrant/pglogical#128]
The documentation currently states for the `forward_origins` parameter:
> currently only supported values are empty array meaning don't forward any changes that didn't originate on provider node, or "{all}" which means replicate all changes no matter what is their origin

In addition to being able to explicitly specify different provider origins, it would also be nice to have a value which meant "not from the local node". This would be very helpful with bi-directional replication.

**Comment by PJMODOS** [comment]
That's what empty array/NULL means, it will not forward any changes from other nodes.

**Comment by EliSnow** [comment]
@PJMODOS, perhaps I misunderstand the documentation, but if I have a bi-directional setup like `A <---> B <---> C` (which is to say that node A is subscribed to table foo on node B, node B is subscribed to table foo on nodes A and B, and node C is subscribed to table foo on node B), if I have `forward_origins := {}`, and I insert a record into C, won't that record never show up on A because it did not originate on B?
