### ISSUE TITLE
Synchronization status unknown

### ISSUE THREAD

**Issue by trourance** [2ndQuadrant/pglogical#129]
Hi,

I'm not sure if it's a bug or a misunderstanding on how it works, but for some of the replicated tables, I get a status "unknown" on the subscriber when I call `select * from pglogical.show_subscription_table(subscription_name name, relation regclass);`.
In fact, I've discovered that 5 tables are missing when I issue `select * from pglogical.local_sync_status;` on the subscriber.
On the provider: `select * from pglogical.replication_set_table;` returns 40 lines for the set_id used.
On the subscriber: `select * from pglogical.tables;` returns the same 40 tables. But, `select * from pglogical.local_sync_status;` returns only 35 tables even if the data seem synchronized for the missing tables.
I'm using pglogical 2.0.1 with postgresql 9.5.7 on both sides.

**Comment by unotech001** [comment]
Hellow fluancefg 
 
Can you please provide me the Repo of pglogical 2.0.1

**Comment by fluancefg** [comment]
`deb http://packages.2ndquadrant.com/pglogical/apt/ trusty-2ndquadrant main` on both sides

**Comment by eulerto** [comment]
I could reproduce this issue. If you still observe this problem with the latest pglogical version, please open a new issue. Make sure to include a detailed description on how to reproduce it.
