### ISSUE TITLE
cant get repository of pglogical 2.0

### ISSUE THREAD

**Issue by unotech001** [2ndQuadrant/pglogical#130]
Dear Team,

WE were installed pglogical version 1.0.1 and replicated the tables.
Now we want to replicate particular columns and row_filter while replication process

But we get errror massage of after executing below command 
 select pglogical.replication_set_add_table('replicationset','warehouse_mst',true,row_filter := 'dwh_id > 3');

Error :- " function pglogical.replication_set_add_table(unknown, unknown, boolean, row_filter => unknown) does not exist"
Hint :- No function matches the given name and argument types. You might need to add explicit type cast

If any budyy have repository file of pglogical version 2.0  ???????

Note :- we are working on postgresql verion 9.5

**Comment by PJMODOS** [comment]
Hi, I am not sure what kind of repository are you referring to, source repository is right here in this github project, packaging repositories are at http://packages.2ndquadrant.com/pglogical/

**Comment by unotech001** [comment]
Hi PJMODOS,

Thanks for Reply

we has installed below rpm file 
rh-postgresql95-postgresql-pglogical-1.0.1-3_2ndQuadrant.el7.centos.src.rpm
rh-postgresql95-postgresql-pglogical-output-1.0.1-2_2ndQuadrant.el7.centos.src.rpm

but we are unable to use columns wise replication and row filter function while replication.

what to do ??  Please help

**Comment by PJMODOS** [comment]
Upgrade, column and row filtering is not supported in pglogical 1.0, you need 2.x.

**Comment by unotech001** [comment]
Thanskss

Can you Please provide me the link to download the pglogical 2.x  ??????
