### ISSUE TITLE
pglogical update 2.0.1 to 2.1.0

### ISSUE THREAD

**Issue by igalchich** [2ndQuadrant/pglogical#132]
Dear Team!

I try to update pglogical 2.0.1. So I've downloaded^
postgresql96-pglogical-2.1.0-1.el7.x86_64.rpm
Done:
rpm -Uhv postgresql96-pglogical-2.1.0-1.el7.x86_64.rpm

After. I tried to update pglogical:
alter extension pglogical update;
But, I could not:
ERROR:  could not find function "pglogical_wait_slot_confirm_lsn" in file "/usr/pgsql-9.6/lib/pglogical.so"

**Comment by unotech001** [comment]
Please restart your postgresql service and then try again.
It worked for me.

**Comment by ringerc** [comment]
You must restart the PostgreSQL server too.​
