### ISSUE TITLE
incremental update mechanism?

### ISSUE THREAD

**Issue by cailin-lai** [2ndQuadrant/pglogical#134]
Hi Guys,
May I know something internals about replication for the row(s) which updated by the provider node?
Let I say, a case likes following,
-provider node is a single table, accepts any updates.
-subscription node is desired to be read only, the data only comes from provider node(s) by replication. Additionally, the table in subscription is partitioned. It works fairly well for inserted cases, of course.
Well, for the update tuple case, I think it might rely on the primary key to locate tuple in subscription side that likely perform a update sentence.  That brings trouble to me since the table is partitioned, the primary key (e.g. like sequence) is usually not sufficient to locate which table contains this tuple in case of the tables were partitioned by a date type column.
In this case, can I add row filter as a workaround? i.e. add row filter likes, 
[arrival_time between '2017-10-01' and '2017-10-02']
Then, would the update sentence be executed as {update table_A set col1=$val1,... where pk=$pk and arrival_time between '2017-10-01' and '2017-10-02' } to leverage the tuple locating process?
Much appreciate for help!

**Comment by eulerto** [comment]
pglogical does not provide an option to modify in-flight tuples before applying them into the subscriber.

**Comment by cailin-lai** [comment]
It indeed was a specific legacy issue. Thanks team anyway!
