### ISSUE TITLE
Sequence replication should be mentioned in the Quick Setup instructions

### ISSUE THREAD

**Issue by rosenfeld** [2ndQuadrant/pglogical#136]
The current procedures in that guide will seem to work, and that's why it's dangerous. Once you notice it worked you may try to use it to migrate the production data. Specially when there's a gap in the first ids, which means things would seem to work with the application initially until the first conflict with existing primary key.

It's a good idea to append to this line:

```sql
SELECT pglogical.replication_set_add_all_tables('default', ARRAY['public']);
-- new instruction below:
SELECT pglogical.replication_set_add_all_sequences('default', ARRAY['public']);
```

It avoids having to find later that the sequences should be updated manually.

**Comment by MichaelDBA** [comment]
I concur.  I just found out that adding a row on the subscriber will attempt to use the number 1 as the next sequence ID for any table.  This was after I used pg_dump directly to export and create the schema objects only on the subscriber.  I then used pglogical to just move the data initially from the provider to the subscriber.

But if I already have the sequences on the subscriber, will the **pglogical.replication_set_add_all_sequences** api update the nextval to be in sync with the provider?

**Comment by rosenfeld** [comment]
Hi, I first suggesting adding those statements to the documentation, but after that I tried that approach and it didn't work either. I've written an article explaining how I upgraded from 9.6 to 10 using pglogical and it explains to handle sequences as well:

https://rosenfeld.page/articles/infrastructure/2017_11_10_upgrading_postgresql_from_9_6_to_10_with_minimal_downtime_using_pglogical

**Comment by MichaelDBA** [comment]
So, pglogical does not handle updating sequences when migration is intended.  So we have to come up with our own solutions.  I spent some more time on this and I came up with some solutions based on using pglogical for migration.  There are a few things we could do:

1.  Update the sequences right before the short downtime where we fence out the former cluster and point to the new one that has been updated through pglogical.  That could be done using Rosenfeld's suggestion about exporting the next usable sequence id on the subscriber + some arbitrary number that is expected to be higher than any ensuing inserts from that time until the failover occurs. I will not duplicate the first solution since Rosenfeld did that already in his link mentioned above.

2. While both publisher and subscriber are up, disconnect all clients from the publisher and export the setvals generated in the next statement on the publisher to a file and run them against the subscriber.
```
select 'SELECT setval(''' || n.nspname || '.' || c.relname || ''',' || nextval('' || n.nspname || '.' || c.relname || '') || ',false);' as ddl FROM pg_catalog.pg_class c LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace WHERE c.relkind IN ('S','') AND n.nspname not in ('pg_catalog','pg_toast','information_schema', 'pglogical') AND pg_catalog.pg_table_is_visible(c.oid) ORDER BY 1;
-->
 SELECT setval('public.actor_actor_id_seq',207,false);
 SELECT setval('public.address_address_id_seq',611,false);
 SELECT setval('public.category_category_id_seq',22,false);
```
3.  When the publisher is stopped, execute setvals on the subscriber based on the max(sequence id value) + 1.
```
select 'SELECT setval(''' || n.nspname || '.' || c.relname || ''',' || '(select max(' || co.column_name || ') from ' || co.table_schema || '.' || co.table_name || ') + 1, false);' as ddl FROM pg_catalog.pg_class c LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace JOIN information_schema.columns co on n.nspname = co.table_schema and co.column_default like '%' || c.relname || '''::regclass)' WHERE c.relkind IN ('S','') AND n.nspname not in ('pg_catalog','information_schema','pg_toast','pglogical') AND pg_catalog.pg_table_is_visible(c.oid) ORDER BY 1;
-->
 SELECT setval('public.actor_actor_id_seq',(select max(actor_id) from public.actor) + 1, false);
 SELECT setval('public.address_address_id_seq',(select max(address_id) from public.address) + 1, false);
 SELECT setval('public.category_category_id_seq',(select max(category_id) from public.category) + 1, false);
 SELECT setval('public.city_city_id_seq',(select max(city_id) from public.city) + 1, false);
 SELECT setval('public.country_country_id_seq',(select max(country_id) from public.country) + 1, false);
```

**Comment by MichaelDBA** [comment]
I just saw this 2nd Quadrant blog by Petr Jelinek, dated  December 13, 2017, '''pglogical 2.1 and Logical Replication in PostgreSQL 10'''.  It  states the following:

> Somewhat related to the on-line upgrades is the support for sequence replication. In pglogical you can add sequences to replication just like you add tables. In PostgreSQL 10 there is no provision for replicating sequences.

So it does appear that we have to code sequence workarounds when using pglogical for major migrations.

**Comment by jjb** [comment]
@MichaelDBA I think that quote is saying pglogical _does_ support replicating sequences, but native logical replication (introduced in 10) does not.

**Comment by jjb** [comment]
This sets up all sequences:

```sql
select pglogical.replication_set_add_all_sequences(set_name := 'default', schema_names := ARRAY['public'], synchronize_data := true)
```

But they are synced over at undefined times. To force sync them over (such as, during a db migration, after disconnecting all clients from the old db and before dropping the subscriber on the new db):

```sql
select pglogical.synchronize_sequence( seqoid ) from pglogical.sequence_state;
```

**Comment by MichaelDBA** [comment]
Thanks soooo much for this function, select pglogical.synchronize_sequence( seqoid ) from pglogical.sequence_state;

I think this issue can be closed now, @rosenfeld?

**Comment by rosenfeld** [comment]
Yes, I think so.

**Comment by jjb** [comment]
should there be a change to the Quick Setup instructions?

**Comment by mcansky** [comment]
Almost 3 years after the last comment I stumbled upon the same problem: I didn't know sequences were not synchronized and now I have to redo a clean, freeze, and resync of a DB.
I think it would be **great** to have something included clearly mentioning the sequences sync step in the documentation.

**Comment by mcansky** [comment]
> Hi, I first suggesting adding those statements to the documentation, but after that I tried that approach and it didn't work either. I've written an article explaining how I upgraded from 9.6 to 10 using pglogical and it explains to handle sequences as well:
> 
> https://rosenfeld.herokuapp.com/en/articles/infrastructure/2017-11-10-upgrading-postgresql-from-9-6-to-10-with-minimal-downtime-using-pglogical

@rosenfeld this is basically a 404 at the moment, https://rosenfeld.page/articles/infrastructure/2017_11_10_upgrading_postgresql_from_9_6_to_10_with_minimal_downtime_using_pglogical this looks like the new home for it

**Comment by rosenfeld** [comment]
Right, I moved from Heroku to a custom instance since Heroku stopped offering the free plan. Thanks for updating the link.
