### ISSUE TITLE
Provider has correct data but pglogical.alter_subscription_synchronize still reports status=unknown

### ISSUE THREAD

**Issue by PerRommetveit** [2ndQuadrant/pglogical#137]
Both provider and subscriber are running these versions:
PostgreSQL 9.6.4 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit
pglogical | 2.0.1   | pglogical  | PostgreSQL Logical Replication

Logical replication is set up from provider to subscriber.

On provider the following commands were run:

select pglogical.replicate_ddl_command('alter table myschema.mytable add column first TEXT NOT NULL default ''''','{my_replication_set}'::text[]);
select pglogical.replicate_ddl_command('alter table myschema.mytable add column second TEXT NOT NULL default ''''','{my_replication_set}'::text[]);
select pglogical.replicate_ddl_command('alter table myschema.mytable drop column third','{my_replication_set}'::text[]);
select pglogical.replicate_ddl_command('alter table myschema.mytable add column fourth text not null default ''''','{my_replication_set}'::text[]);

Then I ran this sql on the provider and the subscriber:

select count(*) from  myschema.mytable ; SELECT md5(CAST((array_agg(myschema.mytable* order by ref))AS text)) FROM  myschema.mytable;

Which gave the same row count and identical hash for both.

Then running this command on subscriber: select * from pglogical.show_subscription_table('my_replication_set','myschema.mytable');

gave status=unknown. and not status=synchronized as expected.

Running this command on the subscriber fixed the issue:

select pglogical.alter_subscription_synchronize('my_replication_set');

Should it be necessary to run pglogical.alter_subscription_synchronize here?

**Comment by trourance** [comment]
Most probably the same as #129

**Comment by eulerto** [comment]
I could reproduce this issue. If you still observe this problem with the latest pglogical version, please open a new issue.
