### ISSUE TITLE
Posgresql 10.1 support?

### ISSUE THREAD

**Issue by twidi** [2ndQuadrant/pglogical#138]
I try to migrate a server with PG 9.6 to a new one with PG 10.1, so I installed the APT packages.

But I get this error on the subscriber, and this time I cannot find anything useful on internet, except the pglogical code source.

> pglogical subscriber init found pg_dump with wrong major version 10.1, expected 10.0

Is this really related to pglogical not supporting PG 10.1 yet? Or I missed something totally obvious ? :)

Thanks if anyone has any hint about this.

**Comment by twidi** [comment]
I guess this is related to this: https://github.com/2ndQuadrant/pglogical/blob/a378ca5383be8a19f77ec70cd00511d9a906d1b6/pglogical_sync.c#L102-L105

Because PG changed the versioning, now 10.1 is to 10 as 9.6.6 was to 9.6.5. So it should be `10` and not `100` for PG version > 10

**Comment by MichaelDBA** [comment]
I have the same problem after upgrading PG to 10.1.  Is there anything we can do to fix this in the interim?

**Comment by ringerc** [comment]
Fixed by a recent commit in the REL2_x_STABLE branch:

https://github.com/2ndQuadrant/pglogical/commit/fa8adb3924a73fea25ffedb4c6992aa7acc643e4

**Comment by GMLudo** [comment]
Hi,

Do you have an idea when the 2.1.1 could be released ?
It's annoying for us, because we have migrated to PostgreSQL 10 and we want to use pglogical.

We have the knowledge to backport this commit and regenerate Debian packages, but I imagine we aren't alone interested in with that.

Regards.

**Comment by KristjanTammekivi** [comment]
Please release this, it's been way too long...

**Comment by KristjanTammekivi** [comment]
Nevermind, release was today. Thanks!
