### ISSUE TITLE
create_subscription() with synchorize_structure := true creates objects not in the replication set

### ISSUE THREAD

**Issue by mw2q** [2ndQuadrant/pglogical#14]
| provider (pg1) | subscriber (pg2) |
| --- | --- |
| create database 94to94p; | create database 94to94s |
| \c 94to94p | \c 94to94s |
| create table a (z integer primary key); | |
| create schema s1; | |
| create table s1.a (z integer primary key); | |
| create schema s2; | |
| create table s2.a (z integer primary key); | |
| select * from pglogical.create_replication_set(set_name := 's1'); | |
| | SELECT pglogical.create_subscription(subscription_name := 'subscription1', replication_sets := ARRAY['s1'], provider_dsn := 'host=pg1 dbname=94to94p'); |

Schema s1 and s2, and tables public.a, s1.a and s2.a are created on the subscriber.

**Comment by PJMODOS** [comment]
That's known limitation, there isn't plan to change this in near future.
