### ISSUE TITLE
Question: any system functions not supported for pglogical?

### ISSUE THREAD

**Issue by MichaelDBA** [2ndQuadrant/pglogical#140]
Where I am going with this is how logical replication works in MySQL for statement-based replication, which seems to be the same as logical replication for PostgreSQL, where statements are replayed on the subscriber cluster.  For instance, if I am inserting a timestamp field on the provider, is there any change to the millisecond portion of the timestamp might be a little later on the subscriber cluster if there is a few milliseconds delay on the replication?

For example, inserting `current_timestamp` into a user table on the provider cluster.

**Comment by eulerto** [comment]
Postgres implements a different approach. [Logical replication](https://www.postgresql.org/docs/current/logical-replication.html) replicates data; it **doesn't** replicate commands. It means that volatile functions won't interfere in the replicated data. In summary, you will always have the same data from the origin (unless you have a trigger that changes the data on the subscriber). Keep in mind that function `pglogical.replicate_ddl_command` bypass this concept (and, in fact, it replicates statements).
