### ISSUE TITLE
CONFLICT: remote UPDATE on relation PUBLIC.TEST. Resolution: apply_remote.",,,,,,,,,"pglogical apply 13534:2849729983

### ISSUE THREAD

**Issue by qq363960630** [2ndQuadrant/pglogical#148]
pglogical 2.0.0

if replicating a large transaction and when wal_sender timeout ,provider cound not get the latest lsn,then send the repeated data

`"2012-01-03 20:30:05.018 CST,,,20908,,4f02f186.51ac,2534392,,2012-01-03 20:16:06 CST,4/6,33519,Log,23000,"CONFLICT: remote UPDATE on relation PUBLIC.TEST. Resolution: apply_remote.",,,,,,,,,"pglogical apply 13534:2849729983" 2012-01-03 20:30:05.019 CST,,,20908,,4f02f186.51ac,2534393,,2012-01-03 20:16:06 CST,4/6,33519,Log,23000,"CONFLICT: remote UPDATE on relation PUBLIC.TEST. Resolution: apply_remote.",,,,,,,,,"pglogical apply 13534:2849729983" 2012-01-03 20:30:05.019 CST,,,20908,,4f02f186.51ac,2534394,,2012-01-03 20:16:06 CST,4/6,33519,Log,23000,"CONFLICT: remote UPDATE on relation PUBLIC.TEST. Resolution: apply_remote.",,,,,,,,,"pglogical apply 13534:2849729983" 2012-01-03 20:30:05.019 CST,,,20908,,4f02f186.51ac,2534395,,2012-01-03 20:16:06 CST,4/6,33519,Log,23000,"CONFLICT: remote UPDATE on relation PUBLIC.TEST. Resolution: apply_remote.",,,,,,,,,"pglogical apply 13534:2849729983" 2012-01-03 20:30:05.019 CST,,,20908,,4f02f186.51ac,2534396,,2012-01-03 20:16:06 CST,4/6,33519,Log,23000,"CONFLICT: remote UPDATE on relation PUBLIC.TEST. Resolution: apply_remote.",,,,,,,,,"pglogical apply 13534:2849729983" 2012-01-03 20:30:05.020 CST,,,20908,,4f02f186.51ac,2534397,,2012-01-03 20:16:06 CST,4/6,33519,Log,23000,"CONFLICT: remote UPDATE on relation PUBLIC.TEST. Resolution: apply_remote.",,,,,,,,,"pglogical apply 13534:2849729983"`

**Comment by PJMODOS** [comment]
Sounds like you have been bitten by PostgreSQL bug - https://www.postgresql.org/message-id/flat/CAMsr+YHdX=XECbZshDZ2CZNWGTyw-taYBnzqVfx4JzM4ExP5xg@mail.gmail.com#CAMsr+YHdX=XECbZshDZ2CZNWGTyw-taYBnzqVfx4JzM4ExP5xg@mail.gmail.com

pglogical 2.1.1 has workaround for this. Hopefully it will be fixed soon upstream as well.

**Comment by flykent** [comment]
hi PJMODOS

i'm using version pglogical 2.1.1 to deploy the model 2 node postgres provider -> subscribe

When the provider that runs 1 dml updates an existing row, subscribe appears as an error : 

```
LOG:  CONFLICT: remote UPDATE on relation sync.my_sync (local index pm_productexpiredate_pkey).Resolution: apply_remote.

DETAIL:  existing local tuple {storeid[int4]:2199 productid[bpchar]:8935049510789        dateexpire[date]:2018-04-18 ischeck[bool]:f datecheck[timestamp]:(null) stockquantity[float4]:0 createddate[timestamp]:2018-02-26 08:35:33.283609 customerid[int4]:(null)} xid=1025115589,origin=0,timestamp=2018-02-28 10:48:09.317663+07; remote tuple {storeid[int4]:2199 productid[bpchar]:8935049510789        dateexpire[date]:2018-04-18 ischeck[bool]:t datecheck[timestamp]:2018-03-02 10:06:35.467392 stockquantity[float4]:18 createddate[timestamp]:2018-02-26 08:35:33.283609 customerid[int4]:(null)} in xact origin=1,timestamp=2018-03-02 10:06:35.471171+07,commit_lsn=0/9D278258

CONTEXT:  apply UPDATE from remote relation sync.my_sync in commit before 3515/9D278258, xid 1033489516 commited at 2018-03-02 10:06:35.471171+07 (action #2) from node replorigin 1
```
Let me know what's going on

Please help me ! Thanks PJMODOS

**Comment by bobibryan** [comment]
Do you had any news about that? Got the same issue with the 2.2.0 release.

**Comment by qq363960630** [comment]
在同步长事务的时候，master没有及时收到slave的反馈信息，造成master的wal sender recv超时（默认是60s超时时间），超时的时候，master以为同步失败，会重新发送这次的事务，所以在slave报冲突信息
In synchronizing long transactions, master does not receive feedback from slave in time, resulting in the wal sender recv timeout of master (the default is 60s timeout time). At the time of overtime, master thinks that synchronization fails, and the transaction will be re sent, so the conflict information is reported in slave.

**Comment by qq363960630** [comment]
This problem was not found in 2.2.0
