### ISSUE TITLE
ERROR:  permission denied for schema pglogical

### ISSUE THREAD

**Issue by fluancefg** [2ndQuadrant/pglogical#15]
Hi,

I have an error I do a refresh materialized view or when I launch a script in which there is a "drop temporary table" statement. In both case, I get the error above and I'm forced to apply "grant usage on schema pglogical" for the user that runs this statement.

`ERROR:  permission denied for schema pglogical`
`CONTEXT:  SQL statement "DROP TABLE pg_temp_6.pg_temp_22541_2, pg_temp_6.pg_temp_22541"`
`STATEMENT:  REFRESH MATERIALIZED VIEW CONCURRENTLY blablabla WITH DATA;`

**Comment by PJMODOS** [comment]
You need to have usage privileges on pglogical schema to be able to execute some DDL. This is because we are using event trigger mechanism. We will probably grant usage to public in next version automatically.

**Comment by vojtech-filipec** [comment]
I encountered the same behavior and it was resolved by `grant usage on schema pglogical to ...`. Just mentioning it here so that it is clear the issue persists.

Greetings from PostgreSQL 10.13!

**Comment by grahamb** [comment]
I encountered this issue during a [Rails migration](https://github.com/instructure/canvas-lms/blob/stable/db/migrate/20210510184336_add_user_index_comment_bank_items.rb) that drops and adds indexes. Doing `GRANT USAGE ON SCHEMA pglogical TO my_user` wasn't sufficient; I had to do `GRANT ALL ON SCHEMA pglogical TO my_user` in order for it to work. (Postgresql-9.6).

**Comment by tarunjain01** [comment]
> I encountered the same behavior and it was resolved by `grant usage on schema pglogical to ...`. Just mentioning it here so that it is clear the issue persists.
> 
> Greetings from PostgreSQL 10.13!

It exists in 12.6 as well.
