### ISSUE TITLE
PGlogical from standby

### ISSUE THREAD

**Issue by M1ha-Shvn** [2ndQuadrant/pglogical#151]
Hi.
Do I understand correctly, that pglogical can work from master server only as provider? For example, I have master server with streaming replication to standby. And I want to replicate some data using pglogical into new database. It's worth catching up from replica, not using master. Can it be ahcieved?
Thanks.

**Comment by ringerc** [comment]
On 7 March 2018 at 19:49, M1ha Shvn <notifications@github.com> wrote:

> Hi.
> Do I understand correctly, that pglogical can work from master server only
> as provider? For example, I have master server with streaming replication
> to standby. And I want to replicate some data using pglogical into new
> database. It's worth catching up from replica, not using master. Can it be
> ahcieved?
> Thanks.
>

Correct. This is a limitation of PostgreSQL's logical decoding facility,
not pglogical as such.

There was work to get support into PostgreSQL 10 but it fell through, and
priorities are currently elsewhere.

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services
