### ISSUE TITLE
Sync tables on demand

### ISSUE THREAD

**Issue by larsop** [2ndQuadrant/pglogical#153]
Hi 

Today we have solution  using hibernate and java to transfer diff between tables on two different database. So if two rows are deleted on master, they will be deleted on the slave when user requests for transfer of data from master to slave.  

So is it possible to achieve  something like also with pglogical  ?

So is it a way suspend transferring of data between master and slave  and when use enables it again the slave is updated with the last changes for selected tables ?

Thanks.

Lars

**Comment by ringerc** [comment]
IIRC you can resync tables that aren't part of a replication set with `pglogical.alter_subscription_resynchronize_table`, but I haven't checked.

You can pause and restart a pglogical subscription. And you can make multiple subscriptions for different subsets of tables. So you can do it that way.

Closing this as it's not a bug. Please use the bdr/pglogical mailing list for general discussion and questions.

**Comment by larsop** [comment]
Thanks for quick replay, I will check it out.

Lars
