### ISSUE TITLE
bad git submodule scheme

### ISSUE THREAD

**Issue by gecube** [2ndQuadrant/pglogical#154]
Hello colleagues,

I would like to point you that we are building the software based on your fantastic pglogical module. It is used in CI-pipeline, so we try to use external modules without modifications. I faced with the problem that submodules in pglogical are made with git:// scheme, which means that GitLab CI runner must have installed git and ssh simultaneously, but it is wrong assumption. Also it forces us to use authorization token to access public registry - it is ridiculous. I made the fork of this great project and fixed the problem, but I have no ability to maintain the fork to be up-to-date.

I'd ask you to remove submodules and add them back with https:// scheme. It will fix the CI-pipeline for us.

**Comment by eulerto** [comment]
Since this submodule (`pglogical_dump`) is needed for Postgres 9.4 and 9.4 is no longer supported for more than 1 year by PGDG, I'm afraid this issue won't be fixed.
