### ISSUE TITLE
Continue failed initialization process

### ISSUE THREAD

**Issue by M1ha-Shvn** [2ndQuadrant/pglogical#156]
Hi.
I have a big database and want to move it to another server. After 2 days of moving, a table structure error occured:
 `ERROR:  subscriber shard_subscription_1 initialization failed during nonrecoverable step (d), please try the setup again`

Is there any way to continue replication initialization without starting from the begginging? I also got a network error with same result once.

Subscription status:
`(shard_subscription_1,down,provider_db,"host=xxx port=5432 dbname=xxx",pgl_carrot_shard_1_provider_db_shard_su5aa634e,{shard_db},{all})
`

Subscription table status raises error:
```
carrot_shard_1=# SELECT pglogical.show_subscription_table('shard_subscription_1', 'messages_conversationpart');
ERROR:  set-valued function called in context that cannot accept a set
```

Trying to resync gives an FK error:
```
SELECT pglogical.alter_subscription_synchronize('shard_subscription_1', true);
ERROR:  cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "users_mergeduser" references "users_user".
HINT:  Truncate table "users_mergeduser" at the same time, or use TRUNCATE ... CASCADE.
```
But users_mergeduser contains 0 records, and error still occures.

**Comment by parihaaraka** [comment]
Hello.
Similar problem: during experimental migration (~15 hours) replica was killed by oom-killer.
Now we have in log:
> СООБЩЕНИЕ:  starting apply for subscription subscription
> ОШИБКА:  subscriber subscription initialization failed during nonrecoverable step (d), please try the setup again

Is it possible to pg_restore database and then fill it up (diff only) by means of pg_logical?
Is it possible to continue replication after temporary shut down of replica?
Thanks.

**Comment by M1hacka** [comment]
Hi, Andrei. As I've understood, the process is really divided into 3 steps:
1. Startup with `COPY ... TO STDIN` command on master
2. Catchup, based on native postgresql replication - it restores the lag between transaction when copy started and current transaction
3. Streaming - new wals are processed as they come.

If process fails during copy, it can't be recovered (pglogical restarts COPY query, but I'm not sure, what it is doing - the pipe was broken when fail occured). We tried to emulate this fall and continue the process, but not succeeded. Steps 2 and 3 can be stopped at any time, and if you solve the problem they will catchup to master. Note, that pg_xlog on master grows until copy finishes and while your replica is down (bugged or disabled) in catchup or streaming state.

As a workaround of my problem, I've splitted the process of replication whole big database into table by table replication, so each table is initially copied independently. It takes less time => less errors, less catchup for each part (every catchup hardly influences master server IO performance):
1. Create replication set without tables
2. Create subscription with this set
3. Add table to replication set with "init" flag.
4. Wait while it finishes replication (I've used `SELECT pid, application_name, client_addr, state, pg_size_pretty(pg_xlog_location_diff(pg_current_xlog_location(), replay_location)) FROM pg_stat_replication;` to monitor process status)
5. Add next table.

**Comment by parihaaraka** [comment]
Thanks, M1ha. I know about this approach, but my cross-referenced tables contain 99% of data. Even if I drop FKs on subscriber, I'll win not much (it's about 2-3 tables). Besides I'd like to know how to interpret the numbers from the log to find out exact table to be resynchronized.
