### ISSUE TITLE
Cannot set destination path of replicated table

### ISSUE THREAD

**Issue by PerRommetveit** [2ndQuadrant/pglogical#157]
I've set up logical replication.

I've already got two postgres servers where replication has been set up such that the subscriber merges everything in Database1 from both the providers. This is fine because, on the subscriber node there is a database 'Database1' which corresponds to the database names on both providers, and there's no overlapping objects on the providers.

However, as of now I have a new table in one of the providers in a separate database.

DB: Database2
Schema: Schema2
Table: Table2

How can I set the target destination to the following for this table?

DB: Database1
Schema: Schema1
Table: Table1

The table I'm writing to on the subscriber node is only written to by this subscription.

db2>sc2.tbl2  --> db1>sc1.tbl1

Also, as long as I could get the table I try to replicate into Database1, I would be fine.

The extension postgres_fdw is not an option to solve this.

If anyone have a suggestion as to how to set this up with pglogical, I would be grateful.

**Comment by eulerto** [comment]
> Tables on the provider and subscriber must have the same names and be in the same schema. Future revisions may add mapping features.

It is not possible to achieve what you want. Maybe you should consider renaming schema and table in your `Database2`.
