### ISSUE TITLE
Document requirement for normal and replication pg_hba.conf entries

### ISSUE THREAD

**Issue by trourance** [2ndQuadrant/pglogical#16]
Hi,

When I've configured the provider, I have added an entry under the replication section, as described in the doc.
However, I still get the error above and I have to add an extra entry under IPV4 for the particular database I want to replicate.

Why ? It seems in the doc that the replication entry should be enough.

**Comment by PJMODOS** [comment]
The pglogical currently requires both replication connection and normal connection. Normal connection is used mainly for initial data copy.

**Comment by fluancefg** [comment]
Thank you for the explanation. Maybe the documentation should reflect that.
