### ISSUE TITLE
Catchup doesn't catch up

### ISSUE THREAD

**Issue by M1ha-Shvn** [2ndQuadrant/pglogical#162]
Hi. 
Pglogical created tables, finished `startup` state and now has `catchup` state in pg_stat_replication. But when I try getting replay delay it shows always growing size:
```SQL
SELECT application_name, client_addr, state, 
    pg_size_pretty(pg_xlog_location_diff(pg_current_xlog_location(), replay_location)) 
FROM pg_stat_replication;
```
Can you suggest any workaround?

**Comment by M1hacka** [comment]
P. s. I use custom filter on master side.

**Comment by M1hacka** [comment]
I've investigated the issue. The problem was in very complex filter. As a result, the speed of replication was slower than the speed of new wals creation on master side. It would be great, to make multi-threaded replication.

**Comment by eulerto** [comment]
By design, `catchup` phase is done using one connection per subscription. You can always use multiple subscriptions. Another option is to add tables one by one to your replication set, hence, the `catchup` state doesn't take so long and your WAL directory won't retain a lot of files.
