### ISSUE TITLE
table name mapping between provider and subscriber

### ISSUE THREAD

**Issue by cailin-lai** [2ndQuadrant/pglogical#166]
Hi Team,
May I know the schedule to support table name mapping feature?
The case is that the tables name are different from provider and subscriber but has same table structure. As I recall, there was already a future plan for this function, when it will be done?
With this feature, it will bring great benefits for replication to partition table, and data accumulation cases in enterprise solution as well.
Thanks as always,
Allen

**Comment by klando** [comment]
for you information, this should appear in the near future. Stay tuned and look at next pull requests...

**Comment by cailin-lai** [comment]
Thanks! Hoping to see that.

**Comment by ringerc** [comment]
This has been implemented in pglogical3, which is currently available only to 2ndQuadrant support customers.
