### ISSUE TITLE
pglogical 2.2.0 - memory leak ?

### ISSUE THREAD

**Issue by mrechte** [2ndQuadrant/pglogical#169]
Hello,

Following an update on a big table which is part of a replication set to which we have subscribed, we are unable to replay: it ends up with a OOM kill on pglogical bgworker.

The RES memory is increasing at a rate of 1 GB / minute until OOM.

pglogical will restart and replay again until next OOM. An endless loop.

At the same time the table phySical size keeps increasing:
SELECT 'grille.q_hyd_v1' nom_table, pg_table_size('grille.q_hyd_v1'::regclass) taille;

It Seems this problem was not there on 2.1.1

Best regards

**Comment by mrechte** [comment]
Maybe this will help:

This case happened in an update causing conflict on all lines of the table (200,000,000+) generating a huge amount of LOG messages, originating from pglogical_apply_heap.c:522

**Comment by mudarisov566** [comment]
Hello, we have this is problem too.

**Comment by PJMODOS** [comment]
This was fixed by c7bb9f5ec5c16ae715ce2a95ffd325906195fdcf, there is no binary release containing it yet.

**Comment by mrechte** [comment]
Thanks. It seems to have stopped the bleeding.

**Comment by gleu** [comment]
@PJMODOS : do you know when you'll release 2.2.1 with this bugfix? Thanks.

**Comment by eulerto** [comment]
It was fixed in 2.2.1.
