### ISSUE TITLE
Build failure on Postgresql 10.4

### ISSUE THREAD

**Issue by jbscalia** [2ndQuadrant/pglogical#177]
Several problems:

1) the Makefile does not properly handle setup for a PostgreSQL version 10 instance. Line 50 sets variable PGVER and that fails. Appending "| cut -c1-2" to the settings allows both 9.6.x and 10.4 to work properly.

2) replorigin_drop changed to use 2 arguments rather than 1 moving from 9.6 to 10. The file pglogical_functions.c breaks as a result.

3) Another set of function changes for version 10, breaks pglogical_apply_heap.c; the functions which changed are:

ExecARUpdateTriggers
ExecARInsertTriggers
ExecARDeleteTriggers

**Comment by jbscalia** [comment]
I have succeeded in getting pglogical working on Postgresql 10.4. Not exactly certain that it's all correct but it is successfully replicating a 9.6.9 server. As the PostgreSQL function signatures changed as noted above, I need to do some code cleanup before I share this with anyone. Currently. my code now only builds on version 10 and no longer builds cleanly on anything earlier.

**Comment by fvannee** [comment]
Not sure, but are you looking at the master branch or the REL_2_X branch? The REL_2_X branch is actually the most up-to-date one. Master branch seems pretty outdated. It's a bit confusing - I had the same issue a while back when I wanted to look at pglogical.

**Comment by ggraham-412** [comment]
I report that I was able to compile the REL2_x_STABLE branch cleanly against postgresql 10.4 on CentOS7.   I've attached the scripts I used in case it helps.  (FYI these are not production quality scripts - these are more or less like notes I kept during the build process.)

[postgres_env.sh.txt](https://github.com/2ndQuadrant/pglogical/files/2206160/postgres_env.sh.txt)

[postgres_build.sh.txt](https://github.com/2ndQuadrant/pglogical/files/2206161/postgres_build.sh.txt)

[pglogical_build.sh.txt](https://github.com/2ndQuadrant/pglogical/files/2206162/pglogical_build.sh.txt)
