### ISSUE TITLE
pglogical switch over from switchovered physical replication cluster 

### ISSUE THREAD

**Issue by edib** [2ndQuadrant/pglogical#187]
I have a physical replication cluster (master-replica) and another machine that replicate only some tables from master. I want to switch over the master to the replica. In test environment, I have tried to test the case but I could not succeed. What should be the workflow for the cases like this without restart logical replication from the beginning?

**Comment by martinmarques** [comment]
2018-08-28 10:18 GMT-03:00 ibrahim edib kokdemir <notifications@github.com>:

> I have a physical replication cluster (master-replica) and another machine
> that replicate only some tables from master. I want to switch over the
> master to the replica. In test environment, I have tried to test the case
> but I could not succeed. What should be the workflow for the cases like
> this without restart logical replication from the beginning?
>

That's not possible, as the standby doesn't have any information about the
replication slots or replication origins from the primary.

You didn't mention which version of postgres you are using, yet that is
actually irrelevant as none of the supported versions, have the ability to
failover the primarys slots and replication origin information to a
physical standby. There were a few attempts to get a failover patch
committed to postgres with no avail.

The only real option is to use 2ndQPostgres which has failover slots, but
we only provide it for support customers. If you are interested, send a
mail to info@2ndquadrant.com asing for a quote for 2ndQPostgres.

Regards,

-- 

Martín Marqués                http://www.2ndQuadrant.com/
PostgreSQL Development, 24x7 Support, Training & Services
