### ISSUE TITLE
Debian builds broken with recent 10.5 ABI changes

### ISSUE THREAD

**Issue by richard-huxton-dev** [2ndQuadrant/pglogical#190]
I was testing out the Debian packages with a PostgreSQL 10.5 installation and kept getting errors about "no data" in messages. I suspect this is due to the recent ABI breakage I saw mentioned on the mailing lists. Building from source against 10.5 or rebuilding the Debian packages seemed to solve this problem.

For anyone else not familiar with building from source, the simplest solution may well be (in Debian or Ubuntu)

    $ sudo apt-get build-dep postgresql-10-pglogical
    $ mkdir ~/source_deb; cd ~/source_deb
    $ apt-get source --compile postgresql-10-pglogical
    $ sudo dpkg -I <package you just built>.deb

**Comment by andyshingler** [comment]
Just a little correction, the last command should have `-i`, not `-I` parameter to install the package.

**Comment by mbanck** [comment]
I guess this has been solved in the meantime?

**Comment by eulerto** [comment]
It was fixed.
