### ISSUE TITLE
Error face in postgresql database

### ISSUE THREAD

**Issue by unotech001** [2ndQuadrant/pglogical#191]
Dear Team,

We have postgresql database version 9.5 in production set up.We occasionally face below error.So we need to restart application process to fix it.(droped connection from application end and start again) but its not ideal solution.

Error :- 
**org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.      
Caused by: java.net.SocketException: Connection reset by peer: socket write error**

We need help to fix this error.

++  loop c. ringerc sir

**Comment by unotech001** [comment]
Dear Team,

Please respond on above error as soon as possible because we are getting this error on production server. How can we fix this error.

Thanks.

**Comment by eulerto** [comment]
This doesn't seem to be related to `pglogical`.
