### ISSUE TITLE
Segmentation fault for tables with indexes using functions 

### ISSUE THREAD

**Issue by pslavov** [2ndQuadrant/pglogical#192]
Hi,
Several months ago I reported this bug for the native logical decoding in PostgreSQL. For some reason this [bug is still not fixed](https://www.postgresql.org/message-id/152110589574.1223.17983600132321618383%40wrigleys.postgresql.org).
My investigation shows that this bug is also present in the current stable version in pglogical extension. The problem is when you are using specifically `immutable` functions in the column definition or in the predicates of the index if it is partial index.

I felt it is good to have this bug reported here also, because it seems that the both codes are connected.

**Comment by pslavov** [comment]
Here is a simple schema that replicates this problem:
`-- 
-- On master
--
 
CREATE FUNCTION public.months_ago(integer) RETURNS timestamp without time zone
  LANGUAGE sql IMMUTABLE
  AS $_$
    SELECT (NOW() - '1 month'::interval * $1)::timestamp;
$_$;

CREATE TABLE public.replicated_table (
    id serial PRIMARY KEY NOT NULL,
    a text,
    b bigint,
    created_at timestamp without time zone DEFAULT now()
);

CREATE INDEX ON public.replicated_table (a) WHERE (created_at > public.months_ago(4));;

--
-- On replica
--

CREATE TABLE public.replicated_table (
    id integer NOT NULL,
    a text,
    b bigint,
    created_at timestamp without time zone DEFAULT now()
);`

**Comment by Splarv** [comment]
Is it closed?

**Comment by eulerto** [comment]
Since pglogical uses `RelationGetIndexAttrBitmap` function from Postgres, this isssue is fixed (postgres/postgres@dfa774ff9ac9de33d8cb98b91906ada55a2ab1df). PostgreSQL 11.2, 10.7, 9.6.12, 9.5.16, and 9.4.21 contain the fix.
