### ISSUE TITLE
pglogical.synchronous_commit now makes regressions tests much slower

### ISSUE THREAD

**Issue by mbanck** [2ndQuadrant/pglogical#194]
the `t/basic` and `t/extended` tests run a long time - they seem to wait for upcoming WAL traffic which isn't happening.

If I issue continuous `CHECKPOINT`s every second in a second connection, the regression tests take 3:30 minutes on my notebook; if I just let them run as-is, they take 25 minutes, which looks excessive.

If I comment out `pglogical.synchronous_commit = true` in `regress-postgresql.conf`, the tests are fast again so this work-around in `a46029c3` no longer seems to be a win. The regression tests take 4:30 then (without running concurrent `CHECKPOINT`s, of course).

**Comment by ChristophBerg** [comment]
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905927 (though the test failures mentioned at the beginning have been fixed in the meantime)

**Comment by eulerto** [comment]
Per Debian bug report, it was fixed.
