### ISSUE TITLE
Subscription synchronization stuck

### ISSUE THREAD

**Issue by CynnySpace** [2ndQuadrant/pglogical#197]
We create a subscription (with `synchronize_data` to false) and then we synchronize it with `alter_subscription_synchronize`. Synchronization starts correctly, and it begins to copy data for all tables in replication set linked by subscription. But sometimes, synchronization stuck and doesn't go forward.
Our data are: `postgresql 10.5`, `pglogical 2.2.1`, subscription is called `r4`, subscriber has ip `2a01:84a0:9001:a001::2:6` and database `meta_0e38e38e`, provider ip `2a01:84a0:9001:a001::3:5` and database `meta_d5555552`
Now we describe situation at the beginning of table (`b2b_object_folder_d5555552`) synchronization that doesn't reach the end:
- on provider we have following slots

  slot_name                                      |      plugin      | slot_type | datoid |   database    | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn
  ------------------------------------------------|------------------|-----------|--------|---------------|-----------|--------|------------|------|--------------|-------------|---------------------
  pgl_meta_0e38e38e___03_05_d5555552_r4_8ec31783 | pglogical_output | logical   |  16385 | meta_d5555552 | f         | t      |      12705 |      |         3613 | 0/1D89740   | 0/1D89778
  pgl_meta_0e38e38e___03_05_d5555552_r4          | pglogical_output | logical   |  16385 | meta_d5555552 | f         | t      |      12559 |      |         3613 | 0/1D87F38   | 0/1D87F70

- on provider we have following replications

  application_name |       client_addr        |         backend_start         | sent_lsn  | write_lsn | flush_lsn | replay_lsn |   state
  ------------------|--------------------------|-------------------------------|-----------|-----------|-----------|------------|-----------
  r4_catchup       | 2a01:84a0:9001:a001::2:6 | 2018-11-14 10:26:21.069132|00 | 0/1D89778 | 0/1D89778 | 0/1D89778 | 0/1D89778  | streaming
  r4               | 2a01:84a0:9001:a001::2:6 | 2018-11-14 10:25:18.362088|00 | 0/1D89778 | 0/1D87F70 | 0/1D87F70 | 0/1D87F70  | streaming

- on provider we have following processes

  `12705 10:26 postgres: wal sender process postgres 2a01:84a0:9001:a001::2:6(53291) idle`
  `12559 10:25 postgres: wal sender process postgres 2a01:84a0:9001:a001::2:6(53189) idle`

- on subscriber we have following subscriptions

  subscription_name |   status    |  provider_node   |                         provider_dsn                         |               slot_name               | replication_sets | forward_origins
  -------------------|-------------|------------------|--------------------------------------------------------------|---------------------------------------|------------------|-----------------
  r4                | replicating | M_03_05_d5555552 | host=2a01:84a0:9001:a001::3:5 port=5432 dbname=meta_d5555552 | pgl_meta_0e38e38e___03_05_d5555552_r4 | {replica_4}      |

- on subscriber we have following processes

  `5854 10:25 postgres: bgworker: pglogical apply 16385:1246847312`
  `5905 10:26 postgres: bgworker: pglogical sync  b2b_object_folder_d5555552 16385:1246847312`

But after some time, as we can see from log [5905.log](https://github.com/2ndQuadrant/pglogical/files/2581143/5905.log) (`5905` is subscriber process) and [12705.log](https://github.com/2ndQuadrant/pglogical/files/2581145/12705.log) (`12705` is provider process), synchronization stuck and doesn't go forward any more.
Here new situation:

- on provider we have following slots

 slot_name                    | datoid |   database    | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn
  ------------------------------------------------|--------|---------------|--------|------------|------|--------------|-------------|---------------------
   pgl_meta_0e38e38e___03_05_d5555552_r4_8ec31783 |  16385 | meta_d5555552 | t      |      12705 |      |         3613 | 0/1D89740   | 0/1D89778
   pgl_meta_0e38e38e___03_05_d5555552_r4          |  16385 | meta_d5555552 | f      |            |      |         3613 | 0/1D87F38   | 0/1D87F70

- on provider we have following processes

  `12705 10:26 postgres: wal sender process postgres 2a01:84a0:9001:a001::2:6(53291) idle`

- on subscriber we have following table synchronization status

  sync_kind | sync_subid | sync_nspname |          sync_relname          | sync_status | sync_statuslsn
  -----------|------------|--------------|--------------------------------|-------------|----------------
  i         | 1246847312 |              |                                | r           | 0/0
  d         | 1246847312 | public       | b2b_tenant_list_d5555552       | i           | 0/0
  d         | 1246847312 | public       | b2b_object_folder_d5555552     | u           | 0/1D87F38

- on subscriber we have following processes

  `5854 10:25 postgres: bgworker: pglogical apply 16385:1246847312`
  `5905 10:26 postgres: bgworker: pglogical sync  b2b_object_folder_d5555552 16385:1246847312`

As you can see from log ( [12559.log](https://github.com/2ndQuadrant/pglogical/files/2581144/12559.log) ), provider process `12559` ends for timeout.
Restarting postgresql server on subscriber fix the situation, synchronization restart and finish to synchronize all remaining tables.

Other attachments:
[5854.log](https://github.com/2ndQuadrant/pglogical/files/2581142/5854.log) (`5854` is subscription main process on subscriber)

**Comment by CynnySpace** [comment]
Thanks for you support, i'll try to replicate this bug and inspect `pg_locks`  to confirm your hypothesis

**Comment by CynnySpace** [comment]
Hi Craig,
sorry for all this time without no updates from us. I have no further investigate on this issue because we solved the problem making so that subscriptions in synchronization don't have no tables in common. I think this was the reason of the deadlock, some crossed locks in tables shared by more than one subscription.

**Comment by SuperChengWu** [comment]
I also encountered the same problem. I feel it is a bug. Is there any way to avoid it? @ringerc

**Comment by SuperChengWu** [comment]
> I also encountered the same problem. I feel it is a bug. Is there any way to avoid it? @ringerc

When the provider's database updates the data, it seems that the subscription will not be stuck for a long time.

**Comment by Mysticwaver** [comment]
It is common situation in our solutions which useing LR with pglogical. Afert sub stuck, we have to kill the PID of the sync table and disable/enable subscription again. May someone help what to do to avoid this situation?
