### ISSUE TITLE
How to check logfiles of pglogical? Should enable logging_collector?

### ISSUE THREAD

**Issue by jingjingan** [2ndQuadrant/pglogical#212]
How to configure to allow pglogical logfile only? Currently I don't need other logfiles.

**Comment by petere** [comment]
pglogical uses the PostgreSQL servers logging subsystem. There is no specific option to see only pglogical messages, but you could perhaps filter them in your logging system, like syslog. However, operating pglogical also requires logs from core PostgreSQL, so just throwing away all the logs except pglogical doesn't seem sensible.
