### ISSUE TITLE
Where to ask questions?

### ISSUE THREAD

**Issue by guettli** [2ndQuadrant/pglogical#220]
Thank you for this great software!

Maybe I am blind, but I could not find a guide from you where users should ask questions about pglogical.

There is a tag on these sites: 

* https://dba.stackexchange.com/questions/tagged/pg-logical
* https://stackoverflow.com/questions/tagged/pglogical

But it seems that few experts read the questions there.

Please tell us (maybe in the README if this github repo) where users should ask questions.

**Comment by eulerto** [comment]
Feel free to open an issue if you have any questions. It is hard to keep track of several resources. Let's keep the communication here.
