### ISSUE TITLE
PostgreSQL 12 support

### ISSUE THREAD

**Issue by gabriel-tincu** [2ndQuadrant/pglogical#223]
Hello,
Is there any plan for supporting the newly released postgresql version
Thanks

**Comment by df7cb** [comment]
Debian wants to transition to PostgreSQL 12 and needs a new version as well.

**Comment by dbigunyak** [comment]
Any info? does postgresql12 will have any chances to have pg_logical extension?

**Comment by petere** [comment]
PostgreSQL 12 support is being worked on.

**Comment by dockpg** [comment]
Any Updates?

**Comment by ringerc** [comment]
PostgreSQL 12 support for pglogical2 has passed basic regression tests but there are some issues remaining. Keep watching here.

**Comment by Andrei-Pozolotin** [comment]
> keep watching here

can we watch that on public brunch? where?

**Comment by dockpg** [comment]
Checking back most every day.  Looking forward to helping out testing on pg12.   Any thoughts on when we can build from source and start testing?

**Comment by ailark** [comment]
Waiting for updates.

**Comment by cpaelzer** [comment]
Hi,
ping - still waiting for  updates.

Debian (as @df7cb mentioned) but even more so Ubuntu which has an earlier Feature-Freeze for the coming LTS 20.04 is depending on that. We intend to go with postgresql-12 only and therefore the only option left otherwise would be to remove pglogical2 from the archive (including its reverse dependencies).

Please let me know if there is anything that Debian/Ubuntu could use to get pglogical (and dependencies) updated to work with PostgreSQL-12

**Comment by cpaelzer** [comment]
FYI for now it is removed from Debian&Ubuntu.

The Ubuntu 20.04 Feature Freeze is on 27th of February. If there is any chance to make a version working with Postgresql-12 before that it would be great to slip in before that.

**Comment by dockpg** [comment]
This critical functionality is too important too die for very long.   I
have created a fork that I am personally working on at
https://github.com/bigsql/spock.  My intent is too support open source
PostgreSQL 9.6, 10, 11, & 12 with the documented functionality that has
been in this extension for the last five years.   My hope is that the code
we develop will be accepted by this community.   If not, then long live
Spock, for he was a logical man.  :-)

**Comment by Andrei-Pozolotin** [comment]
@dockpg @luss @lussier-io
Denis: there are no "issues" in your fork, do you mean to trace issues here instead?

**Comment by pgsql-io** [comment]
I'm hoping the bigsql fork ends u being a throw away as this parent/primary
project supports pg12 in near future.  It's a chance for me to dive deep
and learn this high quality code base.  Cheers.

**Comment by Andrei-Pozolotin** [comment]
@dockpg @luss @lussier-io Denis:
> I'm hoping the bigsql fork ends u being a throw away

please post here when you have `compat12` available for review

**Comment by luss** [comment]
I have opened up 2.3.0dev work in https://github.com/bigsql/spock and am starting work on compat12.   Any expert assistance in the form of advice and/or pull requests is welcome.   This is intended to be an open source collaborative effort.   I am working on it in my personal spare time as a Postgres Community member.   I have also added Issue tracking and Wiki to that fork.

--Luss

**Comment by PJMODOS** [comment]
2.3.0 release has addressed this.

**Comment by Andrei-Pozolotin** [comment]
@PJMODOS Petr: thank you
