### ISSUE TITLE
Build error on function ReadDirExtended

### ISSUE THREAD

**Issue by rzearreta** [2ndQuadrant/pglogical#227]
Hello everyone,

I'm trying to compile version 2.2.2 on a SuSE 12 x64 machine, for PostgreSQL 10.0 (gcc 4.8.5).

The make command fails with error:

> sed 's/__PGLOGICAL_VERSION__/2.2.2/;s/__REQUIRES__//' /users/login/e461588/pglogical-REL2_2_2/pglogical.control.in > /users/login/e461588/pglogical-REL2_2_2/pglogical.control
> 
> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fPIC -fPIC -I/opt/psl100/include -I/users/login/e461588/pglogical-REL2_2_2/compat10 -Werror=implicit-function-declaration -I. -I./ -I/opt/psl100/include/postgresql/server -I/opt/psl100/include/postgresql/internal  -D_GNU_SOURCE   -c -o pglogical_output_plugin.o pglogical_output_plugin.c
> pglogical_output_plugin.c: In function 'pglReorderBufferCleanSerializedTXNs':
> pglogical_output_plugin.c:1004:2: error: implicit declaration of function 'ReadDirExtended' [-Werror=implicit-function-declaration]
>   while ((spill_de = ReadDirExtended(spill_dir, path, INFO)) != NULL)
>   ^
> pglogical_output_plugin.c:1004:19: warning: assignment makes pointer from integer without a cast [enabled by default]
>   while ((spill_de = ReadDirExtended(spill_dir, path, INFO)) != NULL)
>                    ^
> cc1: some warnings being treated as errors
> <builtin>: recipe for target 'pglogical_output_plugin.o' failed
> make: *** [pglogical_output_plugin.o] Error 1

In case of disabling the GCC flag "-Werror=implicit-function-declaration", the software is built, but when trying to load it:

> waiting for server to start....2019-10-29 22:04:01 CET [52937-1] LOG:  pgaudit extension initialized
> 2019-10-29 22:04:01 CET [52937-2] FATAL:  could not load library "/opt/psl100/lib/postgresql/pglogical.so": /opt/psl100/lib/postgresql/pglogical.so: undefined symbol: ReadDirExtended
> 2019-10-29 22:04:01 CET [52937-3] LOG:  database system is shut down

Apparently could be similar to what happens with version 9.6.6 #224, but unfortunately I cannot easily pick a different version of PostgreSQL to try.

Any idea? Thanks.

**Comment by petere** [comment]
You need at least PostgreSQL 10.2.
