### ISSUE TITLE
Replicating TimescaleDB  Hypertables

### ISSUE THREAD

**Issue by derkan** [2ndQuadrant/pglogical#228]
I wonder if replication of [TimescaleDB Hypertables](https://docs.timescale.com/latest/using-timescaledb/hypertables) is in roadmap? I think it will be a nice to have this support. 

@fasmit [has already tried](https://github.com/timescale/timescaledb/issues/483#issuecomment-381395287):

> I managed to patch 2ndquadrant's pg_logical to be able to logically replicate timescaledb tables. I imagine the same wouldwork for BDR. The problem is that logical WAL will receive changes on hyper chunk partitions instead of the parent hypertable, so whenever pglogical logically decodes the WAL I scan if it is a table in the _timescale_internal schema, and if so I use the pgcatalog to map the name to the parent table. Then on the receiver it will simply be inserted into the parent and properly assigned a chunk automatically. These problems are all similar to why pg10 partitioning and logical replication don't work either: it's a mapping problem from inheritance/partition child to parent and/or relation type.
> 
> Oh, and you'd have to make some changes to the COPY bulk read sync as the parent tables are empty and a COPY table would not return any data, so you want to rewrite it as COPY (SELECT ...) TO in order for the individual chunks to be read.

**Comment by petere** [comment]
This is currently not on the roadmap.
