### ISSUE TITLE
cascading replication

### ISSUE THREAD

**Issue by 1803** [2ndQuadrant/pglogical#23]
When setting up cascading replication p1->p2->p3 data does not get replicated to the p3-node. There is an error message in logs:

```
>LOG:  starting apply for subscription sub_p2_to_p3_insert_only
>ERROR:  cache lookup failed for replication origin '[p1-node-name]'
```

AFAIK this was previously reported on pg-general mailing list. Is there anything I can do to work this around?

pglogical 1.1.2
PostgreSQL 9.5.2 x86_64 on CentOS 7

**Comment by PJMODOS** [comment]
Cascading wasn't much of a priority so far. Currently you have to create the origin manually using [pg_replication_origin_create()](https://www.postgresql.org/docs/9.5/static/functions-admin.html#PG-REPLICATION-ORIGIN-CREATE). I plan to make this work seamlessly in the future release.

**Comment by 1803** [comment]
@PJMODOS I tried that after reading logical replication docs on postgresql.org. It didn't seem to help at all.

Here's query from current state of p3 node:
```
postgres=# select * from pg_replication_origin;
 roident |                    roname
---------+-----------------------------------------------
.....
       3 | pgl_postgres_node_p2_9face77_sub_p2_t6fd19a3
       4 | pgl_postgres_node_p1_provider_sub_p1_tae76d83
(4 rows)
```
pgl_postgres_node_p1_provider_sub_p1_tae76d83 is p1 origin.

Is there anything else I need to do apart from adding an origin?

**Comment by MichaelDBA** [comment]
So is this implemented now, cascading replication using pglogical?
