### ISSUE TITLE
yum install 404s on AWS ec2 instance

### ISSUE THREAD

**Issue by bp32795** [2ndQuadrant/pglogical#236]
Is there something special I have to do to get pglogical on an AWS instance? When I do `yum install postgresql96-server postgresql96-contrib` I get `failure: repodata/repomd.xml from 2ndquadrant-dl-default-release-pg9.6: [Errno 256] No more mirrors to try.
https://dl.2ndquadrant.com/default/release/rpm/packages/amzn/2/x86_64/9.6/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`

Here is my linux version `NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
`

**Comment by petere** [comment]
Amazon Linux is not supported by 2ndQuadrant's package repositories yet. You need to use a different distribution or build packages yourself.
