### ISSUE TITLE
Syntax error when calling alter_subscription_synchronize between 2.3.0 and 2.2.2 

### ISSUE THREAD

**Issue by pnhgithub** [2ndQuadrant/pglogical#240]
Starting with pglogical v2.2.2 on both publisher and subscriber nodes, we updated the subscriber node to pglogical v2.3.0.

After upgrade, calling alter_subscription_synchronize on the subscriber node resulted in the following error:

     ERROR:  syntax error at or near "."
     LINE 1: ...i.att_list,       i.has_row_filter, i.nspname as i.nsptarget...
                                                                  ^
Checking the source for pglogical v2.3.0 shows this string appears only in pglogical_rpc.c at line 77.

The comment for this query indicates that it is used when publisher is running 2..0+.

Upgrading our publisher node to pglogical v2.3.0 resolved the issue.

**Comment by ral00** [comment]
Same error (syntax error) occurs on a create_subscription() where provider runs pglogical 2.2.1 and subscriber runs 2.3.0.

**Comment by github-nr-bambee** [comment]
I have same error
source postgres 9.4. pglogical 2.2.2
target postgres 11.6.    pglogical 2.3.0

create_subscription error in log
source
 ERROR:  syntax error at or near "." at character 89
STATEMENT:  SELECT i.relid, i.nspname, i.relname, i.att_list,       i.has_row_filter, i.nspname as i.nsptarget, i.relname as i.reltarget  FROM (SELECT DISTINCT relid FROM pglogical.tables WHERE set_name = ANY(ARRAY['default','default_insert_only','ddl_sql'])) t,       LATERAL pglogical.show_repset_table_info(t.relid, ARRAY['default','default_insert_only','ddl_sql']) i

target
 manager worker [4025] at slot 1 generation 24 detaching cleanly
 could not get table list: ERROR:  syntax error at or near "."
	LINE 1: ...i.att_list,       i.has_row_filter, i.nspname as i.nsptarget...
	                                                             ^
	
  apply worker [4023] at slot 2 generation 8 exiting with error
  background worker "pglogical apply 16384:2875150205" (PID 4023) exited with exit code 1
  starting apply for subscription subscription
ERROR:  subscriber subscription initialization failed during nonrecoverable step (d), please try the setup again

**Comment by sujithpaily** [comment]
I have same error
source postgres 9.4. pglogical 2.2.2
target postgres 11.6. pglogical 2.3.0

create_subscription error in log
source
ERROR: syntax error at or near "." at character 89
STATEMENT: SELECT i.relid, i.nspname, i.relname, i.att_list, i.has_row_filter, i.nspname as i.nsptarget, i.relname as i.reltarget FROM (SELECT DISTINCT relid FROM pglogical.tables WHERE set_name = ANY(ARRAY['default','default_insert_only','ddl_sql'])) t, LATERAL pglogical.show_repset_table_info(t.relid, ARRAY['default','default_insert_only','ddl_sql']) i

target
manager worker [4025] at slot 1 generation 24 detaching cleanly
could not get table list: ERROR: syntax error at or near "."
LINE 1: ...i.att_list, i.has_row_filter, i.nspname as i.nsptarget...
^

apply worker [4023] at slot 2 generation 8 exiting with error
background worker "pglogical apply 16384:2875150205" (PID 4023) exited with exit code 1
starting apply for subscription subscription
ERROR: subscriber subscription initialization failed during nonrecoverable step (d), please try the setup again

**Comment by jarrettgreen** [comment]
Same error.
**Provider:** postgres 9.4, pg_logical 2.2.2
**Subscriber:** postgres 12, pg_logical 2.3.0

Edit: I also see no 2.3.0 version for 9.4 to upgrade to like @pnhgithub did.
