### ISSUE TITLE
Logical replication gets syntax issue trying to add subscription

### ISSUE THREAD

**Issue by bbellrose1** [2ndQuadrant/pglogical#248]
Create new publication and subscription. I want to attempt an upgrade using logical replication from 9.4 to 12.1. PGLogical installed without issues, but when adding the subscription I get the following error in the postgres log.

 [postgres] [pglogical manager 1460528] [[unknown]] LOG:  manager worker [35674] at slot 1 generation 6 detaching cleanly
[pglogical apply 30692:2355714646] [[unknown]] ERROR:  could not get table list: ERROR:  syntax error at or near "."
 [10-2] #011LINE 1: ...i.att_list,       i.has_row_filter, i.nspname as i.nsptarget...
 #011                                                             ^

  oid  |  extname  | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition
-------+-----------+----------+--------------+----------------+------------+-----------+--------------
 30972 | pglogical |       10 |        30921 | f              | 2.3.0      |           |

**Comment by bbellrose1** [comment]
Seems like table definition on the source might not be what the target expects:

# \d pglogical.tables
   View "pglogical.tables"
  Column  | Type | Modifiers
----------+------+-----------
 relid    | oid  |
 nspname  | name |
 relname  | name |
 set_name | name |

**Comment by petere** [comment]
This has been fixed in version 2.3.1.
