### ISSUE TITLE
Handle missing toasted values

### ISSUE THREAD

**Issue by promag** [2ndQuadrant/pglogical#25]
After starting replication of the logical slot:

```
START_REPLICATION SLOT json LOGICAL 0/0 (
  max_proto_version '1',
  min_proto_version '1',
  proto_format 'json',
  startup_params_format '1'
)`);
```

the following shows in postgres logs:

```
ERROR:  XX000: missing chunk number 0 for toast value 17032 in pg_toast_16408
CONTEXT:  slot "json", output plugin "pglogical_output", in the change callback, associated LSN 0/1A62538
LOCATION:  toast_fetch_datum, tuptoaster.c:1945
```

I believe the issue is in [pglogical_proto_json.c#L104](https://github.com/2ndQuadrant/pglogical/blob/pglogical_output/pglogical_proto_json.c#L104) where `heap_copy_tuple_as_datum` unsafely detoasts the values.

**Comment by ringerc** [comment]
Details/background please.

Exact pglogical version?

How did you get to this point? commands run, steps taken, etc.

What steps did you use to set up pglogical?
​

**Comment by promag** [comment]
Postgres 9.5.3
pglogical_output: 71c6f27

The plugin was installed with

```
curl -L "https://github.com/2ndQuadrant/pglogical/archive/pglogical_output.tar.gz" | tar zx
make -C pglogical-pglogical_output USE_PGXS=1 all install
```

Our application test suit performs lots of database integration tests and in between the tables rows are deleted. Then when running pg_recvlogical to stream the slot that error shows up.

Please see https://github.com/posix4e/jsoncdc/issues/63#issuecomment-229970288 for more details.

BTW test_decoding output plugin implementation avoids _detoasting_ the values as you can see in [test_decoding.c:378](https://github.com/postgres/postgres/blob/master/contrib/test_decoding/test_decoding.c#L378)

**Comment by ringerc** [comment]
Right, that makes sense.

We're actually going to be removing the json support entirely now that pglogical_output is being merged into pglogical and not going into the core project's contrib. There's a new in-core logical replication effort that arose out of that instead. So unless this affects the binary format I don't intend to fix it I'm afraid.

I suggest looking into one of the other json-output plugins at this stage.
