### ISSUE TITLE
published docs out of sync with the readme

### ISSUE THREAD

**Issue by jjb** [2ndQuadrant/pglogical#254]
Seems like the published docs https://www.2ndquadrant.com/en/resources/pglogical/pglogical-docs/

are not up to date with the info in the readme https://github.com/2ndQuadrant/pglogical

This wasted a lot of time for me because of a couple pieces of missing info. Might be good to merge them, or take one down.

Thanks for a great project!

**Comment by eulerto** [comment]
Your assumption is correct. My advice is to always rely on [README](https://github.com/2ndQuadrant/pglogical#readme).
