### ISSUE TITLE
install error： pglogical_dependency.c:235: error:

### ISSUE THREAD

**Issue by mawenbin666** [2ndQuadrant/pglogical#259]
version:pglogical-REL2_3_0
`pglogical_dependency.c:235: error: static declaration of ‘AcquireDeletionLock’ follows non-static declaration
/usr/local/postgresql-12.3/include/server/catalog/dependency.h:145: note: previous declaration of ‘AcquireDeletionLock’ was here
pglogical_dependency.c:236: error: static declaration of ‘ReleaseDeletionLock’ follows non-static declaration
/usr/local/postgresql-12.3/include/server/catalog/dependency.h:147: note: previous declaration of ‘ReleaseDeletionLock’ was here
gmake: *** [pglogical_dependency.o] Error 1
`

**Comment by petere** [comment]
Yes, we're preparing a new release to fix that.

**Comment by petere** [comment]
This has been fixed in release 2.3.2.
