### ISSUE TITLE
FATAL:  unsupported frontend protocol 1234.5680

### ISSUE THREAD

**Issue by mawenbin666** [2ndQuadrant/pglogical#263]
old version:9.4.7
new version:12.3
pg_hba.conf:
`host    all            all          0.0.0.0/0         md5`
在新的服务器执行：
```
SELECT pglogical.create_subscription(
subscription_name := 'sub001',
provider_dsn := 'host=192.168.234.1 port=5432 dbname=testdb1 user=repuser password=repuser'
);
```

```
< 2020-05-28 11:07:55.870 CST >FATAL:  unsupported frontend protocol 1234.5680: server supports1.0 to 3.0
< 2020-05-28 11:07:55.875 CST >FATAL:  unsupported frontend protocol 1234.5680: server supports1.0 to 3.0
< 2020-05-28 11:07:55.876 CST >FATAL:  no pg_hba.conf entry for replication connection from host "192.168.234.9", user "repuser", SSL off
```
Is there any way？

**Comment by martinmarques** [comment]
You are missing a line in hba.conf for the replication connection. That line matches all databases but not for replication connections.

You'll have to add also:

```
host replication all 0.0.0.0/0 md5
```

P.S.: this is OK for testing, but you should tighten your access for valuable data

**Comment by martinmarques** [comment]
Also, why are you using 9.4.7? You should upgrade to 9.4.26 and use the latest pglogical 2.3.1 packages. That version requires pglogical 2.1.x as after 9.4.18 there was an ABI change in postgres that required a change in pglogical

**Comment by mawenbin666** [comment]
> 您在hba.conf中缺少用于复制连接的一行。该行匹配所有数据库，但不匹配复制连接。
> 
> 您还必须添加：
> 
> ```
> host replication all 0.0.0.0/0 md5
> ```
> 
> PS：可以进行测试，但是您应该加强对有价值数据的访问

thinks ,fix up.

**Comment by mawenbin666** [comment]
> 您在hba.conf中缺少用于复制连接的一行。该行匹配所有数据库，但不匹配复制连接。
> 
> 您还必须添加：
> 
> ```
> host replication all 0.0.0.0/0 md5
> ```
> 
> PS：可以进行测试，但是您应该加强对有价值数据的访问

thanks ,fix up

**Comment by mawenbin666** [comment]
> 另外，为什么要使用9.4.7？您应该升级到9.4.26并使用最新的pgologic 2.3.1软件包。该版本需要pgologic 2.1.x，因为在9.4.18之后，postgres中的ABI发生了变化，需要pgologic进行了变化

因为是生产环境，不能随便升级，

> 您在hba.conf中缺少用于复制连接的一行。该行匹配所有数据库，但不匹配复制连接。
> 
> 您还必须添加：
> 
> ```
> host replication all 0.0.0.0/0 md5
> ```
> 
> PS：可以进行测试，但是您应该加强对有价值数据的访问

![image](https://user-images.githubusercontent.com/22042460/83213501-d6d90500-a194-11ea-8557-ff1b3ff83e10.png)
`testdb1@[local]:5432=#SELECT pglogical.create_subscription(
testdb1(# subscription_name := 'sub001',
testdb1(# provider_dsn := 'host=192.168.234.1 port=5432 dbname=testdb1 user=repuser password=repuser'
testdb1(# );
ERROR:  could not connect to the postgresql server: could not connect to server: Connection refused
	Is the server running on host "192.168.234.9" and accepting
	TCP/IP connections on port 5432?

DETAIL:  dsn was:  host=192.168.234.9 port=5432 dbname=testdb1
testdb1@[local]:5432=#
`
why？

**Comment by martinmarques** [comment]
Don't know, but you should better use the pglogical mailing list and not github which is for issue reporting

https://groups.google.com/a/2ndquadrant.com/forum/?hl=en-419#!forum/bdr-list
