### ISSUE TITLE
make USE_PGXS=1  after that access/timeline.h: No such file or directory

### ISSUE THREAD

**Issue by lucky529** [2ndQuadrant/pglogical#265]
make USE_PGXS=1  after that access/timeline.h: No such file or directory

**Comment by lucky529** [comment]
Found that the problem is congfig in the makefile, modify the path of congfig to your bin file

**Comment by sunblazevv** [comment]
你好，我现在在安装pglogical的时候遇到这个问题了，麻烦问一下具体要怎么修改，谢谢

**Comment by lucky529** [comment]
您好，我已经不做数据库了，但是我记得timeline.h这个头文件是postgresql的头文件，所以您可以排查一下是不是数据库版本或者环境的问题。这个问题并不是pglogical的问题



---Original---

**Comment by sunblazevv** [comment]
好的，非常感谢



---Original---
