### ISSUE TITLE
pglogical shared_preload_library Loading issue in EDB PPAS - PostgreSQL

### ISSUE THREAD

**Issue by sujiplr** [2ndQuadrant/pglogical#268]
Hi Community Team,

We are trying to move our databases from EDB PPAS to Open Source PostgreSQL. As part of that, we thought of using pglogical for moving the data from EDB PPAS version to Open source version PostgreSQL 12 .

But when I'm trying to load the pglogical extension in shared_preload_library, getting the below error. Can you please help me in Identifying the issue behind this error to setup the pglogical for my requirement. 

ERROR:  could not load library "/app/PostgresPlus/9.5AS/lib/pglogical.so": /app/PostgresPlus/9.5AS/lib/pglogical.so: undefined symbol: LookupFuncName

PostgreSQl version :  EnterpriseDB 9.5.22.28 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-55), 64-bit

pglogical version : 2.2.0

**Comment by martinmarques** [comment]
How did you install pglogical? Did you compile it against the version of PPAS you are using?

I would definitely recommend compiling from source, and as you are at it, maybe use a newer version like 2.3.2, or at least 2.2.2

**Comment by martinmarques** [comment]
In any case, this is something you should bring up with the provider of your Postgres Sever
