### ISSUE TITLE
Replicate into non-empty database

### ISSUE THREAD

**Issue by ephenk** [2ndQuadrant/pglogical#269]
Is it possible to continue the replication after dropping the subscription? I have set up both provider node and subscriber node, data on both are sync perfectly. After that, I drop the subscription on the subscription node, and insert some data into a table in the provider node. And then, I create subscription again on subscription node, the result returns true but the execution failed. Log file here [log.txt](https://github.com/2ndQuadrant/pglogical/files/4918889/log.txt).

I've tried to `set track_commit_timestamp = on` in the postgresql.conf and `set pglogical.conflict_resolution = 'last_update_wins';` but the error keeps persist. Is there any way to continue the subscription without truncating the tables?

**Comment by petere** [comment]
Perhaps when you recreate the subscription, you want to set `synchronize_data := false` so it doesn't copy the table over again. That's where the error comes from, because it's all duplicate data.

**Comment by ephenk** [comment]
I have tried recreate subscription with `synchornize_data := false`, but the data which I inserted on the provider node (when the subscription not running) will not be replicated, only the data inserted after the subscription is running. I also tried to alter the subscription with `pglogical.alter_subscription_synchronize(subscription_name name, truncate bool)` but it doesn't seem to copy the data which I inserted.

**Comment by martinmarques** [comment]
The process you described in the initial message here requires that you resynchronize the whole subscription. When you recreate the subscription, it starts from that LSN when it was created. There is no way to for the logical decoding to go back in time. 
Dropping the subscription means replication is broken, and you have to start from scratch if you want to have full synchronization.
