### ISSUE TITLE
Existing tables don't  have a queue_truncate_trigger trigger

### ISSUE THREAD

**Issue by martinmarques** [2ndQuadrant/pglogical#27]
When creating a new table, pglogical will add an internal trigger for truncate operations queue_truncate_trigger_NNNNN, so if a truncate is executed over the table it will queue the command for the subscribers to consume.

The problem is that pglogical.truncate_trigger_add() isn't invoked on tables that were already present in the database before the node was subscribed, and so they don't have a truncate internal trigger.

IMO, we should add the queue_truncate_trigger to tables added to a replication set instead of doing so for all tables created.

Thoughts?

**Comment by PJMODOS** [comment]
Adding trigger when the table is added to repset sounds like good idea.
