### ISSUE TITLE
APT repository does not have the latest version

### ISSUE THREAD

**Issue by ivanelson** [2ndQuadrant/pglogical#270]
Hi,
I am installing, according to [1] guidance via apt, but do not install the latest (2.3.2) version.

[1] curl https://access.2ndquadrant.com/api/repository/dl/default/release/deb | bash

The installed version was 2.2.2

My env:
 - Ubuntu 14.04

**Comment by martinmarques** [comment]
Ubuntu 14.04 doesn't have support anymore, so we are not building packages for that version of Ubuntu. Please upgrade to a new version (preferable 20.04) where you'll have 2.3.2 available.

Another option would be to download the sources and compile the package yourself
