### ISSUE TITLE
Modify the replica identity will cause the subscription to down.

### ISSUE THREAD

**Issue by leoxjm** [2ndQuadrant/pglogical#272]
pglogical producer subscriber version is 2.3.0.

**SQL**

alter table "public".xxxtable replica identity ......;  (Modify 1 row data of  after execution..)

| Provider(postgres-9.6) | Subscribers.(postgres-12) | subscription_status |
| ---------------------- | ------------------------- | ------------------- |
| full                   | full                      | down                |
| full                   | default                   | replicating         |
| default                | default                   | replicating         |
| default                | full                      | down                |

1 row of data is modified after the copy identity is modified.

The subscriber replica identity cannot be full.
The data table has a primary key.

**postgres log**

```
2020-07-23 18:19:21.813 CST,,"xxx",25581,,5f196410.63ed,2,"",2020-07-23 18:18:56 CST,10/4548,0,ERROR,XX000,"could not find REPLICA IDENTITY index for table xxxtable with oid 17712",,"The REPLICA IDENTITY index is usually the PRIMARY KEY. See the PostgreSQL docs for ALTER TABLE ... REPLICA IDENTITY",,,"apply UPDATE from remote relation public.xxxtable in commit before 2/4C724658, xid 1282794 committed at 2020-07-23 18:19:22.391301+08 (action #2) from node replorigin 1",,,,"pglogical apply 17636:1334639198"
```

**Comment by martinmarques** [comment]
Don't use 2.3.0 as it's know to have many bugs. Upgrade to 2.3.2 which is the latest version available.

**Comment by leoxjm** [comment]
> Don't use 2.3.0 as it's know to have many bugs. Upgrade to 2.3.2 which is the latest version available.

Thank you for your answer.
But i need to use the `nsptarget` parameter. Version 2.3.2 does not support this parameter.

**version 2.3.0**
FUNCTION "pglogical"."replication_set_add_table"("set_name" name, "relation" regclass, "synchronize_data" bool=false, "columns" _text=NULL::text[], "row_filter" text=NULL::text, "nsptarget" name=NULL::name, "reltarget" name=NULL::name)

**version 2.3.2** 
FUNCTION "pglogical"."replication_set_add_table"("set_name" name, "relation" regclass, "synchronize_data" bool=false, "columns" _text=NULL::text[], "row_filter" text=NULL::text)
