### ISSUE TITLE
openssl 1.0.2 required for pglogical

### ISSUE THREAD

**Issue by pratmeht** [2ndQuadrant/pglogical#273]
Hi pglogical community,

We are testing the product. It is interesting. One small note which we observed is that pglogical package installation on RHEL requires openssl >=1.0.2.  We were testing on RHEL 7.2 and our installation was failing. Then we understood that openssl 1.0.2 is available on RHEL from version 7.4 onwards. Thus we tried on VM with openssl 1.0.2 and installation succeeded.

**Comment by martinmarques** [comment]
Versions of RHEL 7.x are forward compatible (it's basically patch upgrading). You should always try to stay at the latest point release, which now would be 7.8

**Comment by pgsql-io** [comment]
+1 for SUDO YUM UPDATE and then a reboot.  :-)
