### ISSUE TITLE
Question: How can I build pglogical for PostgreSQL 9.5.10?

### ISSUE THREAD

**Issue by KenjiOhtsuka** [2ndQuadrant/pglogical#275]
I tried to compile pglogical for PostgreSQL 9.5.10 in AWS EC2.
According to #227 , it requires PostgreSQL 10.2.

I have a question.

How can I build pglogical for PostgreSQL 9.5.10?
Can I use the application compiled with PostgreSQL 10.2 for PostgreSQL 9.5.10?
Or, should I use pglogical of old revision?

**Comment by pgsql-io** [comment]
If you compile it yourself, it works nicely with pg95.  On AWS RDS
PostgreSQL, they offer pgLogical as an option starting from PostgreSQL 10.2
for their DBaaS offering.

**Comment by KenjiOhtsuka** [comment]
@pgsql-io 

Thank you for your comment.

But when I compiled pglogical on EC2, it showed an error.

```
[root@ip-172-30-0-63 pglogical]# cd pglogical-REL2_x_STABLE/
[root@ip-172-30-0-63 pglogical-REL2_x_STABLE]# make
sed 's/__PGLOGICAL_VERSION__/2.3.2/;s/__REQUIRES__//' /usr/local/src/pglogical/pglogical-REL2_x_STABLE/pglogical.control.in > /usr/local/src/pglogical/pglogical-REL2_x_STABLE/pglogical.control
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fPIC -fPIC -I/usr/local/pgsql/include -I/usr/local/src/pglogical/pglogical-REL2_x_STABLE/compat95 -Werror=implicit-function-declaration -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o pglogical_output_plugin.o pglogical_output_plugin.c
pglogical_output_plugin.c: In function 'pglReorderBufferCleanSerializedTXNs':
pglogical_output_plugin.c:1008:2: error: implicit declaration of function 'ReadDirExtended' [-Werror=implicit-function-declaration]
  while ((spill_de = ReadDirExtended(spill_dir, path, INFO)) != NULL)
  ^
pglogical_output_plugin.c:1008:19: warning: assignment makes pointer from integer without a cast [enabled by default]
  while ((spill_de = ReadDirExtended(spill_dir, path, INFO)) != NULL)
                   ^
cc1: some warnings being treated as errors
```

What I wanted to do is create replication from PostgreSQL 9.5.10 on EC2 to RDS (or Aurora).

**Comment by petere** [comment]
pglogical 2.3.2 builds correct against PostgreSQL 9.5.

It's hard to tell what is wrong in your situation. It could be that you have a mix of different PostgreSQL versions installed. Perhaps you have partially built pglogical against one version and then another. Clean everything and try again and before careful to build against one PostgreSQL version only.
