### ISSUE TITLE
Document version compatibility

### ISSUE THREAD

**Issue by ericcmd** [2ndQuadrant/pglogical#277]
Hi, it would be helpful for users to have a statement in the documentation (and here) explaining the intended compatiblity between publishers and subscribers running different versions of pglogical.  Replication between different versions of PostgreSQL is one of the special use cases for this software, and some platforms (like RDS) only supply certain versions of pglogical, so understanding version compatibility would help project planning in some cases, and provide needed confidence that the use case is a supported one.

**Comment by petere** [comment]
In general, all versions of pglogical in recent memory can talk to all other versions. If you find that that doesn't work for you, please report an issue.
