### ISSUE TITLE
 Performance Issues Setting up Logical Replication 

### ISSUE THREAD

**Issue by GEverding** [2ndQuadrant/pglogical#281]
Hi, 

I'm not sure where to ask this question so If there is a better place feel free to direct me there. 

I've been trying to use Pglogical to upgrade from 10 to 12 and have been unsuccessful because of increasing latencies of R/W query (10-20x) on the provider. I've tried creating multiple publications and multiple subscriptions and I always end up killing the subscriptions because of performance degradation. 

- The overall DB is 1.4TB with a couple tables over 80GB. 
- One Read Replica using Streaming Replication is configured
- The total number of tables is less than 20. High update rate a subset of tables and high append rate on others. 
- I've configured the provider and the subscriber per the documentation in the README. 
- There are FK's between a subset of tables. 

I haven't seen other people report serious performance problems with PgLogical so I'm not sure what going on with this migration. How can I start debugging this issue?

**Comment by joshuabaird** [comment]
@GEverding We are having similar issues.  Did you ever determine what was causing the performance issues?
