### ISSUE TITLE
ERROR:  schema "pglogical" does not exist

### ISSUE THREAD

**Issue by ivanelson** [2ndQuadrant/pglogical#290]
I am getting this error in version Postgresql 9.4.

> ERROR:  schema "pglogical" does not exist

To try:

`SELECT pglogical.create_node( node_name := 'dbprovider1', dsn := 'host=127.0.0.1 port=5432 dbname=dam user=usr_rep' );`

The schemas are listed in the database:

> dbacam=# \dn
>          List of schemas
>        Name       |     Owner     
> ------------------+---------------
>  pglogical_origin | postgres
>  public                | postgres
>  sqitch                | usr_aplicacao
 

My extensions:
```
                                          List of installed extensions
       Name       | Version |      Schema      |                           Description                            
------------------+---------+------------------+------------------------------------------------------------------
 adminpack        | 1.0     | pg_catalog       | administrative functions for PostgreSQL
 dblink           | 1.1     | public           | connect to other PostgreSQL databases from within a database
 pglogical_origin | 1.0.0   | pglogical_origin | PostgreSQL Logical Replication Origin Tracking Emulation for 9.4
 pgstattuple      | 1.2     | public           | show tuple-level statistics
 plpgsql          | 1.0     | pg_catalog       | PL/pgSQL procedural language
 postgres_fdw     | 1.0     | dbatez           | foreign-data wrapper for remote PostgreSQL servers
 unaccent         | 1.0     | public           | text search dictionary that removes accents
```

Grateful

**Comment by martinmarques** [comment]
You need to create the pglogical extension first. You only created the pglogical_origin extension.

```
CREATE EXTENSION pglogical;
```

**Comment by daredare2ask** [comment]
Hi. 
I'm having the same issue.

> ERREUR:  could not fetch remote node info: ERROR: schema "pglogical" does not exist

But the pglogical and pglogical_origin schemas both exist on the postgresql 9.4 provider 

> List of schemas
> Name       |  Owner
>------------------+----------
> pglogical        | postgres
> pglogical_origin | postgres
> public           | postgres
> (3 rows)

and the pglogical schema exists on the postgresql 11 subscriber.
>  List of schemas
>  Name    |  Owner
> -----------+----------
>  pglogical | postgres
>  public    | postgres
> (2 rows)

My database actually is in the public schema on the PG9.4 provider. I have already imported a schema only dump of it in the same public schema on the PG11 subscriber.

The pglogical role has been created on both the provider and the subscriber.
` sudo -u postgres psql -c "CREATE ROLE pglogical LOGIN REPLICATION SUPERUSER ENCRYPTED PASSWORD 'secret';" `

The 5432 port is opened in both the provider and the subscriber firewalls.

In the provider pg_hba.conf, I have added what seems to be necessary
> local    replication     pglogical        trust
> host    replication     pglogical        subscriberip/32            md5
> local    mydatabase     pglogical        trust
> host    mydatabase     pglogical        subscriberip/32            md5
> host    mydatabase     postgres        subscriberip/32            md5

And in the subscriber pg_hba.conf, there is the equivalent
> local    replication     pglogical        trust
> host    replication     pglogical        providerip/32            md5
> local    mydatabase     pglogical        trust
> host    mydatabase     pglogical        providerip/32            md5
> host    mydatabase     postgres        providerip/32            md5

On the PG9.4 provider, I have created the node
` postgres=#  SELECT pglogical.create_node(
    node_name := 'provider1',
    dsn := 'host=127.0.0.1 port=5432 dbname=mydatabase'
 );`

and I have set the replication
` postgres=# SELECT pglogical.replication_set_add_all_tables('default', ARRAY['public']);`

On the PG11 subscriber, I have created the node.
` postgres=# SELECT pglogical.create_node(
    node_name := 'subscriber1',
    dsn := 'host=127.0.0.1 port=5432 dbname=mydatabase password=secret'
 );`

And when I try to create the subscription,
` postgres=# SELECT pglogical.create_subscription(
    subscription_name := 'subscription1',
    provider_dsn := 'host=providerhostname port=5432 dbname=mydatabase password=secret'
 ); `

I'm getting the error
> ERREUR:  could not fetch remote node info: ERROR: schema "pglogical" does not exist`


Can you help me please ?
