### ISSUE TITLE
can  not start sync from 2.3.3 -> 2.3.0

### ISSUE THREAD

**Issue by DachengChen** [2ndQuadrant/pglogical#293]
Could be problem von lower version of  pglogical extension from target db. i will try to update the pglogical extension.

source db: 
ubuntu: 16.04
postgresql: 9.5.21 
pglogical 2.3.3

target db:
ubuntu 20.04
postgresql: 12.5
pglogical:2.3.0

get some erro in source:

 ERROR:  syntax error at or near "t" at character 118

 SELECT i.relid, i.nspname, i.relname, i.att_list,       i.has_row_filter, i.nspname as i.nsptarget, i.relname as i.reltarget  FROM (SELECT DISTINCT relid FROM pglogical.tables WHERE set_name = ANY(ARRAY['default','default_insert_only','ddl_sql'])) t,       LATERAL pglogical.show_repset_table_info(t.relid, ARRAY['default','default_insert_only','ddl_sql']) i;

**Comment by petere** [comment]
Don't use 2.3.0. It was buggy and was therefore replaced with newer 2.3.x versions.
