### ISSUE TITLE
conflict_resolution setting is ignored

### ISSUE THREAD

**Issue by Surfer298** [2ndQuadrant/pglogical#30]
Hello, 

I have set the conflict_resolution to 'last_update_wins': 

> set pglogical.conflict_resolution = 'first_update_wins';

But evertime I change something at the provider host, the data is updated at the subscriber and the logfile says: 

> remote UPDATE on relation xxxxx.  Resolution: apply_remote.

What did I do wrong?

Thanks,
Michael

**Comment by PJMODOS** [comment]
That's normal, it only means that the remote tuple was chosen as the one to use during the timestamp based conflict resolution.

**Comment by Surfer298** [comment]
I will try to explain my point: 
I have set the conflict_resolution to first_update_wins
> set pglogical.conflict_resolution = 'first_update_wins';

Then I update a specific row on the subscriber (here is the first update).
Then I update the same row on the provider. Now the row is also updated on the subscriber node, although I have defined that the first update wins.
What is wrong?

Thanks,
Michael
