### ISSUE TITLE
Error :  could not connect to the postgresql server in replication mode: FATAL: No entry in pg_hba.conf 

### ISSUE THREAD

**Issue by mrhassan60** [2ndQuadrant/pglogical#306]
ServerPSQL 9.4 = 192.168.1.91
ServerPSQL 11 = 192.168.1.59

Hello,
I'm trying to replicate using pglogical a database from a Postgresql 9.4 server to a Postgresql 11 server
when i type this command in psql server 11, "SELECT pglogical.create_subscription(subscription_name := 'subscription1',provider_dsn := 'host=192.168.1.91 port=5432 dbname=test password=password');" i have this error 

_ERROR: could not connect to the postgresql server in replication mode: FATAL: No entry in pg_hba.conf for the replication connection from
host "192.168.1.59", user "postgres", SSL enabled
FATAL: No entry in pg_hba.conf for replication connection from
host "192.168.1.59", user "postgres", SSL inactive_

I dont know what is problem and I tried to modify the pg_hba.conf file several times but nothing works

Best regard,
Mrhassan60

**Comment by eulerto** [comment]
That's because you probably doesn't have a HBA entry for the replication connection. Your provider must allow a normal and replication connection from the subscriber.

```
-- pg_hba.conf on the provider
host    DBNAMEHERE    USERNAMEHERE    192.168.1.59/32    md5
host    replication   USERNAMEHERE    192.168.1.59/32    md5
```

PS> subscriber also connect to itself so you must ensure that there is a HBA entry for it.

**Comment by petere** [comment]
More specifically, in PG 9.4 you need the "replication" line, but not in PG 11, so maybe that's where the confusion is coming from.
