### ISSUE TITLE
`replication_set_add_all_tables` function causes `ERROR:  relation "public.pg_class" does not exist`

### ISSUE THREAD

**Issue by holguinj** [2ndQuadrant/pglogical#32]
## Update: reproduction scripts [here](https://github.com/holguinj/pglogical-bug)

I've been seeing some strange behavior around `pglogical.replication_set_add_all_tables`. Under certain circumstances (I haven't been able to narrow it down too much, but I'll add details below), calling the function causes the following to start flooding the logs:

```
2016-08-12 22:07:45 UTC [12175-1] test@test_replication ERROR:  relation "public.pg_class" does not exist                   
2016-08-12 22:07:45 UTC [12175-2] test@test_replication STATEMENT:  COPY "public"."pg_class" TO stdout                      
2016-08-12 22:07:45 UTC [12175-3] test@test_replication LOG:  could not receive data from client: Connection reset by peer  
2016-08-12 22:07:45 UTC [12174-4] test@test_replication LOG:  could not receive data from client: Connection reset by peer  
2016-08-12 22:07:45 UTC [12174-5] test@test_replication LOG:  unexpected EOF on client connection with an open transaction  
```

Note the reference to the nonexistent relation `public.pg_class`, which is presumably based on `postgres.pg_class`.

I don't have a minimal set of steps to reproduce the bug yet, but here's what I've got:
* this doesn't seem to happen the first time we call `pglogical.replication_set_add_all_tables`, which happens before there are any subscribers or tables.
* we're adding all tables in the public schema, as you might guess from the ERROR.
* when this happens, there's already a subscriber node with an active subscription and populated tables.

Again, I apologize that this isn't a comprehensive step-by-step reproduction, but I figured I'd get this filed while I work on that just to see if anything rings a bell.

**Comment by simaofreitas** [comment]
This exact problem happened to me too by calling `pglogical.replication_set_add_all_tables` with `synchronize_data := true` after the subscription was already set.

**Comment by PJMODOS** [comment]
I wasn't able to reproduce this so far.

**Comment by holguinj** [comment]
@PJMODOS Yes, I apologize that I filed this without a comprehensive way to reproduce it. I have one now, which you can see [here](https://github.com/holguinj/pglogical-bug).

**Comment by PJMODOS** [comment]
Ah got it thanks, should be fixed by 2219451

**Comment by holguinj** [comment]
@PJMODOS thanks for the fix! Any idea when it'll be released?

**Comment by carolfly86** [comment]
I'm facing the same issue. Is there a workaround?

**Comment by ringerc** [comment]
pglogical 1.2.0 comes out soon, othrerwise use git head in the mean time.​

**Comment by ringerc** [comment]
pglogical 1.2 has been released.
