### ISSUE TITLE
How do I figure out which rows have been replicated to the subscriber?

### ISSUE THREAD

**Issue by gudmundurp** [2ndQuadrant/pglogical#320]
I want to be able to delete old data on the publisher provided that it has already been replicated to the subscriber.

I know you can query the confirmed_flush_lsn by doing:

`select * from pg_replication_slots;`

But I don't know how this can be related to table rows that are already synced/not synced.

**Comment by petere** [comment]
What are you describing is not really possible in a sensible way.
