### ISSUE TITLE
PostgreSQL 14 support

### ISSUE THREAD

**Issue by devrimgunduz** [2ndQuadrant/pglogical#321]
Hi,

PostgreSQL 14 entered beta, and we are working on building the initial set of RPMs. pglogical fails to build against  v14. Logs are below. Can you please take a look?

Thanks! Devrim

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -fPIC -I/usr/pgsql-14/include -I -Werror=implicit-function-declaration -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pglogical_queue.o pglogical_queue.c
In file included from pglogical_proto_native.h:20,
                 from pglogical_conflict.h:22,
                 from pglogical_conflict.c:48:
pglogical_output_plugin.h:20:10: fatal error: pglogical_compat.h: No such file or directory
   20 | #include "pglogical_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: pglogical_conflict.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from pglogical_worker.h:18,
                 from pglogical_node.c:42:
pglogical.h:27:10: fatal error: pglogical_compat.h: No such file or directory
   27 | #include "pglogical_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: pglogical_node.o] Error 1
In file included from pglogical_rpc.c:29:
pglogical.h:27:10: fatal error: pglogical_compat.h: No such file or directory
   27 | #include "pglogical_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from pglogical_queue.c:49:
pglogical.h:27:10: fatal error: pglogical_compat.h: No such file or directory
   27 | #include "pglogical_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: pglogical_rpc.o] Error 1
In file included from pglogical_repset.c:50:
pglogical.h:27:10: fatal error: pglogical_compat.h: No such file or directory
   27 | #include "pglogical_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: pglogical_queue.o] Error 1
make[1]: *** [<builtin>: pglogical_repset.o] Error 1
In file included from pglogical_worker.h:18,
                 from pglogical_manager.c:32:
pglogical.h:27:10: fatal error: pglogical_compat.h: No such file or directory
   27 | #include "pglogical_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from pglogical_proto_native.h:20,
                 from pglogical_conflict.h:22,
                 from pglogical_apply.c:64:
pglogical_output_plugin.h:20:10: fatal error: pglogical_compat.h: No such file or directory
   20 | #include "pglogical_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: pglogical_manager.o] Error 1
In file included from pglogical_relcache.c:28:
pglogical.h:27:10: fatal error: pglogical_compat.h: No such file or directory
   27 | #include "pglogical_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: pglogical_apply.o] Error 1
make[1]: *** [<builtin>: pglogical_relcache.o] Error 1
In file included from pglogical_worker.h:18,
                 from pglogical_functions.c:81:
pglogical.h:27:10: fatal error: pglogical_compat.h: No such file or directory
   27 | #include "pglogical_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: pglogical_functions.o] Error 1
In file included from pglogical_proto_native.h:20,
                 from pglogical_conflict.h:22,
                 from pglogical.c:56:
pglogical_output_plugin.h:20:10: fatal error: pglogical_compat.h: No such file or directory
   20 | #include "pglogical_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: pglogical.o] Error 1
make[1]: Leaving directory '/Projects/repo/pgrpms/rpm/redhat/master/non-common/pglogical/master/pglogical-REL2_3_3'
error: Bad exit status from /var/tmp/rpm-tmp.NSH9bV (%build)

**Comment by petere** [comment]
Support for PostgreSQL 14 is being worked on.

**Comment by luss** [comment]
Thanks for keeping up with this Peter.  Are there any architectural changes
in how you want (or need) to get pg_logical working with pg14 or is it
pretty simple stuff this year?

--Luss

**Comment by petere** [comment]
done in 2.4.0

**Comment by xenophenes** [comment]
@petere As you mentioned pg_logical has support for PG14 now, you may want to update the primary GitHub repository description to include PG14 as well for clarity :-)

**Comment by petere** [comment]
> @petere As you mentioned pg_logical has support for PG14 now, you may want to update the primary GitHub repository description to include PG14 as well for clarity :-)

done, thanks
