### ISSUE TITLE
pglogical.so: undefined symbol: elog_finish

### ISSUE THREAD

**Issue by sp1022** [2ndQuadrant/pglogical#324]
when I use pg13 ,install the pglogical lastest  with source code .
but when i use pg_ctl start, performance a error 👍 FATAL:  could not load library "/usr/pgsql-13/lib/pglogical.so": /usr/pgsql-13/lib/pglogical.so: undefined symbol: elog_finish.

**Comment by petere** [comment]
This looks like you built pglogical against a PostgreSQL major version that is different from the one your are running it against.
