### ISSUE TITLE
quote handling in pglogical.replicate_ddl_command 

### ISSUE THREAD

**Issue by tahseenbaig** [2ndQuadrant/pglogical#326]
Provider is on OEL 7 postgres 12.4 and Subscriber in on RDS 13.2

`pglogical.replicate_ddl_command` works fine as long as there are no quotes between start and end of the command.
for example, below works fine
```
select pglogical.replicate_ddl_command('create table public.foo ( like public.orders including all)','{default}'::text[]);
```
Event triggers are setup to add this newly created table to `default` replication_set.

Next, we need to attach table foo as a partition to table orders, and that's where quotes in `FOR VALUES` become a problem.

```
select pglogical.replicate_ddl_command('Alter table public.orders attach partition public.foo for values from ('2021-05-01') TO ('2021-06-01')','{default}'::text[]);
ERROR:  syntax error at or near "2021"
LINE 1: ...ers attach partition public.foo for values from ('2021-05-01...
                                                             ^
```
Could not find anything in docs related to this.
please help.

**Comment by tahseenbaig** [comment]
while I was able to get past the error by doubling the quote ( as the dd command field in the function is a text field), the attach partition did not replicate.
Is ATTACH partition not supported by pglogical?

**Comment by bonesmoses** [comment]
As with any SQL quoting with Postgres, any text strings that contain a literal quote must be escaped. You can do it one of two ways.

Using double-single-quotes:

```sql
select pglogical.replicate_ddl_command('Alter table public.orders attach partition public.foo for values from (''2021-05-01'') TO (''2021-06-01'')','{default}'::text[]);
```

Or using `$$` dollar-quoting SQL-escape syntax:

```sql
select pglogical.replicate_ddl_command($$Alter table public.orders attach partition public.foo for values from ('2021-05-01') TO ('2021-06-01')$$,'{default}'::text[]);
```

You can read more about these in the [PostgreSQL SQL Syntax Documentation](https://www.postgresql.org/docs/current/sql-syntax-lexical.html)

**Comment by tahseenbaig** [comment]
> As with any SQL quoting with Postgres, any text strings that contain a literal quote must be escaped. You can do it one of two ways.
> 
> Using double-single-quotes:
> 
> ```sql
> select pglogical.replicate_ddl_command('Alter table public.orders attach partition public.foo for values from (''2021-05-01'') TO (''2021-06-01'')','{default}'::text[]);
> ```
> 
> Or using `$$` dollar-quoting SQL-escape syntax:
> 
> ```sql
> select pglogical.replicate_ddl_command($$Alter table public.orders attach partition public.foo for values from ('2021-05-01') TO ('2021-06-01')$$,'{default}'::text[]);
> ```
> 
> You can read more about these in the [PostgreSQL SQL Syntax Documentation](https://www.postgresql.org/docs/current/sql-syntax-lexical.html)

@bonesmoses Thanks for your comment. Yes I was able to get past the error by doubling the quote, and it attached the partition on the provider but the command did not get replicated over to my subscription.

**Comment by tahseenbaig** [comment]
Is anyone else able to reproduce this issue - try attaching a partition to your partitioned table with partition expression using `pglogical.replicate_ddl_command` and see if replicates over to your subscriber?

**Comment by tahseenbaig** [comment]
Leaving this note for anyone else who runs into my situation. The requirement is you need to add both parent and all its partitions to the same replication set. In my case I had all the partitions added but not the parent.

**Comment by petere** [comment]
pglogical 2 does not support partitioned tables directly. You need to add the partition to the replication set directly.
