### ISSUE TITLE
Postgres 13 + pglogical 2.3.4 on an existing dataset

### ISSUE THREAD

**Issue by mauhumor** [2ndQuadrant/pglogical#328]
I'm experiencing an issue trying to setup pglogical between a provider and a subscriber, both already have some data in common.
This is a minimal script to reproduce what I'm trying to do:

```sql
CREATE DATABASE db1;
\c db1;
CREATE EXTENSION pglogical;
CREATE TABLE table1(pk_field int primary key , value_field int);
INSERT INTO table1 VALUES(1,1);
INSERT INTO table1 VALUES(2,2);

SELECT pglogical.create_node(
    node_name := 'db1_node',
    dsn := 'host=localhost port=5432 dbname=db1 '
);
SELECT pglogical.replication_set_add_all_tables('default', ARRAY['public']);

CREATE DATABASE db2;
\c db2;
CREATE EXTENSION pglogical;
CREATE TABLE table1(pk_field int primary key , value_field int);
INSERT INTO table1 VALUES(1,1);

SELECT pglogical.create_node(
    node_name := 'db2_node',
    dsn := 'host=localhost port=5432 dbname=db2'
);
SELECT pglogical.create_subscription(
    subscription_name := 'subscription1',
    provider_dsn := 'host=localhost port=5432 dbname=db1'
);
```

I thought that with conflict resolution set to 'apply_remote' pglogical would re-insert on db2 the existing row with PK 1 and insert the new row with PK2. But db2.table1 remains with a single row with PK 1.
Postgres log show this:

```
2021-08-03 01:46:46.771 UTC [4496] ERROR: duplicate key value violates unique constraint "table1_pkey"
2021-08-03 01:46:46.771 UTC [4496] DETAIL: Key (pk_field)=(1) already exists.
2021-08-03 01:46:46.771 UTC [4496] CONTEXT: COPY table1, line 1
2021-08-03 01:46:46.771 UTC [4496] STATEMENT: COPY "public"."table1" ("pk_field","value_field") FROM stdin
2021-08-03 01:47:42.885 UTC [4507] LOG: starting apply for subscription subscription1
2021-08-03 01:47:42.885 UTC [4507] ERROR: subscriber subscription1 initialization failed during nonrecoverable step (d), please try the setup again
2021-08-03 01:47:42.885 UTC [4507] LOG: apply worker [4507] at slot 2 generation 124 exiting with error
2021-08-03 01:47:42.885 UTC [1] LOG: background worker "pglogical apply 30304:1763399739" (PID 4507) exited with exit code 1
```

onflic resultion setting:
```
show pglogical.conflict_resolution;
apply_remote
I also tried with:
```
pglogical.conflict_resolution last_update_wins 
After seeing the COPY fail on the logs and reading on the documentation that the batch would internally use a COPY command, I tried disabling it:
```
pglogical.batch_inserts off
```
It still didn't work

I'm I doing something wrong or I'm misunderstanding how it is supposed to work? Perhaps conflict resolution only applies after the initial replication batch is executed?

Note: If the duplicate row is inserted after initial replication it works fine:
```
2021-08-03 10:39:30.568 UTC [5309] LOG:  CONFLICT: remote INSERT on relation public.table1 (local index table1_pkey). Resolution: apply_remote.
2021-08-03 10:39:30.568 UTC [5309] DETAIL:  existing local tuple {pk_field[int4]:2 value_field[int4]:2} xid=81770,origin=-1,timestamp=; remote tuple {pk_field[int4]:2 value_field[int4]:3} in xact origin=4,timestamp=2021-08-03 10:39:30.566666+00,commit_lsn=0/FEB6918
```

Note II: I have previously posted this on stackoverflow (https://stackoverflow.com/questions/68629647/postgres-13-pglogical-2-3-4-on-an-existing-dataset), not sure if asking it here too would be faux pas or something.

**Comment by petere** [comment]
You are right, conflict resolution does not apply during the initial data sync.

What you read about batch insert does not apply here. The documentation is perhaps worded a little bit ambiguously. What it means is that the batch insert mode uses internal optimizations that are similar to what COPY also uses internally.

**Comment by mauhumor** [comment]
Got it, thanks for clarifying that!

**Comment by mjuvette** [comment]
I have configure replication in postgres between one provider--> subscriber nodes with pglogical extension 2.3.2. and running postgres version 11. But I am getting this error but I cannot find any solution to this. 
CONFLICT: remote UPDATE on relation pac.tai replica identity index pk_rx (tuple not found). Resolution: skip.","remote tuple {rxid[int8]:83694769

**Comment by minhnhupham** [comment]
@mauhumor / @petere , 
Is there a way to solve this?
As this scenario occurs for when doing synchronisation of a backup of a DB to the most recent DB changes.

e.g. 
If I created a new DB from a backup pg_dump of the primary DB.
Then try to sync this new DB to the latest changes. As every table has some sort of primary key this basically breaks.

Is there a way to solve this so during the initial data sync the conflict resolution rule is honoured ?

**Comment by tbecks** [comment]
I have a similar issue (using 2.4.1).  

I backup and restore a database using pg_dump/pg_restore for a large bulk load.  Then enable pglogical replication.  However there are new records between the time I took the backup and enabled replication that are not captured and replicated as part of the replication process.  New records will be ingested, but there is a delta between the pg_dump and pglogical replication that are never replicated to the replica server.

Is there a way pglogical can sync the data when the replication first starts?

**Comment by koureasstavros** [comment]
I was wondering about the exact same thing with @tbecks comment. In my case I have an application in which you can perform manual copy using sql statements to replicate the data: INSERT INTO.... SELECT FROM.... and then enable the replication. I came to PGLogical from Logical Replication to test the conflict resolution.

My idea (which I havent test yet with PGLogical is the following:
Step1: Start PG Logical without initial load
Step2: Copy manually all the data between source to destination to all or desired tables
This way there is no gap which can make database inconsistent.

But I am not sure if there is an option to disable initial snapshot like Logical Replication has, is there any such an option?
If there is I will test this schenario

**Comment by koureasstavros** [comment]
Just figured out that the option to not perform the initial load is the option synchronize_data := false, now the question is the following: If I enable replication without initial load and perform the initial load manually (using ONCONFLICT statement) if a row is inserted into source database and inserted with manual load is the replication going to update this record once it captures it?

So in sort, the question is what will happen in case record transfer happen faster with manual copy before pglogical replication apply the record (or slower within pglogical after manual copy is transferred that line). I am not sure how I can test that.

On the other side if I am not mistaken in most RDBMs the select statement produces a kind of shared lock which takes the snapshot of the records at the moment of the select, so this also ensures that if any new record arrives into source database during the manual copy it will not be taken into consideration from manual copy but only from replication. In this case there will  be no conflict. I think same applies for Native Logical Replication).

But what happens if that line is replicated much later after manual copy is performed including that line?
Scenario:
Line is inserted into source
Perform manual copy (by accident, in milliseconds from line insertion, line is included)
Line is being replicated from PGLogical (so there is conflict)
Is it going to work?
