### ISSUE TITLE
ERROR:  output plugins have to declare the _PG_output_plugin_init symbol

### ISSUE THREAD

**Issue by osiro** [2ndQuadrant/pglogical#331]
Hi all,

I have installed and configured `pglogical` version [1.2.2](http://packages.2ndquadrant.com/pglogical/tarballs/pglogical-1.2.2.tar.bz2) into a `PosgreSQL` server version **9.4.1**.

Creating the extensions `pglogical_origin` and `pglogical` as well as the provider node and the replication set work well.

However, I get the following error when trying to create a replication slot:

```sql
SELECT * FROM pg_create_logical_replication_slot('replication_slot_name', 'pglogical');
ERROR:  output plugins have to declare the _PG_output_plugin_init symbol
```

Note that the installation of pglogical has been done from source code by running the following commands:

```bash
cd pglogical-1.2.2
PATH=/my-postgres/bin:$PATH make clean all
PATH=/my-postgres/bin:$PATH make install
```

Am I missing anything?

**Comment by petere** [comment]
pglogical 1.x is no longer supported. Please use a newer version.
