### ISSUE TITLE
pgLogical row_filter for jsonb type

### ISSUE THREAD

**Issue by NamDL** [2ndQuadrant/pglogical#332]
Does pgLogical allow for filtering based on a jsonB value? I have been trying to use row filter but cant get it to work. Here is my data -

Table person:
 ```
        id                  serial,
        name                TEXT NOT NULL,
        details          JSONB NOT NULL,
        modified_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        PRIMARY KEY (name)); 
```
Sample data:

 ```
id |  name   |     details     |          modified_at          
----+---------+-----------------+-------------------------------
  1 | person1 | {"city": "nyc"} | 2021-05-17 06:05:55.735086+00
  2 | person2 | {"city": "SF"}  | 2021-05-17 06:06:30.028065+00
```
I have tried the following and they don't work:

`SELECT pglogical.replication_set_add_table(set_name:= 'replicate1', relation := 'person', row_filter:= details->>'city' = 'nyc');`
The other option I tried:

`SELECT pglogical.replication_set_add_table(set_name:= 'replicate1', relation := 'person', row_filter:= "details->>'city' = 'nyc'"); `

**Comment by petere** [comment]
Try

```sql
SELECT pglogical.replication_set_add_table(set_name:= 'replicate1', relation := 'person', row_filter:= ' details->>''city'' = ''nyc'' ');
```

or

```sql
SELECT pglogical.replication_set_add_table(set_name:= 'replicate1', relation := 'person', row_filter:= $$ details->>'city' = 'nyc' $$);
```

**Comment by NamDL** [comment]
Awesome, that worked! Thank you @petere

**Comment by pavan-postgres** [comment]
@petere How does the syntax work for column filtering:

Table person:

       id                  serial,
       name                TEXT NOT NULL,
       details          JSONB NOT NULL,
       modified_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
       PRIMARY KEY (name)); 
Sample data:

id |  name   |     details     |          modified_at          
----+---------+-----------------+-------------------------------
 1 | person1 | {"city": "nyc"} | 2021-05-17 06:05:55.735086+00
 2 | person2 | {"city": "SF"}  | 2021-05-17 06:06:30.028065+00`

I want the columns details and modified_at to be excluded while replicating data to subscriber. How do I achieve this?

Will the below syntax works?

`SELECT pglogical.replication_set_add_table(set_name:= 'replicate1', relation := 'person', column_filter not in ( $$ details $$ and $$ modified_at $$);
`

**Comment by eulerto** [comment]
If you want to include **only** columns `id` and `name`, use the following command:

```sql
SELECT pglogical.replication_set_add_table(set_name:= 'replicate1', relation := 'person', columns := '{id, name}');
```

Column filter provides an array of attribute names that you want to replicate. Remember that replica identity columns must be included in this list; otherwise, you will get an error.

BTW, column filter is different from row filter. You shouldn't use closed issue to ask a question or even report a similar issue (unless you want to discuss the exact same issue). In this case, you should have open a new issue.
