### ISSUE TITLE
snapshot active issue

### ISSUE THREAD

**Issue by marianmacleod1** [2ndQuadrant/pglogical#336]
Upgraded pglogical to 2.4.0 on a postgres 13.4 database this week.
Every change to the data is generating the following in the log file

2021-08-19 14:01:55 BST [4967]: [472961][7619810] user=[unknown],db=dw,host=WARNING:  snapshot 0x10c6a68ctive
2021-08-19 14:01:55 BST [4967]: [472971][7619810] user=[unknown],db=dw,host=CONTEXT:  apply COMMIT in coore 32/ADD9E760, xid 8118781 committed at 2021-08-19 14:01:55.564834+01 (action #6) from node replorigin 2

This is happening on both the 13.4 databases.  The pglogical upgrade was applied to older database versions e.g. 11 without having the same issues.
There are 4 subscriptions to 3 different servers.  If I disable all subscriptions then there are no error messages.  As soon as I enable 1 then the messages start writing to the log again and there are millions of them. The database has restarted since the upgrade to pglogical was applied.  
2 of the subscriptions have been rebuilt from scratch. This has not made any difference.

**Comment by rauanmayemir** [comment]
I've tried to migrate v12 to v13 with 2.4.0 on both prodiver and subscriber node and have been seeing this warning a lot.
Do I need to worry about it if my data seems to be synced okay?

**Comment by petere** [comment]
closed by #338
