### ISSUE TITLE
PostgreSQL 14 packages?

### ISSUE THREAD

**Issue by pdeaudney** [2ndQuadrant/pglogical#346]
I see there is PG14 support, will there be packages built some time? If help is required I may be able to contribute changes.

**Comment by martinmarques** [comment]
Could you be more specific on packaging for which distribution you are referring to? I can see packages for RHEL distributions (those rpm-based) in the PGDG repository.

https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-8-aarch64/

**Comment by koleo** [comment]
I guess this is about Debian/Ubuntu APT packages...

**Comment by martinmarques** [comment]
If it's related to APT packages, you should check with @df7cb

**Comment by mbanck** [comment]
The 2.4.0 release has Postgres 14 support as being preliminary and in beta according to the release notes, is this no longer the case?

**Comment by mbanck** [comment]
@pdeaudney packages have been uploaded some days ago and should also be on PGDG now

**Comment by martinmarques** [comment]
Thanks Michael for that info. I'm going to close this as it's not a pglogical issue per-se, but more related to packaging for Debian. In any case, @pdeaudney please use the PGDG channels to request that missing packages be added.
