### ISSUE TITLE
need help on pglogical per table control

### ISSUE THREAD

**Issue by sandeepkalra** [2ndQuadrant/pglogical#355]
Hi All:

I recently migrated to version 2.4.0 of pglogical (from pglogical 2.3.2). I was using pglogical to do streaming on selective tables, but after this upgrade found that it is *not working* with older steps using `pglogical.replication_set_add_table()`, however things work fine if I  use `pglogical.replication_set_add_all_tables()` to do it full database replication. Moreover, in my experiments I found that it is working more reliable if i add all_tables query twice - once for the replica-set that I created, and then for 'default' that the system has. 

comparison of the steps:
```
Old Setup:
  create_node('n0'),  
  create_replication_set('rep1'),  
  for table_name in selected_tables: 
        replication_set_add_table('rep1', <table_name>)

Old Tearing:
 for table_name in selected_tables: 
       replication_set_remove_table('rep1', <table_name>)
drop_replication_set('rep1')

As of now, I had something like this to make it to work: 
New Setup:
 create_node('n0'),  
 create_replication_set('rep1'),  
 replication_set_add_all_tables('rep1', ARRAY['public'])      <<< modified step
 replication_set_add_all_tables('default', ARRAY['public']) <<< modified step

New Tearing:
 for table_name in selected_tables: 
       replication_set_remove_table('rep1', <table_name>) <<< now this step fails
drop_replication_set('rep1')
```

If I try to repeat what i had earlier, then the logical slots are not created. With all settings as is, switching to all table works. I still want to go back to support only table level streaming (and not complete database). 

It may be some setup issue at my end or change in library that is causing it. I am a bit clueless at this point. Is there some change in procedure that I should take care for going back to table level controls? 

Please suggest.

Thanks,
Sandeep

PS: I have not pasted the DSN part, but the actual queries in system has it.

**Comment by eulerto** [comment]
I didn't get it. What's the exact error message? Are you sure the subscriber is referring to the correct replication set?

Don't use 2.4.0. 2.4.1 was released a few days ago.
