### ISSUE TITLE
Replication with incorrect timestamps

### ISSUE THREAD

**Issue by osiro** [2ndQuadrant/pglogical#357]
I am configuring logical replication to get rid of PostgreSQL with `Date/time type storage: floating-point numbers`, the replication goes well but some records present incorrect timestamps.

Provider: `PostgreSQL 9.4.26 with Date/time type storage: floating-point numbers`
Subscriber: `PostgreSQL 9.4.26 with Date/time type storage: 64-bit integers`

The provider contains the following records:

```
 id                 |       createdtime
------------+-------------------------
   27070044 | 2021-12-14 19:29:36.837
   27070043 | 2021-12-14 19:29:13.281
   27070042 | 2021-12-14 19:28:49.085
   27070041 | 2021-12-14 19:28:06.468
```

But the subscriber presents this instead:

```
 id                 |         createdtime
------------+------------------------------
   27070044 | 152175-12-11 03:21:05.129169         <-----------------
   27070043 | 152175-12-11 03:17:47.527119          <-----------------
   27070042 | 2021-12-14 19:28:49.085
   27070041 | 2021-12-14 19:28:06.468
```

I haven't encountered errors in the PostgreSQL, and the current status of the subscription still `replicating`. 

Can anyone point me in the right direction? Is there anything I am missing out?

Note: the version of `PgLogical` is `2.2.1`.

**Comment by simonat2ndQuadrant** [comment]
On Tue, 14 Dec 2021 at 09:22, Vinny Osiro ***@***.***> wrote:

> I am configuring logical replication to get rid of PostgreSQL with Date/time
> type storage: floating-point numbers, the replication goes well but some
> records present incorrect timestamps.
>
> Provider: PostgreSQL 9.4.26 with Date/time type storage: floating-point
> numbers
> Subscriber: PostgreSQL 9.4.26 with Date/time type storage: 64-bit integers
>
Since Postgres 9.4 is no longer supported, it seems likely there are
unresolved issues in that release.

Please get in touch with EDB Professional Services on
 https://www.enterprisedb.com/contact
for assistance.

-- 
Simon Riggs                http://www.EnterpriseDB.com/
