### ISSUE TITLE
Logical replication won't start due to syntax issues.

### ISSUE THREAD

**Issue by fr33l** [2ndQuadrant/pglogical#358]
Hi, 

First, of thanks for your work guys, this is a life saver for many of us outhere. 

We are trying to create replication:

`source: psql 9.5, 2.3.4-1.xenial+1`
`target: psql 12, 2.4.1-1.focal+1`

But after creating subscription it fails:

Source:
```
2021-12-21 15:23:26 UTC [48595-2] replica@db STATEMENT:  SELECT i.relid, i.nspname, i.relname, i.att_list,       i.has_row_filter, i.nspname as i.nsptarget, i.relname as i.reltarget  FROM (SELECT DISTINCT relid FROM pglogical.tables WHERE set_name = ANY(ARRAY['default','default_insert_only','ddl_sql'])) t,       LATERAL pglogical.show_repset_table_info(t.relid, ARRAY['default','default_insert_only','ddl_sql']) i
```

Target: 
```
2021-12-21 15:23:26 UTC [32165-2] [unknown]@db ERROR:  could not get table list: ERROR:  syntax error at or near "."
	LINE 1: ...i.att_list,       i.has_row_filter, i.nspname as i.nsptarget...
	                                                             ^
```

I saw https://github.com/2ndQuadrant/pglogical/issues/240 [248 ](https://github.com/2ndQuadrant/pglogical/issues/248) and so on, be it appears like we are hitting the same? . 

Worth noting, when I first created nodes and subscription versions of pglogical were:

`source: psql 9.5, 2.3.3-2.pgdg16.04+1`
`target: psql 12, 2.3.0-1`

After upgrade, I purged existing subscriptions and created new ones, still the same issue. Should we purge all nodes and create new ones with new versions?

**Comment by fr33l** [comment]
>  Should we purge all nodes and create new ones with new versions?

That was the case, yup. 

To anyone out there, if you are upgrading your pglogical versions you should reinstall pglogical extension in postgres and recreate nodes/subscriptions.

**Comment by petere** [comment]
> > Should we purge all nodes and create new ones with new versions?
> 
> That was the case, yup.
> 
> To anyone out there, if you are upgrading your pglogical versions you should reinstall pglogical extension in postgres and recreate nodes/subscriptions.

The faulty queries were not in the extension definition scripts, so it's not clear why this helped. In any case, the issue was with the 2.3.0 release somehow.
