### ISSUE TITLE
Help with pglogical's handling of LOBs

### ISSUE THREAD

**Issue by Prajaktcs** [2ndQuadrant/pglogical#359]
We are currently using pglogical v2.4.0 on AWS RDS v13.4. We use AWS dms with pglogical to replicate data in another postgres instance.

After a few days the DMS tasks stops with only a warning message 
```[SOURCE_CAPTURE  ]W:  Value of column 'value_multiline_text' in table 'public.entity_values' was truncated to 524288 bytes, actual length: -66165448 bytes  (postgres_pglogical.c:2343)```

We opened a case with AWS support and they advised us to not use pglogical because of the way pglogical manages large objects. This was their reply - 
```
 Unfortunately the negative LOB calculation issue faced by the DMS task is due to the 'pglogical' plugin and the manner in which the plugin manages Large Objects (LOBs). Making use of the 'test_decoding' plugin is currently the only known workaround as the LOB sizes are calculated correctly when this plugin is used. 
```

Does anyone know how to get around this? We really love using pglogical and dont really have any problems other than this one.

Thank you in advance!!

**Comment by petere** [comment]
That source file (`postgres_pglogical.c`) and the message are not part of PostgreSQL or pglogical, so you will have to defer to AWS support about the details of what this means. In any case, "large objects" are not supported in pglogical, and there are no plans to change this.

**Comment by Prajaktcs** [comment]
Thank you @petere for letting me know. Yeah, not knowing how we end up with the negative bytes is really throwing us off. We will try to push AWS to get an answer there.
