### ISSUE TITLE
release tarball cant be built 

### ISSUE THREAD

**Issue by darix** [2ndQuadrant/pglogical#36]
```
 pglogical_hooks.c:24:36: fatal error: pglogical_output/hooks.h: No such file or directory
```

**Comment by ringerc** [comment]
On 23 August 2016 at 22:32, darix <notifications@github.com> wrote:

>  pglogical_hooks.c:24:36: fatal error: pglogical_output/hooks.h: No such file or directory
>
>
It must be built against a PostgreSQL with pglogical_output installed.


-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by darix** [comment]
Given you have to have both installed on all machines according to your documentation ... does it really make sense to split the tarballs? 

also this gives me the impression this might actually be intended to have just one tarball instead of 2:

```
$ tar tf *bz2  | grep output
pglogical-1.1.2/pglogical_output/
```
