### ISSUE TITLE
Schema in relation name and row-filtering clarity

### ISSUE THREAD

**Issue by PenguinFlyingHigh** [2ndQuadrant/pglogical#365]
We do not use the public schema, instead we use `abc` schema. 

When trying to add a table to the replication set, 
`select pglogical.replication_set_add_table(set_name:= 'test-replication-set', relation:= 'abc.tablename')`
It fails with "Relation abc.tablename does not exist"

Okay fine, we can get around that by using the table's `relid` which I can find querying `select * from pglogical.tables`
So this works `select pglogical.replication_set_add_table(set_name:= 'test-replication-set', relation:= '123456')`

However, I am stumped about adding a row_filter to this table. 

Trying `select pglogical.replication_set_add_table(set_name:= 'test-replication-set', relation:= '123456', row_filter:= 'CreatedTimestamp > ''2022-01-19T01:48:00''')` fails because it complains that the column cannot be found. It's suggested that I try adding tablename to the filter. 

`select pglogical.replication_set_add_table(set_name:= 'test-replication-set', relation:= '123456', row_filter:= 'tablename.CreatedTimestamp > '''2022-01-19T01:48:00''')` fails and complains "ERROR: missing FROM-clause entry for table "tablename""

Is it possible to row-filter on a column of a table that does not belong in the public schema? 

Out of curiosity, I re-created the same table in `public` schema and I was able to successfully add the table with row_filter to the replication set with just `select pglogical.replication_set_add_table(set_name:= test-replication-set'', relation:= 'tablename',  row_filter:= 'timestamp > ''2022-01-19T01:48:00''');`

**Comment by eulerto** [comment]
> When trying to add a table to the replication set,
select pglogical.replication_set_add_table(set_name:= 'test-replication-set', relation:= 'abc.tablename')
It fails with "Relation abc.tablename does not exist"

It seems your problem is that unquoted identifiers are case insensitive. Your schema name or table name probably contains uppercase or even its name is a keyword. Check the [PostgreSQL documentation](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS).

Regarding the row filtering, you don't need to refer to `relation` by OID, you can use the `schema.name` notation. See table "Baz" in the example below.

The row filtering expression does not require the table name. You can use just the column name. Have in mind that, if the column name has uppercase characters (like `CreatedTimestamp`) or it is a keyword, you need to quote it. See the example below.

```
postgres=# create extension pglogical;
CREATE EXTENSION
postgres=# \dx
                   List of installed extensions
   Name    | Version |   Schema   |          Description           
-----------+---------+------------+--------------------------------
 pglogical | 2.4.1   | pglogical  | PostgreSQL Logical Replication
 plpgsql   | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

postgres=# create schema foo;
CREATE SCHEMA
postgres=# create table foo.bar (a int primary key, b text);
CREATE TABLE
postgres=# \d foo.bar
                                 Table "foo.bar"
      Column      |            Type             | Collation | Nullable | Default 
------------------+-----------------------------+-----------+----------+---------
 a                | integer                     |           | not null | 
 CreatedTimestamp | timestamp without time zone |           |          | 
Indexes:
    "bar_pkey" PRIMARY KEY, btree (a)

postgres=# select pglogical.create_node('node1', 'host=localhost dbname=postgres');
 create_node 
-------------
  1148549230
(1 row)

postgres=# select pglogical.create_replication_set('test');
 create_replication_set 
------------------------
             3612699271
(1 row)

postgres=# select pglogical.replication_set_add_table(set_name := 'test', relation := 'foo.bar', row_filter := 'CreatedTimestamp > ''2022-01-19T01:48:00''');
ERROR:  column "createdtimestamp" does not exist
HINT:  Perhaps you meant to reference the column "bar.CreatedTimestamp".
postgres=# select pglogical.replication_set_add_table(set_name := 'test', relation := 'foo.bar', row_filter := '"CreatedTimestamp" > ''2022-01-19T01:48:00''');
 replication_set_add_table 
---------------------------
 t
(1 row)

postgres=# select set_id, set_reloid, pg_get_expr(set_row_filter, set_reloid) from pglogical.replication_set_table;
   set_id   | set_reloid |                                pg_get_expr                                
------------+------------+---------------------------------------------------------------------------
 3612699271 | foo.bar    | ("CreatedTimestamp" > '2022-01-19 01:48:00'::timestamp without time zone)
(1 row)

postgres=# create table foo."Baz" (a int primary key, b text);
CREATE TABLE
postgres=# select pglogical.replication_set_add_table(set_name := 'test', relation := 'foo."Baz"');
 replication_set_add_table 
---------------------------
 t
(1 row)
```

**Comment by PenguinFlyingHigh** [comment]
Amazing, thank you for pointing out my mistake with not using double quotes with my table name. Your suggestion and example was very clear!
