### ISSUE TITLE
Issues compiling

### ISSUE THREAD

**Issue by dynelow** [2ndQuadrant/pglogical#390]
Hi, 
I'm new in this and need some help please.
Having this error while make
/usr/bin/ld: cannot find -lselinux
/usr/bin/ld: cannot find -lxslt
/usr/bin/ld: cannot find -lxml2
/usr/bin/ld: cannot find -lpam
/usr/bin/ld: cannot find -ledit
collect2: error: ld returned 1 exit status
make: *** [Makefile:147: pglogical_create_subscriber] Error 1

I instead have 
- /usr/lib/x86_64-linux-gnu/libselinux.so.1
- /usr/lib/x86_64-linux-gnu/libxslt.so.1
- /usr/lib/x86_64-linux-gnu/libxml2.so
- /usr/lib/x86_64-linux-gnu/libpam.so.0
- /usr/lib/x86_64-linux-gnu/libedit.so.2

Please what do i need to do.

**Comment by petere** [comment]
You need to provide more details, like what platform you are on, how you installed PostgreSQL proper, what commands you used to build pglogical, etc.

**Comment by dynelow** [comment]
Oh sorry,
postgres@ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

I have the same on WSL, and VMware16

I installed postgreSQL using apt-get-install (both for version 10 and 13), as well as dev-13, and Python 3.8.10
pglogical installed via apt-get install postgresql-10-pglogical is working just fine.
But i need to be able to build:
- I cloned this repo "https://github.com/2ndQuadrant/pglogical.git"
- and the Make gave the above error.

**Comment by petere** [comment]
Please show all the exact commands and the full output from `make`.

**Comment by dynelow** [comment]
postgres@ubuntu:~$ git clone "https://github.com/2ndQuadrant/pglogical.git"
postgres@ubuntu:~$ cd pglogical

postgres@ubuntu:~/pglogical$ make
sed 's/__PGLOGICAL_VERSION__/2.4.1/;s/__REQUIRES__//' /var/lib/postgresql/pglogical/pglogical.control.in > /var/lib/postgresql/pglogical/pglogical.control
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/var/lib/postgresql/pglogical/compat10 -Werror=implicit-function-declaration -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_worker.o pglogical_worker.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/var/lib/postgresql/pglogical/compat10 -Werror=implicit-function-declaration -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_sync.o pglogical_sync.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/var/lib/postgresql/pglogical/compat10 -Werror=implicit-function-declaration -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_sequences.o pglogical_sequences.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/var/lib/postgresql/pglogical/compat10 -Werror=implicit-function-declaration -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_executor.o pglogical_executor.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/var/lib/postgresql/pglogical/compat10 -Werror=implicit-function-declaration -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_dependency.o pglogical_dependency.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/var/lib/postgresql/pglogical/compat10 -Werror=implicit-function-declaration -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_apply_heap.o pglogical_apply_heap.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/var/lib/postgresql/pglogical/compat10 -Werror=implicit-function-declaration -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_apply_spi.o pglogical_apply_spi.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/var/lib/postgresql/pglogical/compat10 -Werror=implicit-function-declaration -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_output_config.o pglogical_output_config.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/var/lib/postgresql/pglogical/compat10 -Werror=implicit-function-declaration -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_output_plugin.o pglogical_output_plugin.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/var/lib/postgresql/pglogical/compat10 -Werror=implicit-function-declaration -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_output_proto.o pglogical_output_proto.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/var/lib/postgresql/pglogical/compat10 -Werror=implicit-function-declaration -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_proto_json.o pglogical_proto_json.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/var/lib/postgresql/pglogical/compat10 -Werror=implicit-function-declaration -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_proto_native.o pglogical_proto_native.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/var/lib/postgresql/pglogical/compat10 -Werror=implicit-function-declaration -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_monitoring.o pglogical_monitoring.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/var/lib/postgresql/pglogical/compat10 -Werror=implicit-function-declaration -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o compat10/pglogical_compat.o compat10/pglogical_compat.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -shared -o pglogical.so pglogical_apply.o pglogical_conflict.o pglogical_manager.o pglogical.o pglogical_node.o pglogical_relcache.o pglogical_repset.o pglogical_rpc.o pglogical_functions.o pglogical_queue.o pglogical_fe.o pglogical_worker.o pglogical_sync.o pglogical_sequences.o pglogical_executor.o pglogical_dependency.o pglogical_apply_heap.o pglogical_apply_spi.o pglogical_output_config.o pglogical_output_plugin.o pglogical_output_proto.o pglogical_proto_json.o pglogical_proto_native.o pglogical_monitoring.o .//compat10/pglogical_compat.o -L/usr/lib/x86_64-linux-gnu  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed  -L/usr/lib/x86_64-linux-gnu -lpq  
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I/var/lib/postgresql/pglogical/compat10 -Werror=implicit-function-declaration -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_create_subscriber.o pglogical_create_subscriber.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC pglogical_create_subscriber.o pglogical_fe.o -L/usr/lib/x86_64-linux-gnu  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed  -L/usr/lib/postgresql/10/lib -lpgcommon -lpgport -L/usr/lib/x86_64-linux-gnu -lpq -lpgcommon -lpgport -lpthread -lselinux -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -ledit -lrt -lcrypt -ldl -lm -o pglogical_create_subscriber
/usr/bin/ld: cannot find -lselinux
/usr/bin/ld: cannot find -lxslt
/usr/bin/ld: cannot find -lxml2
/usr/bin/ld: cannot find -lpam
/usr/bin/ld: cannot find -ledit
collect2: error: ld returned 1 exit status
make: *** [Makefile:147: pglogical_create_subscriber] Error 1

**Comment by luss** [comment]
Pglogical compiles like most all other pg extensions.

I recommend you to first download a src tarball of postgres and the. do a
./configure; make; make install.  Then be sure your path includes your
pgbin directory.  Then go to the contrib directory and download and extract
a tarball for pg_logical.   Change into the pg_logical directory and do a
make & a make install.

**Comment by luss** [comment]
https://github.com/2ndQuadrant/pglogical#from-source-code

**Comment by petere** [comment]
Maybe you need to install the -dev packages that correspond to those missing libraries.

**Comment by eulerto** [comment]
Execute:

`sudo apt-get build-dep postgresql-10-pglogical`

and try again.
