### ISSUE TITLE
PG15 Support

### ISSUE THREAD

**Issue by luss** [2ndQuadrant/pglogical#391]
Any word?

**Comment by luss** [comment]
i understand this is non trivial.   is the effort started?

**Comment by petere** [comment]
PG15 support is in progress and should be released in time for the PG15 release.

**Comment by luss** [comment]
great news, thanks.

**Comment by NitinJadhav-postgres** [comment]
Is it possible to commit the beta version if available?

**Comment by luss** [comment]
pg15 rc1 is coming out in 36 hours and 15.0 GA is scheduled for two weeks after that

**Comment by petere** [comment]
This is now available in version 2.4.2.
