### ISSUE TITLE
Future support for pglogical after pg15. (replicate_ddl_command not in in core postgres)

### ISSUE THREAD

**Issue by jamesrhbailey** [2ndQuadrant/pglogical#396]
Great news on pg15 support. What is the longer term outlook for future versions of postgres? We are keen on the replicate_ddl_command command and do not see this currently in the in core versions of postgres.

**Comment by petere** [comment]
The pglogical issue tracker isn't really the place to discuss core postgres development.

**Comment by jamesrhbailey** [comment]
Sorry that is written a little ambiguously. The question, better put, is: What is the longer term outlook for pglogical against future versions of postgres?

**Comment by petere** [comment]
We are working on migrating all relevant functionality from pglogical into core PostgreSQL. So pglogical will eventually go away.
