### ISSUE TITLE
Unable to drop the database when pglogical extension is preloaded

### ISSUE THREAD

**Issue by NitinJadhav-postgres** [2ndQuadrant/pglogical#399]
Following are the steps to reproduce the issue.

1. Include pglogical extension in 'shared_preload_libraries' parameter in postgresql.conf file.
2. Start the server and connect psql.
3. Create database testdb;
4. Drop database testdb; - This command will hang and never completes.

Kindly let me know if I am missing something.

**Comment by NitinJadhav-postgres** [comment]
Kindly acknowledge.

**Comment by eulerto** [comment]
Thanks for your report. What's your pglogical version? What's your PostgreSQL version? I bet it is 15. I couldn't reproduce this issue on 14 or earlier. ... _poking PostgreSQL code_ ... Commit postgres/postgres@4eb2176318d includes a signal barrier for DROP DATABASE. pglogical has no logic to handle it in the supervisor code. I think a simple CHECK_FOR_INTERRUPTS might fix it. Another option might be to call a function that handles barrier events.

**Comment by NitinJadhav-postgres** [comment]
Thanks for the reply. The pglogical version is 2.4.2 and PostgreSQL version is 15. The analysis and the fix looks good to me.

**Comment by EinKrebs** [comment]
@eulerto can you tell me when this fix will be released?
