### ISSUE TITLE
Postgres 16 support

### ISSUE THREAD

**Issue by Deltaus** [2ndQuadrant/pglogical#428]
Tried building the current version with Postgres 16 but saw some build errors. May I know when we can expect a PG16 compatible version to be released? Thank you!

**Comment by lizhiygu** [comment]
Hello, PostgreSQL 16 Beta 1/2/3 are out. What are the plans for v16 support? Thanks!

**Comment by devrimgunduz** [comment]
Ping. v16 is out next week.

**Comment by devrimgunduz** [comment]
ping

**Comment by vyruss** [comment]
PR is #437

**Comment by eulerto** [comment]
@devrimgunduz @df7cb new version (2.4.4) was released.

**Comment by devrimgunduz** [comment]
Thanks!

**Comment by rauanmayemir** [comment]
Can rpm/deb repositories be updated as well?

**Comment by df7cb** [comment]
@rauanmayemir yum/apt.postgresql.org have already been updated.

**Comment by rauanmayemir** [comment]
@df7cb Oh, thank you! I was searching inside 2ndQuadrant/EDB repository. 😅
