### ISSUE TITLE
No data copied from provider to subscriber

### ISSUE THREAD

**Issue by Summer88** [2ndQuadrant/pglogical#44]
CREATE EXTENSION pglogical;

on SUBSCRIBER HOST:

```

SELECT pglogical.create_node(
    node_name := 'provider1',
    dsn := 'host=1.1.1.1 port=5432 dbname=DB'
);

SELECT pglogical.create_subscription(
    subscription_name := 'subscription1',
    provider_dsn := 'host=1.1.1.1 port=5432 dbname=DB',
    synchronize_structure := false,
    synchronize_data := true
);
```

on PROVIDER host:

```
SELECT pglogical.create_node(
    node_name := 'subscriber1',
    dsn := 'host=1.1.1.2 port=5435 dbname=DB'
);

select pglogical.replication_set_add_all_tables('default', ARRAY['public']);

select pglogical.replication_set_add_table(
 set_name := 'default',
 relation := 'public.mytable',
 synchronize_data := true);


```

select \* from pg_stat_replication;

```

  pid  | usesysid | usename  | application_name | client_addr | client_hostname | client_port |         backend_start         | backend_xmin |   state   | sent_location | write_location | flush_location | replay_location | sync_priority | sync_state 
-------+----------+----------+------------------+-------------+-----------------+-------------+-------------------------------+--------------+-----------+---------------+----------------+----------------+-----------------+---------------+------------
 13648 |       10 | postgres | subscription1    | 1.1.1.2  |                 |       48054 | 2016-10-04 17:00:56.730186+02 |              | streaming | 0/1947E3C8    | 0/1947E3C8     | 0/1947E3C8     | 0/1947E3C8      |             0 | async
(1 riga)

```

Tried also:
select pglogical.alter_subscription_resynchronize_table('subscription1', 'public.go_ovr');

but still:

PROVIDER log says:

> postgres@DB CONTEXT:  COPY mytable, row 1
>                        ISTRUCTION:  COPY "public"."mytable" FROM stdin
>                        DETAILS: Key (id)=(28) already exist.

SUBSCRIBER LOG:

> 2016-10-04 16:47:10 CEST [8449-1] LOG:  starting pglogical database manager for database DB
> 2016-10-04 16:47:10 CEST [8450-1] LOG:  starting apply for subscription subscription1
> 2016-10-04 16:47:11 CEST [8463-1] LOG:  manager worker [8463] at slot 3 generation 1 detaching cleanly

I've created only the structure on the SUBSCRIBER host, no data are present (with pg_dump -s).
Why the Provider continue to say that key already exist if no data at all are present?

> DB=# select \* from pglogical.local_sync_status;
>  sync_kind | sync_subid | sync_nspname | sync_relname | sync_status 
> -----------+------------+--------------+--------------+-------------
>  d         | 1763399739 |              |              | r
>  d         | 1763399739 | public       | mytable       | r

**Comment by PJMODOS** [comment]
You sure you don't have duplicate data on the provider (ie corrupted PKey)?

**Comment by john5000** [comment]
Looks like your ip addresses and also provider/subscriber are swapped around on the create_node(...) calls.

On your subscriber, name the node 'subscriber1' and with the ip address of the subscriber (its own IP address).

On your provider, name the node 'provider1' and with the ip address of the provider (also its own IP address).

Execute the create _subscription(...) call on the subscriber and the dsn points to the provider (looks like you have that correct already).

Then retry.  After you start the subscription, get on the provider and check that it connected by doing:

`
select * from pg_replication_slots
`
Hope that helps.

**Comment by PJMODOS** [comment]
Hah, that's good point @john5000 , I completely missed that, so the replication is actually defined as circular here which explains the data coflict.
