### ISSUE TITLE
What is the difference between using this extension and inbuilt logical replication?

### ISSUE THREAD

**Issue by drticcz** [2ndQuadrant/pglogical#449]
I cannot find out what is the difference. 
The documentation here involves installing and loading an extension, while the [official Postgres guide](https://www.postgresql.org/docs/current/logical-replication-quick-setup.html) describes a slightly different approach to running the logical replication which works without installing and loading any extension. 

Is the documentation here just outdated or the extension codebase is different than the "inbuilt Postgres logical" ?

**Comment by dubek** [comment]
Here's a post for 2017 explaining this: https://www.2ndquadrant.com/en/blog/pglogical-logical-replication-postgresql-10/

Besides the different syntax, pglogical has some features not available in current Postgres (16), such as [conflict resolution](https://github.com/2ndQuadrant/pglogical?tab=readme-ov-file#conflicts).

**Comment by drticcz** [comment]
Thanks, this explains a lot!
