### ISSUE TITLE
2ndQuadrant GPG public key expired - blocks installs

### ISSUE THREAD

**Issue by NValan** [2ndQuadrant/pglogical#464]
The GPG public key available at https://dl.2ndquadrant.com/gpg-key.asc (and content in bash script https://dl.2ndquadrant.com/default/release/get/deb or https://techsupport.enterprisedb.com/api/repository/dl/default/release/deb) are all expired:

> pub   rsa4096 2018-03-14 [SC] [expired: 2024-03-08]
>       8565305CEA7D0B664933D2509904CD4BD6BAF0C3
> uid           Public repository signing key 2ndQuadrant <ci@2ndquadrant.com>

This blocks installation of the repo (and updates thereof)

**Comment by przemyslavic** [comment]
It looks like the GPG public key has just been updated 👍

**Comment by NValan** [comment]
Indeed, it has been.
