### ISSUE TITLE
Large objects documentation wrong?

### ISSUE THREAD

**Issue by jcoleman** [2ndQuadrant/pglogical#467]
The README says:

```
Large objects

PostgreSQL's logical decoding facility does not support decoding changes to large objects, so pglogical cannot replicate large objects.
```

I can only imagine this refers to TOAST since I'm not sure what other Postgres feature "large objects" would refer to, but there are in-project tests for replication of TOASTed values, and our own testing confirms the same.

Is this outdated documentation (maybe it was true in a very old version of Postgres)? Or is there something else this refers to?

**Comment by nmisch** [comment]
This refers to https://www.postgresql.org/docs/current/largeobjects.html, stored in `pg_largeobject`.

**Comment by jcoleman** [comment]
Ah, I wasn't aware of that facility.

Thanks for clarifying.
