### ISSUE TITLE
Failed to start PostgreSQL 11.1 with pglogical  2.4.2

### ISSUE THREAD

**Issue by tmiyamon** [2ndQuadrant/pglogical#475]
I installed pglogical 2.4.2 for PostgreSQL 11.1 on CentOS7 and restart it, and then I got the following error and failed to start it.

```
could not load library "/usr/pgsql-11/lib/pglogical.so": /usr/pgsql-11/lib/pglogical.so: undefined symbol: getmissingattr
```

How to solve this problem?

Thank you.

**Comment by nmisch** [comment]
First, update to PostgreSQL 11.22.  PostgreSQL 11.1 has been out of support for over five years.  Does the error still happen with v11.22, or not?

**Comment by tmiyamon** [comment]
Updating to PostgreSQL 11.22 solved this issue. Thank you!
