### ISSUE TITLE
Repositories from enterprisedb "not found"

### ISSUE THREAD

**Issue by aljazvidmar** [2ndQuadrant/pglogical#479]
All repositories for rpm installs are not working

https://techsupport.enterprisedb.com/api/repository/dl/default/release/<version_number>/rpm

response:
"not found"

**Comment by pikkemans** [comment]
The old ones still work

https://access.2ndquadrant.com/api/repository/dl/default/release/<VERSION>/rpm

**Comment by eulerto** [comment]
The installations instructions were updated by efee43f09864b37192d4c63db0911b38321debd2.
