### ISSUE TITLE
Unsuccessful standby replication on PostgreSQL 17

### ISSUE THREAD

**Issue by esiaero** [2ndQuadrant/pglogical#485]
Hi, I tested subscription to a standby with the HEAD of the repo (pglogical 2.4.5, pending release).
I'm noticing pglogical seems to create subscriptions with failover as long as its supported on the node (by checking  catalog).

https://github.com/2ndQuadrant/pglogical/blob/c3507a827e427e1e76baa4b581d644bab929fbb3/pglogical_sync.c#L900-L904

https://github.com/2ndQuadrant/pglogical/blob/c3507a827e427e1e76baa4b581d644bab929fbb3/pglogical_sync.c#L308-L311

But with PG 17, that isn't supported if its a standby.
https://github.com/postgres/postgres/blob/bccca780eef904002512a1a0b5ce617bcb63507b/src/backend/replication/slot.c#L330-L333

So unlike PG 16, now the subscription cannot succeed, with error messages like
```
ERROR:  cannot enable failover for a replication slot created on the standby
...
STATEMENT:  CREATE_REPLICATION_SLOT "pgl_postgres_provider_testsub" LOGICAL pglogical_output (FAILOVER)
```

I was curious if this kind of behavior is expected?

**Comment by eulerto** [comment]
Fixed by commit 8579de3b2557355008ddac13ce05663942eedddf.
