### ISSUE TITLE
Tag 2.4.5 release for PG 17 support

### ISSUE THREAD

**Issue by df7cb** [2ndQuadrant/pglogical#486]
Hi,

I see the version has been bumped to 2.4.5, but there's no git tag for that yet. Could you please add that tag so the Debian packaging machinery can pick up that release?

Thanks!

**Comment by eulerto** [comment]
@df7cb Tag available.

**Comment by devrimgunduz** [comment]
@eulerto seeing these warnings on my Fedora 40 box. Not sure they are harmless or not, so wanted to report here:

> /usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I/usr/pgsql-17/include -I/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/main/non-common/pglogical/main/pglogical-REL2_4_5/compat17 -Werror=implicit-function-declaration -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o pglogical.bc pglogical.c
> In file included from /usr/pgsql-17/include/server/postgres.h:46,
>                  from pglogical_sync.c:14:
> pglogical_sync.c: In function ‘pglogical_sync_subscription’:
> /usr/pgsql-17/include/server/utils/elog.h:387:29: warning: declaration of ‘_save_exception_stack’ shadows a previous local [-Wshadow=compatible-local]
>   387 |                 sigjmp_buf *_save_exception_stack##__VA_ARGS__ = PG_exception_stack; \
>       |                             ^~~~~~~~~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/storage/ipc.h:50:17: note: in expansion of macro ‘PG_TRY’
>    50 |                 PG_TRY()
>       |                 ^~~~~~
> pglogical_sync.c:920:25: note: in expansion of macro ‘PG_ENSURE_ERROR_CLEANUP’
>   920 |                         PG_ENSURE_ERROR_CLEANUP(pglogical_sync_tmpfile_cleanup_cb,
>       |                         ^~~~~~~~~~~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/utils/elog.h:387:29: note: shadowed declaration is here
>   387 |                 sigjmp_buf *_save_exception_stack##__VA_ARGS__ = PG_exception_stack; \
>       |                             ^~~~~~~~~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/storage/ipc.h:50:17: note: in expansion of macro ‘PG_TRY’
>    50 |                 PG_TRY()
>       |                 ^~~~~~
> pglogical_sync.c:911:17: note: in expansion of macro ‘PG_ENSURE_ERROR_CLEANUP’
>   911 |                 PG_ENSURE_ERROR_CLEANUP(pglogical_sync_worker_cleanup_error_cb,
>       |                 ^~~~~~~~~~~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/utils/elog.h:388:39: warning: declaration of ‘_save_context_stack’ shadows a previous local [-Wshadow=compatible-local]
>   388 |                 ErrorContextCallback *_save_context_stack##__VA_ARGS__ = error_context_stack; \
>       |                                       ^~~~~~~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/storage/ipc.h:50:17: note: in expansion of macro ‘PG_TRY’
>    50 |                 PG_TRY()
>       |                 ^~~~~~
> pglogical_sync.c:920:25: note: in expansion of macro ‘PG_ENSURE_ERROR_CLEANUP’
>   920 |                         PG_ENSURE_ERROR_CLEANUP(pglogical_sync_tmpfile_cleanup_cb,
>       |                         ^~~~~~~~~~~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/utils/elog.h:388:39: note: shadowed declaration is here
>   388 |                 ErrorContextCallback *_save_context_stack##__VA_ARGS__ = error_context_stack; \
>       |                                       ^~~~~~~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/storage/ipc.h:50:17: note: in expansion of macro ‘PG_TRY’
>    50 |                 PG_TRY()
>       |                 ^~~~~~
> pglogical_sync.c:911:17: note: in expansion of macro ‘PG_ENSURE_ERROR_CLEANUP’
>   911 |                 PG_ENSURE_ERROR_CLEANUP(pglogical_sync_worker_cleanup_error_cb,
>       |                 ^~~~~~~~~~~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/utils/elog.h:389:28: warning: declaration of ‘_local_sigjmp_buf’ shadows a previous local [-Wshadow=compatible-local]
>   389 |                 sigjmp_buf _local_sigjmp_buf##__VA_ARGS__; \
>       |                            ^~~~~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/storage/ipc.h:50:17: note: in expansion of macro ‘PG_TRY’
>    50 |                 PG_TRY()
>       |                 ^~~~~~
> pglogical_sync.c:920:25: note: in expansion of macro ‘PG_ENSURE_ERROR_CLEANUP’
>   920 |                         PG_ENSURE_ERROR_CLEANUP(pglogical_sync_tmpfile_cleanup_cb,
>       |                         ^~~~~~~~~~~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/utils/elog.h:389:28: note: shadowed declaration is here
>   389 |                 sigjmp_buf _local_sigjmp_buf##__VA_ARGS__; \
>       |                            ^~~~~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/storage/ipc.h:50:17: note: in expansion of macro ‘PG_TRY’
>    50 |                 PG_TRY()
>       |                 ^~~~~~
> pglogical_sync.c:911:17: note: in expansion of macro ‘PG_ENSURE_ERROR_CLEANUP’
>   911 |                 PG_ENSURE_ERROR_CLEANUP(pglogical_sync_worker_cleanup_error_cb,
>       |                 ^~~~~~~~~~~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/utils/elog.h:390:22: warning: declaration of ‘_do_rethrow’ shadows a previous local [-Wshadow=compatible-local]
>   390 |                 bool _do_rethrow##__VA_ARGS__ = false; \
>       |                      ^~~~~~~~~~~
> /usr/pgsql-17/include/server/storage/ipc.h:50:17: note: in expansion of macro ‘PG_TRY’
>    50 |                 PG_TRY()
>       |                 ^~~~~~
> pglogical_sync.c:920:25: note: in expansion of macro ‘PG_ENSURE_ERROR_CLEANUP’
>   920 |                         PG_ENSURE_ERROR_CLEANUP(pglogical_sync_tmpfile_cleanup_cb,
>       |                         ^~~~~~~~~~~~~~~~~~~~~~~
> /usr/pgsql-17/include/server/utils/elog.h:390:22: note: shadowed declaration is here
>   390 |                 bool _do_rethrow##__VA_ARGS__ = false; \
>       |                      ^~~~~~~~~~~
> /usr/pgsql-17/include/server/storage/ipc.h:50:17: note: in expansion of macro ‘PG_TRY’
>    50 |                 PG_TRY()
>       |                 ^~~~~~
> pglogical_sync.c:911:17: note: in expansion of macro ‘PG_ENSURE_ERROR_CLEANUP’
>   911 |                 PG_ENSURE_ERROR_CLEANUP(pglogical_sync_worker_cleanup_error_cb,
>       |                 ^~~~~~~~~~~~~~~~~~~~~~~
>

**Comment by df7cb** [comment]
Thanks!

I'm seeing the same compiler warnings, but regression tests are passing. (The TAP tests are still broken, TestLib.pm was removed in PG15.)
