### ISSUE TITLE
how is data changes handled during initial data synchronization?

### ISSUE THREAD

**Issue by carolfly86** [2ndQuadrant/pglogical#52]
We aim to do online upgrade from 9.4 to 9.5 with pglogical. Our tables are quite large (37GB), and take over 1hr to synchronize with SELECT pglogical.replication_set_add_all_tables('default', ARRAY['public'], true); 

Will the data changes made during the synchronize process be missing from subscriber? If it is,  is there a way to ensure those changes are carried over to subscriber?

**Comment by ringerc** [comment]
It's handled automatically by the snapshot exported during replication slot
creation, so long as you get pglogical to handle schema and data sync.

Please don't use this bug tracker for general questions. Use the
pglogical/bdr mailing list/forum at pglogical-list@2ndquadrant.com /
https://groups.google.com/a/2ndquadrant.com/forum/#!forum/bdr-list . This
github tracker is for bug reports and feature requests only.

**Comment by ringerc** [comment]
It's handled automatically by the snapshot exported during replication slot creation, so long as you get pglogical to handle schema and data sync.

Please don't use this bug tracker for general questions. Use the pglogical/bdr mailing list/forum at pglogical-list@2ndquadrant.com / https://groups.google.com/a/2ndquadrant.com/forum/#!forum/bdr-list . This github tracker is for bug reports and feature requests only.
