### ISSUE TITLE
README: Make it clear whether pglogical uses synchronous or asynchronous replication

### ISSUE THREAD

**Issue by afiskon** [2ndQuadrant/pglogical#55]
I believe it's asynchronous but currently it's not clear from README.md.

**Comment by PJMODOS** [comment]
It uses whatever synchronous_standbys and synchronous_commit specify.

**Comment by afiskon** [comment]
@PJMODOS I see. I suggest to add this to README. It's not obvious at all.

**Comment by PJMODOS** [comment]
This will be documented in 2.0.
