### ISSUE TITLE
Unable to configure pglogical (bug or confusing documentation)

### ISSUE THREAD

**Issue by afiskon** [2ndQuadrant/pglogical#56]
There are way too many things that are not clear. You can find all details in this discussion: http://stackoverflow.com/questions/40345862/postgresql-difficulties-with-basic-pglogical-configuration

**Comment by afiskon** [comment]
Depesz published an excellent blog post about pglogical configuration https://www.depesz.com/2016/11/08/major-version-upgrading-with-minimal-downtime/

**Comment by ringerc** [comment]
We would welcome pull requests with enhancements to the documentation.

**Comment by afiskon** [comment]
@ringerc I would be happy to send such a pull request, but first I have to figure out how to configure pglogical myself. I was trying for 3 days already and still didn't succeeded, even after Depesz published a blog post. As far as I know currently pglogical just doesn't work. Here is exactly what I'm doing.

## Preparetion

I'm using VirtualBox VM's, guest system is Arch Linux. You can download an image here:

https://dl.dropboxusercontent.com/u/19923518/temp/archlinux-src.ova

MD5: d3d498cd2ca34421744fdedfb8f9afa9

SSH login:password are eax:killkim22 - it's a sudoer.

I personally use this CLI tool for managing VM's https://github.com/afiskon/py-vm It automatically joins VM's in 10.128.0.0/16 network and has various other advantages over VBoxManage and Vagrant.

From this base VM I created two VM's - archlinux1 (provider, 10.128.0.11) and archlinux2 (subscriber, 10.128.0.12).  

## Steps to reproduce

(1) Install PostgreSQL (in my case it was 9.5.4):

```
sudp pacman -Sy
sudo pacman -S postgresql
```

(2) Build pglogical from source code (I tried `master` and `REL1_2_1` - reproduces on both):

```
sudo pacman -S git
sudo pacman -S --needed base-devel
git clone https://github.com/2ndQuadrant/pglogical.git
cd pglogical
make USE_PGXS=1
sudo make install
```

(3) On *both* provider and subscriber:

```
sudo -u postgres initdb -D /var/lib/postgres/data
```

Edit /var/lib/postgres/data/postgresql.conf:

```
# change IP on subscriber
listen_addresses = 'localhost,10.128.0.11'
wal_level = logical
shared_preload_libraries = 'pglogical'
max_worker_processes = 16
max_wal_senders = 16
max_replication_slots = 16
track_commit_timestamp = on
log_min_messages = debug3
```

Add to /var/lib/postgres/data/pg_hba.conf:

```
local   replication     all                                trust
host    replication     all        127.0.0.1/32            trust
host    replication     all        ::1/128                 trust

# change IP on subscriber (AFAIK it actually doesn't matter - but I was desperate)
host    all    all    10.128.0.11/16    trust
host    replication     all        10.128.0.11/16            trust
```

Start PostgreSQL:

```
sudo systemctl enable postgresql
sudo systemctl start postgresql
```

Create user and database:

```
sudo -u postgres createuser -s --replication -P eax
sudo -u postgres createdb -O eax eax
```

Run `psql` as user eax and execute:

```
create extension pglogical;
```

On this point both provider and subscriber have user, database, and enabled pglogical.

(4) On provider:

```
create table test (k serial primary key, v text);

insert into test (v) values ('aaa');

select pglogical.create_node(
  node_name := 'provider',
  dsn := 'host=10.128.0.11 port=5432 user=eax dbname=eax'
);

select pglogical.create_replication_set('replication_set');

select pglogical.replication_set_add_table(
  set_name := 'replication_set',
  relation := 'test',
  synchronize_data := true
);
```

(5) On subscriber:

```
create table test (k serial primary key, v text);

select pglogical.create_node(
  node_name := 'subscriber',
  dsn := 'host=10.128.0.12 port=5432 dbname=eax user=eax'
);

select pglogical.create_subscription(
  subscription_name := 'subscription',
  replication_sets := array['replication_set'],
  provider_dsn := 'host=10.128.0.11 port=5432 dbname=eax user=eax'
);
```

## Expected behavior

Table `test` is sucessfuly replicating from provider to subscriber.

## Actual behavior

Table `test` is empty on subscriber, even after executing new queries on provider. Nothing helpful in logs (`journalctl -u postgresql -f` - note that `log_min_messages = debug3`).


Am I doing something wrong or it's a bug? Naturally there is no firewall involved or anything like this. I would  be happy to provide any additional debug information you might need.

**Comment by john5000** [comment]
The logs should be showing something.  The `journalctl` command does not necessarily show the postgres logs, so you won't see the postgres errors and diagnostic message with that. Instead, try looking for the logs in under: /var/log/postgresql/

Also, I've not seen much covering status checks and diagnostics, but here are commands I've found and use to check things:

**On the Provider:**
`
    select * from pg_replication_slots; 
`
This should show the a record as soon as the subscription is started. Also, this is how you can tell who is subscribing and to what replication sets.  The "active" field should be "true".

**On the subscriber:**

Check the overall replication status from the subscriber.
`
    select * from pglogical.show_subscription_status();
`

Check the status of each of the tables (status should be "r" = Ready)
`
    select * from pglogical.local_sync_status;
`

**Comment by PJMODOS** [comment]
I would guess this is probably bug which was fixed in upcoming version of pglogical. Try `REINDEX pglogical.local_node;` after creating the node for workaround.

**Comment by PJMODOS** [comment]
Or upgrade to 1.2.2
