### ISSUE TITLE
Still having issues getting pglogical compiled on Gentoo 

### ISSUE THREAD

**Issue by bryanconlon** [2ndQuadrant/pglogical#6]
Additional info requested in closed issue:

**pglogical version?**
1.1.0

**make command?**
GNU Make 4.1
Built for x86_64-pc-linux-gnu

**PATH environment version?**
Not sure how to find this.  Gentoo version is 4.0.5-gentoo.

**How PostgreSQL was installed from where?**

Installed via emerge and package name dev-db/postgresql-9.4.4:9.4

**pgxs should be ensuring that the PostgreSQL libraries are on the linker path, assuming you compiled with USE_PGXS=1. If you didn't you'd get errors like in #1 . So I have to guess you've done something different, possibly using some Gentoo packaging or script.**

When I stall this with USE_PGXS=1 I get the following error:

Makefile:127: ../../src/Makefile.global: No such file or directory
Makefile:128: /contrib/contrib-global.mk: No such file or directory
make: *** No rule to make target '/contrib/contrib-global.mk'.  Stop.

Took advice in article to get passed this error:  http://blog.pgxn.org/post/20908326485/lose-use-pgxs

and then got error:

86_64-pc-linux-gnu-gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -march=native -O2 -pipe -fpic pglogical_create_subscriber.o pglogical_fe.o -L/usr/lib64/postgresql-9.4/lib64 -Wl,-O1 -Wl,--as-needed  -Wl,--as-needed -Wl,-rpath,'/usr/lib64/postgresql-9.4/lib64',--enable-new-dtags -Wl,-O1 -Wl,--as-needed -L/usr/lib64/postgresql-9.4/lib64 -lpgcommon -lpgport -L/usr/lib64/postgresql-9.4/lib64 -lpq -lpgcommon -lpgport -lxslt -lxml2 -lpam -lssl -lcrypto -lz -lreadline -lrt -lcrypt -ldl -lm  -o pglogical_create_subscriber
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lpgcommon
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lpgport
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lpgcommon
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lpgport
collect2: error: ld returned 1 exit status
Makefile:73: recipe for target 'pglogical_create_subscriber' failed
make: *** [pglogical_create_subscriber] Error 1

Thanks,

Bryan

**Comment by ringerc** [comment]
Running with

   make USE_PGXS=1

should be fine. The article you linked to is telling people not to make the
Makefile require that, but the pglogical one does since it's intended to be
compiled inside the PostgreSQL source tree as well as stand-alone.

When you say you "took advice in article" ... did you edit the Makefile?
Can you show the new one you created, if so?

What is the output of

    which pg_config

and

    pg_config

?


-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by bryanconlon** [comment]
output which pg_config:  /usr/bin/pg_config

output pg_config:

pg_config
BINDIR = /usr/lib64/postgresql-9.4/bin
DOCDIR = /usr/share/doc/postgresql-9.4.4
HTMLDIR = /usr/share/doc/postgresql-9.4.4
INCLUDEDIR = /usr/include/postgresql-9.4
PKGINCLUDEDIR = /usr/include/postgresql-9.4
INCLUDEDIR-SERVER = /usr/include/postgresql-9.4/server
LIBDIR = /usr/lib64/postgresql-9.4/lib64
PKGLIBDIR = /usr/lib64/postgresql-9.4/lib64
LOCALEDIR = /usr/lib64/postgresql-9.4/share/locale
MANDIR = /usr/share/postgresql-9.4/man
SHAREDIR = /usr/share/postgresql-9.4
SYSCONFDIR = /etc/postgresql-9.4
PGXS = /usr/lib64/postgresql-9.4/lib64/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/usr' '--build=x86_64-pc-linux-gnu' '--host=x86_64-pc-linux-gnu' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--datadir=/usr/share' '--sysconfdir=/etc' '--localstatedir=/var/lib' '--libdir=/usr/lib64/postgresql-9.4/lib64' '--prefix=/usr/lib64/postgresql-9.4' '--datadir=/usr/share/postgresql-9.4' '--docdir=/usr/share/doc/postgresql-9.4.4' '--includedir=/usr/include/postgresql-9.4' '--mandir=/usr/share/postgresql-9.4/man' '--sysconfdir=/etc/postgresql-9.4' '--with-system-tzdata=/usr/share/zoneinfo' '--enable-integer-datetimes' '--enable-thread-safety' '--without-gssapi' '--without-ldap' '--with-pam' '--with-perl' '--with-python' '--with-readline' '--with-openssl' '--without-tcl' '--with-uuid=e2fs' '--with-libxml' '--with-libxslt' '--with-zlib' '--enable-nls=en' 'build_alias=x86_64-pc-linux-gnu' 'host_alias=x86_64-pc-linux-gnu' 'CFLAGS=-march=native -O2 -pipe' 'LDFLAGS=-Wl,-O1 -Wl,--as-needed' 'LDFLAGS_EX=-Wl,-O1 -Wl,--as-needed' 'LDFLAGS_SL=-Wl,-O1 -Wl,--as-needed'
CC = x86_64-pc-linux-gnu-gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -march=native -O2 -pipe
CFLAGS_SL = -fpic
LDFLAGS = -L../../../src/common -Wl,-O1 -Wl,--as-needed -Wl,--as-needed -Wl,-rpath,'/usr/lib64/postgresql-9.4/lib64',--enable-new-dtags
LDFLAGS_EX = -Wl,-O1 -Wl,--as-needed
LDFLAGS_SL = -Wl,-O1 -Wl,--as-needed -Wl,-O1 -Wl,--as-needed -Wl,-O1 -Wl,--as-needed -Wl,-O1 -Wl,--as-needed -Wl,-O1 -Wl,--as-needed
LIBS = -lpgcommon -lpgport -lxslt -lxml2 -lpam -lssl -lcrypto -lz -lreadline -lrt -lcrypt -ldl -lm
VERSION = PostgreSQL 9.4.4

**Comment by bryanconlon** [comment]
Commented lines in Makefile to get it past error:

#ifdef USE_PGXS
...q
# In-tree builds only
#subdir = contrib/pglogical
#top_builddir = ../..
#include $(top_builddir)/src/Makefile.global
#include $(top_srcdir)/contrib/contrib-global.mk
...
#endif

**Comment by bryanconlon** [comment]
My manager took a look and he had to recompile PostgreSQL with static libraries to get it to work.  Also had to comment out a couple of lines in makefile:

#include $(top_builddir)/src/Makefile.global
#include $(top_srcdir)/contrib/contrib-global.mk

**Comment by PJMODOS** [comment]
All you described just means you didn't run the make with USE_PGXS=1 as is documented. I think that now that pglogical won't be submitted for core in this form, we should remove the need to specify this though.

**Comment by PJMODOS** [comment]
And done.
