### ISSUE TITLE
Minor points to fix

### ISSUE THREAD

**Issue by john5000** [2ndQuadrant/pglogical#62]
1) Typo in prototype in [pglogical_hooks.c](https://github.com/2ndQuadrant/pglogical/blob/bbe616044e32a77cb5cc23a1a8c2cf3d77f4e7a3/pglogical_hooks.c#L48)
The "pglogical_hooks_setupn" -- should be "pglogical_hooks_setup"
This fix is needed when compiling on Windows. (Btw, no problems running pglogical under Windows Postgres, but there are a few other Windows specific declarations/prototypes needed.)

2) Missing return statement in pglogical_apply.c after the cleanup code that is mid handle_insert().  See [pglogical_apply.c](https://github.com/2ndQuadrant/pglogical/blob/bbe616044e32a77cb5cc23a1a8c2cf3d77f4e7a3/pglogical_apply.c#L561).

**Comment by PJMODOS** [comment]
Good catches, thanks, fixed.
