### ISSUE TITLE
Upgrade from 1.0.1 to 1.2.1 fails

### ISSUE THREAD

**Issue by carbonin** [2ndQuadrant/pglogical#65]
I upgraded the pglogical package to the latest version and attempted to update the extension online.

```sql
vmdb_development=# alter extension pglogical update to '1.2.1';
ERROR:  could not find function "pglogical_alter_node_add_interface" in file "/usr/pgsql-9.5/lib/pglogical.so"
```

After I restart the database server the extension seems to be upgraded:
```sql
vmdb_development=# select * from pg_extension ;
  extname  | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition 
-----------+----------+--------------+----------------+------------+-----------+--------------
 plpgsql   |       10 |           11 | f              | 1.0        |           | 
 pglogical |    16385 |      5227096 | f              | 1.2.1      |           | 
(2 rows)
```

Is there a step that I missed or do I have to restart the server to upgrade properly?

**Comment by carbonin** [comment]
I imagine this has something to do with the old `.so` still being in memory when I run the `ALTER EXTENSION` because I ran the `yum upgrade` while the server was running.

If so, I guess this is unavoidable?

**Comment by PJMODOS** [comment]
Yes, it's unavoidable, the extension itself with upgrade automatically, but the library reload requires restart yes.

**Comment by carbonin** [comment]
Thanks @PJMODOS
