### ISSUE TITLE
Feature request: Record update could do insert if missing

### ISSUE THREAD

**Issue by john5000** [2ndQuadrant/pglogical#67]
When the subscriber gets an update record, and the record to be updated does not exist, the current logic just ignores the update.  See logic in [pglogical_apply.c, line 822](https://github.com/2ndQuadrant/pglogical/blob/REL1_2_STABLE/pglogical_apply.c#822).

Here is the comment from the code:

		 * The tuple to be updated could not be found.
		 * We can't do INSERT here because we might not have whole tuple.

But the code I've seen for sending updates looks like we do have the whole tuple, so the insert could be done.  

To prove this out, I made the changes in my copy so that it would do an insert (basically, calling the handle_insert logic after the PushActiveSnapshots) and it works well.

This has several uses:

- This is useful when you need to sync few records and not the whole table.
- In some cases a table sync command is not possible, but by doing an update on each record (with no actual changes), you can sync the whole table.
- Lets you do a table sync type action where the subscriber table does not have to be truncated.

**Comment by PJMODOS** [comment]
It might not have whole tuple if there is TOASTed value in the tuple that wasn't changed as those are not sent.

**Comment by ringerc** [comment]
As @PJMODOS says we'd have to force sending of unchanged TOASTed attributes unconditionally to make this work, which would be terrible for normal performance especially with big attributes. Or we'd need a way to talk back to the master to ask for them ... and have a full round trip *per tuple*. Making it vaguely workable would require us to deTOAST the attributes on the walsender side and cache them until the txn is confirmed applied, so the receiver could ask us for them asynchronously.

This *only affects setups with multiple subscriptions, or where the downstream also receives direct writes*. It can't cause a problem for single-master replication, unless you're doing things like you are attempting with sync.

I don't think this is the right answer for sync. Closing.
