### ISSUE TITLE
worker registration failed

### ISSUE THREAD

**Issue by fluancefg** [2ndQuadrant/pglogical#7]
Hello,

I'm trying to setup pglogical with an initial synchronization of structure and data. Following the [quick setup](https://github.com/2ndQuadrant/pglogical) part of the documentation, the advice to configure max_worker_processes parameter is # one per node needed on subscriber node.
I have two nodes on the subscriber side and max_worker_processes = 4, but I still get an error during initial replication:
`ERROR:  worker registration failed, you might want to increase max_worker_processes setting`
`LOG: pglogical supervisor exited with code 1`
`LOG:  starting pglogical supervisor`

**Comment by PJMODOS** [comment]
This can happen in situation when you have many database in one postgres instance but only replicate few of them, workaround is to increase the max_worker_processes.

**Comment by fluancefg** [comment]
Ok, but in that case, how can I know how many max_worker_processes I should set ?
And does it affect max_replication_slots and max_wal_senders, too ?

**Comment by PJMODOS** [comment]
There is one worker needed for the main mainternance process, one per subscription, one per replicated database and during startup it can need one per any connectable database on top of that. It does not affect slots or wal senders.

**Comment by fluancefg** [comment]
Ok, I'm going to follow that rule.
Thanks
