### ISSUE TITLE
Custom update on slaves

### ISSUE THREAD

**Issue by aligit** [2ndQuadrant/pglogical#71]
I'm very new to replication and I apologize in advance if this is not the right place.

Is there a way to run custom sql scripts when replicating into slaves like updating rows containing sensitive data by making them anonymous?

Thanks

**Comment by jfinzel** [comment]
You can use triggers, then enable the trigger to fire during replication with:
`ALTER TABLE foo ENABLE REPLICA TRIGGER footrigger;`
https://www.postgresql.org/docs/9.6/static/sql-altertable.html

Bear in mind you will pay a slight performance penalty for that.
