### ISSUE TITLE
MERGE REPLICATION:  Table doesn't merge.  It replaces it.

### ISSUE THREAD

**Issue by bradleyf** [2ndQuadrant/pglogical#80]
Hi:  

Two separate providers.  Same table structure, different table data and different PK's.  One subscriber.

Upon subscribe to provider1, table is replicated to match provider1.   Upon subscribe to provider 2, table is replicated to match provider2.    NO MERGE.

Upon resynchronize_table with provider 1,  table is replicated to match provider 1.  NO MERGE.
Upon resynchronize_table with provider 2,  table is replicated to match provider 2.  NO MERGE.

**Comment by PJMODOS** [comment]
Can't reproduce the subscription issue. Please share something reproducible.

The resynchronize_table() function behaves as documented (first truncates the table, this will be optional in 2.0, but still true by default).

**Comment by bradleyf** [comment]
I can repro every time.  Simple table with 18 records.  happens again and again.    I can show you via teamviewer if you wish.   Let me know.

**Comment by bradleyf** [comment]
Now the same is happening on another table.   Resync clears the table and overlays the data.

C'mon now, there must be a better way to troubleshoot this!  Please make a suggestion....

**Comment by bradleyf** [comment]
Ok.  I figured it out.  

Duplicate data rows were in pglogical.replication_set_relation, as well as in pglogical.queue.

Also, after dropping a replication set, data rows for that set remain in pglogical.queue.

Clearing out these pglogical tables and then starting over cured the problem.

Folks.  Fix your data deletion and please, please change pglogical tables to use primary keys.

Thanks.

**Comment by PJMODOS** [comment]
Data deletion has nothing to do with this. Existing data in queue don't affect anything, the changes are applied when INSERT to that table is replicated so that definitely wasn't the cause. That table should definitely **not** have primary key as there is nothing unique in it.
