### ISSUE TITLE
PGLogical parsing error on timestamp with time zone column followed by json column

### ISSUE THREAD

**Issue by bradleyf** [2ndQuadrant/pglogical#81]
PGLogical parses a table row with timestamp with time zone column followed by json column improperly and yields the following log entries:

-------------------------------------

 starting sync of table xxx_log for subscriber aaa
2017-03-20 22:07:05 UTC [22972-1]  ERROR:  invalid input syntax for type json
2017-03-20 22:07:05 UTC [22972-2] DETAIL:  Token "-02" is invalid.
2017-03-20 22:07:05 UTC [22972-3] CONTEXT:  JSON data, line 1: 2017-02...
        COPY xxx_log, line 1, column comments: "2017-02-12 17:22:19.433663
-05"
2017-03-20 22:07:05 UTC [22972-4]  STATEMENT:  COPY "public"."xxx_log" FROM stdin
2017-03-20 22:07:22 UTC [22971-2] LOG:  pglogical sync finished processing; replayed to 3/
26FBEEA0 of required 3/26FBEEA0
2017-03-20 22:07:23 UTC [22971-3] LOG:  finished sync of table public.xxx_log

========================

The main thing wrong here is that in the actual data a "timestamp with time zone" column called "disposition_dt"  has the value of 2017-02-12 17:22:19.433663-05".   THAT column is followed by a json column called "comments" with a NULL value.

So, the error message is obviously describing a parsing error.     I also noticed other issues with it parsing json and jsonb columns alongside others.  

Please fix!

**Comment by PJMODOS** [comment]
This has nothing to do with timestamps and json. It's known limitation of pglogical 1.2 and older where initial COPY can't handle different order of columns. This will be fixed in upcoming 2.0 so closing.

**Comment by bradleyf** [comment]
Ah.   Different ordered columns between publisher and subscriber.   That I can fix and try again.   

What timeframe is 2.,0 expected?

**Comment by bradleyf** [comment]
Ok, I reordered the columns on the subscriber and the parsing error is gone.  However, merge replication isn't working.  See issue 80.
