### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by jamessewell** [2ndQuadrant/pglogical#83]
Hi, this is a question about using pglogical in an HA setup.

I have two PostgreSQL HA clusters, A and B. 

Both consist of two PostgreSQL nodes, with the master being identified by a virtual IP (VIP) address which is moved during failover.

I want to push a subset of data from cluster A to cluster B using logical replication - but I can't find any solid information about failure cases.

My main questions are (assuming pglogical is configured on all 4 nodes).

1. When A(master) fails and the VIP is moved do I need to take action on `A(promoted_master)` and `B(master)` before logical replication continues? 
2. When `B(master)` fails do I need to take action on `B(promoted_master)` and `A(master)` before replication continues?
3. In both of these cases what is my window for data loss above the normal streaming sync replication losses.

Cheers,
James

**Comment by jfinzel** [comment]
This isn't an issue, it's a question and I think should be closed.

1. If you failover with the same IP, you need to 2 things:
- Verify you don't have unconsumed changes in the replication slot and
- Recreate the same replication slots on the failed master with `pg_create_logical_replication_slot('slot_name','pglogical_origin');`

Then it should just work.  If you have a different IP/port you would need to alter the subscription interface.

2. Exact same process.
3. Not sure I understand the question.  You can view unconsumed changes on a disabled replication slot with `pg_logical_slot_peek_changes` on the provider.

**Comment by jamessewell** [comment]
Happy to close as a question - there doesn't seem to be anywhere else to ask pglogical questions at the moment. Reading back one thing I didn't explain well was I'm using streaming replication from A1->A2 and B1->B2

In the case above the original provider is dead, so I can't peek changes.

It seems that as you can't replicate logical slot data to a physical standby logical replication can't be used effectively when streaming replication is being used as well.

Hopefully failover slots or later focal replication on standbys or some variant gets into 11!

**Comment by jfinzel** [comment]
Okay, thanks for the clarification.  Regarding your statement:

> It seems that as you can't replicate logical slot data to a physical standby logical replication can't be used effectively when streaming replication is being used as well.

I'm not sure what you mean here because we have in fact successfully used this setup:
provider -> provider streamer
 - subscriber -> subscriber streamer

We can do a failover in above scenario successfully for either the provider or subscriber.  That is, provider can fail to provider streamer given intervention mentioned above.  Subscriber can fail to subscriber streamer with actually no intervention needed.

If the provider is dead, you may be able to figure out if subscriber has up to date data by comparing LSN numbers from the system tables.  However I haven't tried that.

**Comment by jamessewell** [comment]
Hey,

The issue is really that when the provider fails to the provider streamer
we lose any data which is queued in the (lost) provider slot.

This can be made worse by the fact logical replication seems to be serial
(correct me if I'm wrong here?) so if I have xid 10 running at failure time
any changes made by xid > 10 will be lost.

This seems to be the problem Craig was trying to fix with 'Failover Slots'
<https://commitfest.postgresql.org/9/488/>, and then with 'Logical Decoding
on Standby'
<https://www.postgresql.org/message-id/CAMsr+YEVmBJ=dyLw=+kTihmUnGy5_EW4Mig5T0maieg_Zu=XCg@mail.gmail.com>
.

Anyway - looks like the only solution today is to accept these losses and:

   1. Force connection from Sub -> Pub via the VIP address using routing
   rules (we need the Pub to be sending to the Sub VIP, not the Sub primary IP)
   2. Implement slot creation in the tool used for failover

I would ask if pglogical could handle slot creation on promotion - but I'm
guessing with the logical work in 10 pglogical isn't getting new features
currently?

Cheers,
