### ISSUE TITLE
Where is everyone?

### ISSUE THREAD

**Issue by JakeSummers** [2ndQuadrant/pglogical#86]
Hello!

Is there a more up to date repository for Pglogical?  This repo had pretty regular commits until Jan 24, 2017.  Since then there haven't been any changes.  Where is everyone?

Is there a more up to date repository somewhere?  

The reason I am asking, is that I am interested in the fixes that are dicussed on this thread:

https://www.postgresql.org/message-id/AT5PR84MB0084FAE5976D89CDE9733093EE4A0%40AT5PR84MB0084.NAMPRD84.PROD.OUTLOOK.COM

Thanks!

**Comment by PJMODOS** [comment]
We just released 2.0.

**Comment by JakeSummers** [comment]
Is there a separate repo that I can follow changes on?
