### ISSUE TITLE
`synchronize_structure` tries to create extensions

### ISSUE THREAD

**Issue by thedumbtechguy** [2ndQuadrant/pglogical#87]
I find that when I use `synchronize_structure`, it fails. This actually caused me a ton of headache trying to find the problem as I did everything else perfectly.

The problem is, the provider creates some foreign data wrappers using `tds_fdw`. The subscriber is interested in the data from particular tables.
I used `pglogical.replication_set_add_table` to specify each of these tables.

However, I find that when I create the subscription, rather than only create the structure of the tables in the replication set, it attempts to do much more. I'm not very sure how much more, but I can confirm that it tries to create extensions.

I'm not sure this is intended behavior and I believe it is due to the underlying mechanism used in the copy.

**Comment by PJMODOS** [comment]
That's by (current) design, synchronize_structure copies everything.

**Comment by thedumbtechguy** [comment]
Is it possible to document it? 
Synchronize in the context of a replication set seems to imply it replicates just the tables in the set.
