### ISSUE TITLE
PGLogical slave crush loop

### ISSUE THREAD

**Issue by thealexparshin** [2ndQuadrant/pglogical#9]
The setup:
- Two PG instances are setup on the same host, with different port numbers and data directories.
- The streaming replication is setup from one instance to another.
The problem:
- While at streaming replication, we create a table 'xxx' and call pg_switch_xlog(), then slave instance is promoted, master/slave have pglogical nodes created, etc to have working pglogical replication.
We test data replication and delays - all is working.
The two different results we get are:
1) The 'xxx' table doesn't exist on slave - but nothing crushes. Understood, we need a delay.
OR
 2) The 'xxx' table does exist on slave, but if we try inserting anything into the 'xxx' table, slave goes into crush-start-crush.. infinite loop.
Both cases are prevented with a delay before calling pg_switch_xlog() until 'xxx' table is detected on the slave. However, it would be nice replacing crush loop with an error message of some kind, suggesting something.

**Comment by ringerc** [comment]
Versions?

Error messages?

Commands run?

**Comment by thealexparshin** [comment]
Craig,

I've spent the whole day yesterday trying to reproduce that behaviour.
Unfortunately, I can't.
I do know what trigerred it, though: We are starting from stream
replication, then modifying master's configuration to add preload pglogical
and restarting master.
Right after master restart, we are creating a table for lag test, and then
promoting the slave and continue with pglogical replication setup.
The problem is, that slave is temporary disconnected during master restart,
and connect only after few seconds delay, and sometimes slave gets the lag
test table changes, and sometimes it doesn't. By adding a delay after
creating lag test table, I was able reliably reproduce it. But the Friday's
problem, when slave gets the lag table, but crashes if you do anything with
it - I can't reproduce any more :(

I now think that this problem is not directly related to pglogical.

Just in case, I'm attaching the script as extracted from our Java code,
with PG config it uses.


Regards,
Alexey Parshin

On 3 June 2016 at 16:36, Craig Ringer <notifications@github.com> wrote:

> Versions?
>
> Error messages?
>
> Commands run?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/2ndQuadrant/pglogical/issues/9#issuecomment-223502278>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHNq9ZRIHCYr9PnYe10Q2__JMiZL2lPIks5qH8uJgaJpZM4ItNKl>
> .
>

# Localization
datestyle = 'iso, dmy'
lc_messages = 'C'                      # locale for system error message
lc_monetary = 'C'                      # locale for monetary formatting
lc_numeric = 'C'                       # locale for number formatting
lc_time = 'C'                          # locale for time formatting

client_min_messages = warning

autovacuum_freeze_max_age = 2000000000
track_activity_query_size = 10240
max_prepared_transactions = 10

listen_addresses = '*'          # what IP address(es) to listen on

################################################
# Query planner tuning (permanent)
default_statistics_target = 200                 # range 1-10000
#constraint_exclusion = partition               # on, off, or partition
#cursor_tuple_fraction = 0.1                    # range 0.0-1.0
from_collapse_limit = 8
join_collapse_limit = 8                         # 1 disables collapsing of explicit JOIN clauses

geqo = off
geqo_threshold = 12
enable_hashagg = off

cpu_tuple_cost = 0.05
random_page_cost = 1.5
seq_page_cost = 1.0


################################################
# Performance tuning (permanent)
checkpoint_completion_target = 0.9
checkpoint_timeout = 5min
full_page_writes = off
wal_buffers = 1024MB
wal_sync_method = fdatasync
effective_io_concurrency = 10
fsync = on
synchronous_commit = off
archive_timeout = 10min

################################################
# Set more optimistic lock timeout
lock_timeout = 30s

# Master server mode (backup and replication)
archive_mode = on
wal_keep_segments = 512
hot_standby = off
max_wal_senders = 3
max_standby_archive_delay = 600s
max_standby_streaming_delay = 600s
wal_level = logical


statement_timeout = 4h
temp_file_limit = 100GB


################################################
# Accomodating different PostgreSQL versions

unix_socket_directories = '/tmp,/var/run/postgresql'
timezone = 'Australia/Melbourne'
log_timezone = 'Australia/Melbourne'

###############################################
# PostgreSQL 9.5 and up:

max_wal_size = 2GB
max_replication_slots = 20
max_worker_processes = 20
shared_preload_libraries = 'pglogical'


###############################################
# Memory-related settings that are depending on available RAM:

effective_cache_size = 925MB
maintenance_work_mem = 76MB
work_mem = 76MB
shared_buffers = 615MB
wal_buffers = 76MB
max_connections = 100
