### ISSUE TITLE
Can't upgrade to 2.0 when using 1.2.2

### ISSUE THREAD

**Issue by fluancefg** [2ndQuadrant/pglogical#90]
Hi,

Yesterday evening I have updated the packages on our prod servers and I discovered that there's a new version of pglogical.
However, I had the bad surprise to see that it does not work if there was version 1.2.2 installed before. I get the following message:
`2017-05-04 19:35:58 CEST [2624-2] ERROR:  extension "pglogical" has no update path from version "1.2.2" to version "2.0.0"`
`2017-05-04 19:35:58 CEST [2624-3] LOG:  manager worker [2624] at slot 0 generation 30 crashed`

Indeed, there's no script pglogical--1.2.2--2.0.0.sql

Is there any particular reason why there's no script to upgrade from 1.2.2 to 2.0 ? Is there another procedure to upgrade ?

Thx

**Comment by PJMODOS** [comment]
Fixed in upcoming 2.0.1 and REL2_0_STABLE code branch.
