### ISSUE TITLE
Table with column name "group" will crash in version 2.0.0

### ISSUE THREAD

**Issue by tvarsis** [2ndQuadrant/pglogical#94]
As title say. After upgrading to 2.0.0 it kept crashing on a table with a column named group. After I renamed the column, it started working again.

**Comment by awesinine** [comment]
this is for any keyword

**Comment by tvarsis** [comment]
Maybe, but it worked in earlier versions and should probably be escaped.

**Comment by a-parser** [comment]
also for "default", "limit" and etc.. please fix it

**Comment by PJMODOS** [comment]
And any other keyword, fixed in REL2_0_STABLE branch and soon to be released 2.0.1.
