### ISSUE TITLE
after alter table add column, delete replication error

### ISSUE THREAD

**Issue by qq363960630** [2ndQuadrant/pglogical#95]
**1 . on master**
create table tb1(a int primary key,b varchar(100)); 
insert into tb1 values(1,'A'); 
create extension pglogical; 
select pglogical.create_node( 
   node_name := 'MastNode1', 
   dsn := 'host=192.168.8.219 port=54321 dbname=test'); 
select pglogical.create_replication_set( 
   set_name := 'RepSet1', 
   replicate_insert := true, 
   replicate_update := true, 
   replicate_delete := true, 
   replicate_truncate := true); 
select pglogical.replication_set_add_table( 
   set_name := 'RepSet1', 
   relation := 'public.tb1', 
   synchronize_data := true, 
   row_filter := 'a > 1'); 
**2. on slave**
create table tb1(a int primary key,b varchar(100)); 
create extension pglogical; 
select pglogical.create_node( 
   node_name := 'SlaveNode1', 
   dsn := 'host=192.168.8.220 port=54221 dbname=test'); 
select pglogical.create_subscription( 
   subscription_name := 'sub1', 
   provider_dsn := 'host=192.168.8.219 port=54321 dbname=test user=system', 
   replication_sets := '{RepSet1}', 
   synchronize_structure := false, 
   synchronize_data := true, 
   forward_origins := '{all}'); 

**3. on master** 
alter table tb1 add c int; 
select pglogical.replication_set_remove_table( 
   set_name := 'RepSet1', 
   relation := 'public.tb1'); 
select pglogical.replication_set_add_table( 
   set_name := 'RepSet1', 
   relation := 'public.tb1', 
   synchronize_data := true, 
   row_filter := 'c > 1'); 
**4. on slave** 
alter table tb1 add c int; 

**5. on master** 
insert into tb1 values(2,'B',2); 
delete from tb1 where c>1; 
6. on slave 
select * from tb1; 

hope result： 
test=# select * from tb1;         
a | b | c 
---+---+--- 
(0 rows) 
realy result： 
test=# select * from tb1; 
a | b | c 
---+---+--- 
2 | B | 2 
(1 rows)

**Comment by PJMODOS** [comment]
Ah yes, upstream table needs REPLICA IDENTITY FULL if you want to filter DELETEs on columns that are not part of primary key. Need to add proper check for that.

Btw what's syslogical?
