### ISSUE TITLE
pglogical + barman

### ISSUE THREAD

**Issue by noizo** [2ndQuadrant/pglogical#96]
Is there any solution, for setting up Master, to be backed up by Barman, and some tables replicated with pglogical at the same time?

all comes to
`wal_level = replica/logical`

**Comment by PJMODOS** [comment]
Not quite sure what is the problem here? logical is higher wal_level than replica so it contains all replica does.

**Comment by noizo** [comment]
No problem after your explanation.
Unfortunately documentation does not stick to that differences directly.
It is only mentioned...
So case closed and thatnks!

**Comment by saurabhnanda** [comment]
I'm in a similar situation, where I already have `barman` configured and working for backups, but need to _also_ configure `pglogical` for a "hot migration" from 9.4.x => 11.x 

Will barman **and** pglogical, both, work if I set `wal_level=logical` on the primary PG server?

**Comment by noizo** [comment]
Yes
