### ISSUE TITLE
Can't assign to "stdin" on all platforms

### ISSUE THREAD

**Issue by danmcd** [2ndQuadrant/pglogical#99]
One of my colleagues tried to compile pglogical on OmniOS (an illumos distro), and got an error on this line:

https://github.com/2ndQuadrant/pglogical/blob/master/pglogical_apply_spi.c#L493

The error is:

```
pglogical_apply_spi.c:493:8: error: lvalue required as left operand of assignment
  stdin = pglcstate->copy_read_file;
        ^
```

On illumos, stdin, stdout, and stderr are macros which offset into an array of FILE structures.  Assigning to "stdin" is illegal.

I'd recommend the following patch:

```patch
--- pglogical_apply_spi.c.orig  Mon May 15 15:50:41 2017
+++ pglogical_apply_spi.c       Mon May 15 15:52:27 2017
@@ -454,7 +454,7 @@
 pglogical_proccess_copy(pglogical_copyState *pglcstate)
 {
        uint64  processed;
-       FILE    *save_stdin;
+       FILE    save_stdin;
 
        if (!pglcstate->copy_parsetree || !pglcstate->copy_buffered_tuples)
                return;
@@ -487,10 +487,13 @@
         * The COPY statement previously crafted will read from STDIN. So we
         * override the 'stdin' stream to point to the read end of the pipe created
         * for this relation. Before that we save the current 'stdin' stream and
-        * restore it back when the COPY is done
+        * restore it back when the COPY is done.
+        *
+        * NOTE: Not all platforms allow assignment to stdin. Use whole-structure
+        * copy instead.
         */
-       save_stdin = stdin;
-       stdin = pglcstate->copy_read_file;
+       save_stdin = *stdin;
+       *stdin = pglcstate->copy_read_file;
 
        /* COPY may call into SPI (triggers, ...) and we already are in SPI. */
        SPI_push();
@@ -502,9 +505,11 @@
        /* Clean up SPI state */
        SPI_pop();
 
+       /* Resynch copy_read_file before closing... */
+       *pglcstate->copy_read_file = *stdin;
        fclose(pglcstate->copy_read_file);
        pglcstate->copy_read_file = NULL;
-       stdin = save_stdin;
+       *stdin = save_stdin;
 
        /* Ensure we processed correct number of tuples */
        Assert(processed == pglcstate->copy_buffered_tuples);
```

I'm assuming copy_read_file isn't accessed between the save and restore.

**Comment by gmile** [comment]
We're seeing the same issue when compiling 2.0 under Alpine in docker. Is there anything we could do to help get this fixed?

**Comment by gmile** [comment]
@danmcd after [applying your patch](https://github.com/gmile/pglogical/commit/c078cfedb4aa40302a0cc01f377be5574e899523), I get pass through the initial problem, but get following error instead:

```
pglogical_apply_spi.c: In function 'pglogical_proccess_copy':
pglogical_apply_spi.c:457:7: error: storage size of 'save_stdin' isn't known
  FILE save_stdin;
       ^~~~~~~~~~
pglogical_apply_spi.c:495:15: error: dereferencing pointer to incomplete type 'FILE {aka struct _IO_FILE}'
  save_stdin = *stdin;
               ^
pglogical_apply_spi.c:509:3: error: dereferencing pointer to incomplete type 'FILE {aka struct _IO_FILE}'
   *pglcstate->copy_read_file = *stdin;
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
pglogical_apply_spi.c:457:7: warning: unused variable 'save_stdin' [-Wunused-variable]
  FILE save_stdin;
       ^~~~~~~~~~
make: *** [<builtin>: pglogical_apply_spi.o] Error 1
```

I use the following `Dockerfile` to build pglogical:

```dockerfile
FROM alpine

RUN apk add --update postgresql make libedit-dev libxml2-dev postgresql-dev zlib-dev g++

WORKDIR /

COPY . /

RUN make USE_PGXS=1 all
```

Any idea how to adjust the patch to solve the issue with build?

**Comment by danmcd** [comment]
Wow.  Because Linux distros use distinct stdlib/stdio implementations (like how many are there?!?), I'll bet Alpine's stdio has the property that "stdin" is not an lvalue (like illumos and Oracle Solaris), but its "FILE" type is abstracted away (i.e. Alpine's stdio.h doesn't include anything beyond "typedef FILE struct <something>" while not defining <something>.).  I'll bet for Alpine you'll need to include an additional header that actually DEFINES what "FILE" is as a structure.  I don't know Alpine, but I hear its libc is "musl" which clearly has stdin-not-an-lvalue in common with Solarish systems, but also abstracts FILE right out.

**Comment by gmile** [comment]
FYI I tried reverting back to this commit – 98d143c504cef33f58ee7dc2946ef0b4933b40b8, and compilation under my Alpine docker container worked.

**Comment by gmile** [comment]
I took master and reverted d2af7e1b9e47cf0d23e17b2778f329f7e7682acb locally, which resulted in the following patch, with which `pglogical` builds just fine under Alpine 3.6:

```diff
commit 26c0dea8555e0b3d1063fafde541df298f45abd6
Author: gmile <iamexile@gmail.com>
Date:   Tue Jul 4 06:49:29 2017 +0200

    Revert "Manipulate 'stdin' stream directly instead of dealing with underlying file"
    
    This reverts commit d2af7e1b9e47cf0d23e17b2778f329f7e7682acb.

diff --git a/pglogical_apply_spi.c b/pglogical_apply_spi.c
index 3eaccc4..111a4eb 100644
--- a/pglogical_apply_spi.c
+++ b/pglogical_apply_spi.c
@@ -454,7 +454,7 @@ static void
 pglogical_proccess_copy(pglogical_copyState *pglcstate)
 {
 	uint64	processed;
-	FILE	*save_stdin;
+	int		save_stdin;
 
 	if (!pglcstate->copy_parsetree || !pglcstate->copy_buffered_tuples)
 		return;
@@ -489,8 +489,16 @@ pglogical_proccess_copy(pglogical_copyState *pglcstate)
 	 * for this relation. Before that we save the current 'stdin' stream and
 	 * restore it back when the COPY is done
 	 */
-	save_stdin = stdin;
-	stdin = pglcstate->copy_read_file;
+	save_stdin = dup(fileno(stdin));
+	if (save_stdin < 0)
+		ereport(FATAL,
+				(errcode_for_file_access(),
+				 errmsg("could not save stdin: %m")));
+
+	if (dup2(fileno(pglcstate->copy_read_file), fileno(stdin)) < 0)
+		ereport(FATAL,
+				(errcode_for_file_access(),
+				 errmsg("could not redirect stdin: %m")));
 
 	/* COPY may call into SPI (triggers, ...) and we already are in SPI. */
 	SPI_push();
@@ -501,10 +509,17 @@ pglogical_proccess_copy(pglogical_copyState *pglcstate)
 
 	/* Clean up SPI state */
 	SPI_pop();
+	/*
+	 * Also close the read end of the pipe and restore 'stdin' to its original
+	 * value
+	 */
+	if (dup2(save_stdin, fileno(stdin)) < 0)
+		ereport(FATAL,
+				(errcode_for_file_access(),
+				 errmsg("could not restore stdin: %m")));
 
 	fclose(pglcstate->copy_read_file);
 	pglcstate->copy_read_file = NULL;
-	stdin = save_stdin;
 
 	/* Ensure we processed correct number of tuples */
 	Assert(processed == pglcstate->copy_buffered_tuples);
```

**Comment by gmile** [comment]
@pavanvd @PJMODOS can you please review the patch above? 

Inability to build under alpine forces us to consider using `1.x` version of `pglogical` (which builds fine, but lacks selective column replication) or newer `pglogical` but in a much heavier Debian container (20x the size as compare to alpine).

**Comment by danmcd** [comment]
Can you try that patch on an illumos distro (e.g. OmniOS, SmartOS, or OpenIndiana)?

**Comment by gmile** [comment]
@danmcd how do you compile pglogical under OmniOS? I installed OmniOS pretty quickly via vagrant (e.g. https://app.vagrantup.com/omnios/boxes/r151014), logged in and pulled the repo for pglogical, but I'm hitting a roadblock ([this?](https://stackoverflow.com/questions/18567963/makefile-errors-in-solaris-when-using-conditional-assignment)) when running `make USE_PGXS=1 all`:

```
vagrant@omnios-vagrant:/export/home/vagrant/pglogical$ make USE_PGXS=1 all
make: Fatal error in reader: Makefile, line 48: Badly formed macro assignment
vagrant@omnios-vagrant:/export/home/vagrant/pglogical$
```

**Comment by PJMODOS** [comment]
I don't really want to play with various ways of assignment of stdin, we've been bitten by changing the current code before. Instead I added `PGL_NO_STDIN_ASSIGN` which you can define using CPPFLAGS and it will skip this part of code altogether. Given that it's just INSERT speed optimization when SPI is used (which means in PostgresXL) I think it's fine to just leave it out on other platforms than linux.

In PG10 onward, we should be able to use Copy API for this anyway so in future we can support it again that way.

**Comment by PJMODOS** [comment]
The change above was added to pglogical 2.1 btw.

**Comment by jirutka** [comment]
> The change above was added to pglogical 2.1 btw.

What change? If you mean patch https://github.com/2ndQuadrant/pglogical/issues/99#issuecomment-312780008, then no, it’s not included in 2.1.0 (downloaded from http://packages.2ndquadrant.com/pglogical/tarballs/pglogical-2.1.0.tar.bz2).

**Comment by PJMODOS** [comment]
The change I explained above. I don't plan to integrate the patch from the comment.

**Comment by imissyouso** [comment]
```
PATH=/usr/local/bin:$PATH make clean all USE_PGXS=1 CPPFLAGS="-PGL_NO_STDIN_ASSIGN"; \
PATH=/usr/local/bin:$PATH make install USE_PGXS=1 CPPFLAGS="-PGL_NO_STDIN_ASSIGN";
```
I get error
```
gcc: error: unrecognized command line option '-PGL_NO_STDIN_ASSIGN'
```

**Comment by vltr** [comment]
> I get error
> 
> ```
> gcc: error: unrecognized command line option '-PGL_NO_STDIN_ASSIGN'
> ```

Try `make USE_PGXS=1 CPPFLAGS="-DPGL_NO_STDIN_ASSIGN"`
